Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-10, with the labels that each got.

#1572 Fix Hexblast interaction with increased/reduced resistance modifiers
  Modules/CalcOffence-3_0.lua
Labels: bug

#1568 Remove ModFlag.Melee from Exerted mods
  Modules/CalcOffence-3_0.lua
Labels: bug

#1569 Remove keywordFlag.Hit from many mods in ModParser
  Modules/ModParser-3_0.lua
Labels: bug

#1567 Bladestorm attack speed now only applies to bladestorm
  Data/3_0/Skills/act_str.lua
Labels: bug

#1566 Add enemy modifiers section for self-bleed chance
  Modules/CalcSections-3_0.lua
Labels: bug

#1565 Adding calc effect of divergant rallying
  Modules/CalcPerform.lua
Labels: bug

#1564 Fixing inversion of static strike repeat benefits
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1554 README for using ooz extractor
  Export/ggpk/README.md
Labels: documentation

#1553 Fix Mjolner and Cospri's Malice supports
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/ModParser-3_0.lua
Labels: enhancement

#1549 Fix catalyst tags on Emberwake
  Data/Uniques/ring.lua
Labels: bug

#1576 Fix Flame Wall added damage not working with Minions
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#1558 Fix Curse mods on the tree not applying correctly
  Data/3_0/Skills/spectre.lua
  Data/3_0/Skills/sup_int.lua
  Export/Skills/spectre.txt
  Export/Skills/sup_int.txt
  Modules/CalcActiveSkill.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1555 Add Snow Rhex spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1559 fix(load-quality): when overriding quality also pass existing qual
  Classes/ImportTab.lua
  Classes/SkillsTab.lua
Labels: bug

#1606 Make ailment mode apply to non-damaging ailments
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement, hacktoberfest-accepted

#1611 Fix 3.12 gems changes
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/spectre.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
  Export/Skills/spectre.txt
  Modules/ModParser-3_0.lua
Labels: bug

#1603 Add TotalPoisonDPS to combineStat list for Average Hit attack skills
  Modules/CalcOffence-3_0.lua
Labels: bug, enhancement

#1599 Updates for Might and Influence Jewel
  Data/Uniques/jewel.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1590 Change "Curses" to "Hexes" in "Is Enemy a Boss?" tooltip
  Modules/ConfigOptions.lua
Labels: enhancement

#1586 Spell damage applied to attack damage is now a mod like cast speed to…
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1583 Add Replica Forbidden Shako
  Data/Generated.lua
Labels: enhancement

#1578 Fix Siphoning Charges limit
  Modules/CalcSetup.lua
  Modules/ModParser-3_0.lua
Labels: bug

#311 Support Infernal Blow
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ModParser-3_0.lua
Labels: enhancement

#1616 Issue 1613 - Adding eHP values to power report
  Modules/Data.lua
Labels: enhancement

#1663 Fix gem quality export
  Data/3_0/Skills/other.lua
  Data/3_0/Skills/sup_dex.lua
  Data/3_0/Skills/sup_int.lua
  Export/Scripts/skills.lua
  Export/spec.lua
Labels: bug

#1656 Fix aura buffs for purity of elements and vaal impurities
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
Labels: bug

#1642 Issue 1626 - Caps accuracy at 0
  Modules/CalcOffence-3_0.lua
Labels: hacktoberfest-accepted

#1650 Adding duration as dps mod to storm burst
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: enhancement

#1641 Separating code cleanup from #1628
  Classes/TreeTab.lua
Labels: hacktoberfest-accepted

#1634 Issue 1633 - Fix Voidforge wording
  Data/Uniques/sword.lua
  Modules/ModParser-3_0.lua
Labels: hacktoberfest-accepted

#1629 Replica Wings of Entropy support
  Modules/ModParser-3_0.lua
Labels: hacktoberfest-accepted

#1628 Fixes #1519, #1562 - Thread of Hope socketed in cluster jewel
  Classes/PassiveSpec.lua
Labels: hacktoberfest-accepted

#1587 Add Contaminate skill from Sporeguard
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/ModParser-3_0.lua
Labels: enhancement

#1615 Adding column sorting for ListControl
  Classes/ListControl.lua
  Classes/PowerReportListControl.lua
Labels: hacktoberfest-accepted

#1365 Adding malachai artifice replica support
  Classes/ConfigTab.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1669 Update licence
  LICENSE.md
  README.md
  manifest.xml
  update_manifest.py
Labels: documentation

#1655 Mod tag conversion
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
  Modules/ModTools.lua
Labels: bug
