Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-09, with the labels that each got.

#1375 3.12 Tree Update
  GameVersions.lua
  TreeData/3_12/groups-3.png
  TreeData/3_12/skills-3.jpg
  TreeData/3_12/skills-disabled-3.jpg
  TreeData/3_12/tree.lua
  tree-3_12.zip
Labels: enhancement

#1363 Fixes Issue 1173 - Adds configurable charges for minions
  Modules/ConfigOptions.lua
Labels: enhancement

#1362 Fixes Issue 1310
  Classes/CalcsTab.lua
Labels: bug

#1352 Fix awakened blasphemy quality +1 curse skills
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
Labels: bug, enhancement

#1351 Add Scinteel Synthete spectre.
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1349 Add Templar Tactician spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1350 Now uses misc calc to use all changes of adding node
  Classes/CalcsTab.lua
Labels: documentation

#1342 Fix dashes
  Data/Uniques/body.lua
  Data/Uniques/staff.lua
Labels: documentation

#1336 Added support for the Ancient Waystones jewel
  Modules/ModParser-3_0.lua
Labels: enhancement

#1333 Life recharge display fix
  Modules/CalcSections-3_0.lua
Labels: bug

#1332 Total Net Regen
  Modules/Build.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: bug, enhancement

#1326 Remove VS solution file
  PathOfBuilding.sln
Labels: documentation

#1327 Generate Skin of the Lords
  Data/Generated.lua
  Data/Uniques/body.lua
  Modules/Data.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1323 Remove Powershell update script
  patch_fork.ps1
Labels: documentation

#1372 Update CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#1353 Fixing crash when using an old tree to view new keystones
  Modules/CalcPerform.lua
Labels: crash

#1313 Improve general breakdown.mod function and Duration Mod breakdown
  Modules/CalcBreakdown.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: enhancement

#1405 Adds Impending Doom secondary
  Classes/SkillsTab.lua
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/spectre.lua
  Data/3_0/Skills/sup_dex.lua
  Data/3_0/Skills/sup_int.lua
  Data/3_0/Skills/sup_str.lua
  Export/Scripts/skills.lua
  Export/Skills/sup_int.txt
Labels: bug

#1393 Implemented Endless Misery Threshold Jewel
  Modules/ModParser-3_0.lua
Labels: enhancement

#1379 chore: Update rundown.md
  docs/rundown.md
Labels: documentation

#1364 % of cast speed applied to attack speed
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1319 Add Primal Crushclaw Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1416 Reworking firestorm to give DPS for first impact
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: enhancement

#1460 Replica dreamfeather
  Modules/ModParser-3_0.lua
Labels: enhancement

#1458 Added Replica Alberon's Warpath mod
  Modules/ModParser-3_0.lua
Labels: enhancement

#1459 Implemented New Discharge
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: enhancement

#1456 Negative accuracy fix
  Modules/CalcDefence-3_0.lua
Labels: bug

#1455 Implemented Corrupted Soul granted by Replica Soul Tether
  Modules/ModParser-3_0.lua
Labels: enhancement

#1440 Huge Stat Fixes
  Export/Scripts/skills.lua
  Export/Scripts/statdesc.lua
  Export/statdesc.lua
  Modules/Common.lua
  Modules/StatDescriber.lua
Labels: bug

#1453 Fixing assassin's mark crit multi mod
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
  Modules/CalcOffence-3_0.lua
Labels: bug

#1435 Glancing Blows fix
  Modules/ModParser-3_0.lua
Labels: bug

#1433 "Is the enemy Deathmarked?" fix
  Modules/ConfigOptions.lua
Labels: bug

#1406 Update Steel skills
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#1439 Adding tooltip when hovering over the items in the variant dropdown t…
  Classes/SkillsTab.lua
Labels: enhancement

#1461 Implemented Replica Cold Iron Point
  Modules/ModParser-3_0.lua
Labels: enhancement

#1432 Vitality fix
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1417 Heist gems alt quals
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/sup_dex.lua
  Data/3_0/Skills/sup_int.lua
  Data/3_0/Skills/sup_str.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_str.txt
  Export/Skills/sup_dex.txt
  Export/Skills/sup_int.txt
  Export/Skills/sup_str.txt
Labels: enhancement

#1366 Add a "Power Report" Feature: Displays report of passive node efficacy based on currently selected heat map
  Classes/PassiveTreeView.lua
  Classes/PowerReportListControl.lua
  Classes/TreeTab.lua
Labels: enhancement

#1466 added support for Replica Nebulis
  Modules/CalcDefence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1345 Add new 3.12 uniques
  Data/Uniques/amulet.lua
  Data/Uniques/axe.lua
  Data/Uniques/belt.lua
  Data/Uniques/body.lua
  Data/Uniques/boots.lua
  Data/Uniques/bow.lua
  Data/Uniques/claw.lua
  Data/Uniques/dagger.lua
  Data/Uniques/flask.lua
  Data/Uniques/gloves.lua
  Data/Uniques/helmet.lua
  Data/Uniques/jewel.lua
  Data/Uniques/mace.lua
  Data/Uniques/quiver.lua
  Data/Uniques/ring.lua
  Data/Uniques/shield.lua
  Data/Uniques/staff.lua
  Data/Uniques/sword.lua
  Data/Uniques/wand.lua
Labels: enhancement

#1358 Add config option for Phys Gained as Random Element mods
  Modules/CalcOffence-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1296 Show Combined DPS output more consistently on DoT skills
  Classes/SkillsTab.lua
  Modules/Build.lua
  Modules/CalcOffence-3_0.lua
  Modules/Data.lua
Labels: bug

#1481 Fix Supreme Ego applying aura effect incorrectly
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1476 Add Frost Auto-scout spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1474 Add Syndicate Operative spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1469 Triple Damage Implementation
  Data/3_0/SkillStatMap.lua
  Data/Uniques/sword.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1468 Add Cloud Retch Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1360 Feature: legion jewels with modifiable passives
  Classes/ItemsTab.lua
  Classes/PassiveSpec.lua
  Classes/PassiveTree.lua
  Classes/PassiveTreeView.lua
  Classes/TreeTab.lua
  Data/3_0/LegionPassives.lua
  Data/Uniques/jewel.lua
  Export/Scripts/legionPassives.lua
  Modules/Build.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSetup.lua
  Modules/Common.lua
  Modules/Data.lua
  Modules/ModParser-3_0.lua
  TreeData/legion/skills-additional-3.jpg
  TreeData/legion/skills-additional-disabled-3.jpg
  TreeData/legion/tree-legion.lua
Labels: enhancement, long term

#1482 Fix/importing of alt gems
  Classes/ImportTab.lua
  Classes/SkillsTab.lua
Labels: bug, enhancement

#1529 Update Animate Weapon
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
  Modules/ConfigOptions.lua
Labels: bug, enhancement

#1516 Update ProjectileCount formula for accuracy, parse Spectral Shield Throw helmet enchantment
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1490 Fix Growing Agony mod not appearing
  Data/Uniques/jewel.lua
Labels: bug

#1545 Fix Doom
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1541 Changing wording of Agnerod's staves
  Data/Uniques/staff.lua
Labels: bug

#1534 Implements Combat Rhythm Cluster Notable
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1533 Fix Perforate more aoe in Sand Stance
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1501 Improvements for Power Report
  Classes/CalcsTab.lua
  Classes/PowerReportListControl.lua
  Classes/TreeTab.lua
Labels: enhancement

#1530 Implement DeathWish
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/other.lua
  Data/Uniques/helmet.lua
  Export/Skills/other.txt
  Modules/CalcOffence-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement
