Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-06, with the labels that each got.

#953 Deal No Non-Lightning Damage mod implementation
  Modules/ModParser-3_0.lua
Labels: enhancement

#952 Fix Feeding Frenzy Tooltip
  Modules/ConfigOptions.lua
Labels: bug

#949 Support the zero case for "there is at most one rare or unique enemy nearby"
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#950 Update elusive tooltip numbers
  Modules/ConfigOptions.lua
Labels: documentation

#944 fix elusive calculations from gems
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/sup_dex.lua
  Export/Skills/act_dex.txt
  Export/Skills/sup_dex.txt
Labels: enhancement

#939 Total up "reduced Extra Damage from Critical Strikes"
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#937 Handle Liege of the Primordial golem elemental immunity
  Modules/ModParser-3_0.lua
Labels: enhancement

#938 Handle Arcane Blessing ailment immunity
  Modules/ModParser-3_0.lua
Labels: enhancement

#934 Handle Daresso's Courage block syntax
  Modules/ModParser-3_0.lua
Labels: enhancement

#931 Fix item slot not being displayed for belt skills
  Classes/SkillsTab.lua
Labels: bug

#933 Stormbind damage per improvement fix
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#927 Fix Snipe Stages
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
Labels: bug

#926 Specifying bleed stack sets "enemy is Bleeding"
  Modules/ConfigOptions.lua
Labels: enhancement

#919 move oil image loading out of tooltip constructor
  Classes/Tooltip.lua
Labels: bug

#916 Update pantheon upgrades for 3.10
  Data/3_0/Pantheons.lua
Labels: bug

#912 Clean up all uses of Life/ES/Mana Recovery Rates
  Classes/ItemsTab.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: documentation

#910 Update mod on Brittle Barrier
  Data/Uniques/jewel.lua
Labels: documentation

#911 Add better support for Soul Tether unique belt
  Data/Uniques/belt.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#908 Fix:20Q Awakened Generosity not increasing supported auras level
  Data/3_0/Skills/sup_str.lua
  Export/Skills/sup_str.txt
Labels: bug

#900 Add parsing for Tailwind mod on Hunter influenced boots
  Modules/ModParser-3_0.lua
Labels: enhancement

#893 Allow ifOption config options to have tooltips
  Classes/ConfigTab.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#891 Add support for Scorch, Brittle, and Sap
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#885 Update Area of Effect calculations
  Modules/CalcBreakdown.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/CalcTools.lua
  Modules/Data.lua
Labels: enhancement

#886 Fix faster bleeding mods not being displayed
  Modules/CalcSections-3_0.lua
Labels: enhancement

#882 Add support for First Among Equals node
  Modules/ModParser-3_0.lua
Labels: enhancement

#874 Fix for Dying Sun not changing "increased" to "reduced" properly for the first mod.
  Modules/ItemTools.lua
Labels: bug

#881 Totem improvements
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#873 Fix for Willowgift missing an open parenthesis on a mod
  Data/Uniques/amulet.lua
Labels: bug

#871 Fix for crash accessing nil when canceling an item craft
  Classes/ItemsTab.lua
Labels: bug

#872 Fix for Berserk quality attack damage not applying properly.
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#866 Fix hybrid flasks not counting as life/mana flasks
  Modules/CalcPerform.lua
Labels: bug

#813 Add the 75% cap for buff expiration slowness
  Modules/CalcOffence-3_0.lua
  Modules/Data.lua
Labels: bug

#816 Server hardcaps
  Modules/CalcOffence-3_0.lua
  Modules/Data.lua
Labels: enhancement

#955 Support Attack Crit Multi
  Modules/ModParser-3_0.lua
Labels: bug

#942 Update wording on Warlord's Reach
  Data/Uniques/jewel.lua
Labels: documentation

#943 Fix experience multiplier
  Modules/Data.lua
Labels: bug

#941 Sort crafting options by prefix/suffix, add tag
  Classes/ItemsTab.lua
Labels: enhancement

#923 Update wording on Survival Skills
  Data/Uniques/jewel.lua
Labels: bug

#904 Update mod on Mon'tregul's Grasp
  Data/Uniques/mace.lua
Labels: bug

#918 Fix item format on Speaker's Wreath
  Data/Uniques/helmet.lua
Labels: bug

#903 Add Mortal Conviction to Skin of the Lords
  Data/Uniques/body.lua
  Modules/ModParser-3_0.lua
Labels: bug

#845 Fix bleed infliction/immunity mods
  Data/Uniques/body.lua
  Data/Uniques/boots.lua
  Modules/ModParser-3_0.lua
Labels: bug

#988 Fix allocation of cluster jewels on tree update
  Classes/TreeTab.lua
Labels: bug

#1037 Adds all the new gems from 3.11
  Data/3_0/Bases/amulet.lua
  Data/3_0/Bases/axe.lua
  Data/3_0/Bases/bow.lua
  Data/3_0/Bases/dagger.lua
  Data/3_0/Bases/mace.lua
  Data/3_0/Bases/quiver.lua
  Data/3_0/Bases/ring.lua
  Data/3_0/Bases/staff.lua
  Data/3_0/Bases/sword.lua
  Data/3_0/ClusterJewels.lua
  Data/3_0/EnchantmentHelmet.lua
  Data/3_0/Gems.lua
  Data/3_0/ModFlask.lua
  Data/3_0/ModItem.lua
  Data/3_0/ModJewel.lua
  Data/3_0/ModJewelAbyss.lua
  Data/3_0/ModJewelCluster.lua
  Data/3_0/ModMaster.lua
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/glove.lua
  Data/3_0/Skills/minion.lua
  Data/3_0/Skills/other.lua
  Data/3_0/Skills/spectre.lua
  Data/3_0/Skills/sup_dex.lua
  Data/3_0/Skills/sup_int.lua
  Data/3_0/Skills/sup_str.lua
  Data/3_0/Spectres.lua
  Data/3_0/StatDescriptions/active_skill_gem_stat_descriptions.lua
  Data/3_0/StatDescriptions/brand_skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/buff_skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/gem_stat_descriptions.lua
  Data/3_0/StatDescriptions/minion_attack_skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/minion_skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/minion_spell_skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/monster_stat_descriptions.lua
  Data/3_0/StatDescriptions/skill_stat_descriptions.lua
  Data/3_0/StatDescriptions/stat_descriptions.lua
  Data/Global.lua
  Export/Scripts/skills.lua
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
  Export/Skills/sup_int.txt
  Export/Skills/sup_str.txt
  Export/spec.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1005 Fix support for Corpse Pact on 3.11 Tree
  Modules/ModParser-3_0.lua
Labels: bug

#1003 Fix Brand keyword flag
  Data/Global.lua
  Modules/CalcActiveSkill.lua
Labels: bug

#1004 Support Stance mods on the tree
  Modules/ModParser-3_0.lua
Labels: enhancement

#981 Update Hyrri's Truth
  Data/Uniques/amulet.lua
Labels: bug

#1020 Allow More Activation Frequency for Brands
  Export/Skills/act_int.txt
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1056 Update all old uniques to 3.11.0
  Data/Uniques/amulet.lua
  Data/Uniques/axe.lua
  Data/Uniques/belt.lua
  Data/Uniques/boots.lua
  Data/Uniques/bow.lua
  Data/Uniques/claw.lua
  Data/Uniques/dagger.lua
  Data/Uniques/gloves.lua
  Data/Uniques/helmet.lua
  Data/Uniques/jewel.lua
  Data/Uniques/mace.lua
  Data/Uniques/ring.lua
  Data/Uniques/shield.lua
  Data/Uniques/staff.lua
  Data/Uniques/sword.lua
  Data/Uniques/wand.lua
Labels: bug, enhancement

#1054 Adding support for sunder's aoe multiplier
  Export/Skills/act_str.txt
Labels: bug

#1052 Updated tectonic slam for 3.11
  Export/Skills/act_str.txt
Labels: bug

#1053 Updating static strike parts
  Export/Skills/act_str.txt
Labels: bug

#1047 Update Herald of Purity to 3.11
  Export/Skills/act_str.txt
Labels: bug, enhancement

#1050 Updating Inevitability threshold jewel
  Modules/ModParser-3_0.lua
Labels: bug

#1044 Implement Storm Secret unique ring
  Export/Skills/act_int.txt
  Modules/ModParser-3_0.lua
Labels: enhancement

#1045 Add missing spell tags to atlas influence spectre skills
  Export/Skills/spectre.txt
Labels: bug

#1029 Correctly parse the new purposeful harbinger line
  Modules/CalcPerform.lua
  Modules/Data.lua
  Modules/ModParser-3_0.lua
Labels: bug, enhancement

#973 Movement speed is 150% of base
  Modules/CalcDefence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#972 Reverse knockback
  Modules/ModParser-3_0.lua
Labels: enhancement

#970 Bypass support
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#971 Projectile block
  Modules/CalcDefence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#969 Split degens
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug, enhancement

#1038 Glancing blows
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1033 Adding dropdown to select dps field for sorting support gems
  Classes/GemSelectControl.lua
  Classes/SkillsTab.lua
Labels: enhancement

#1014 Fix femur mods
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1019 Added KeywordFlag.MatchAll option to force all KeywordFlags to match rather than just any.
  Classes/ModDB.lua
  Classes/ModList.lua
  Data/Global.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1009 Add support for new Rage functionality in 3.11
  Modules/CalcDefence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#968 Reflect damage taken
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#966 Support "as though dealing more damage" for Shock, Chill, and Freeze
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#965 Update Tukohama's Fortress
  Data/Uniques/shield.lua
Labels: bug

#828 Update readme
  README.md
Labels: documentation

#1074 Add Baranite Sister Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1069 Allow calculating the maximum damage on Explosive Arrow
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
Labels: enhancement

#1070 Fix Staff Implicits
  Data/Uniques/staff.lua
Labels: bug

#1068 Fix Corpse Pact cap being too low
  Modules/ModParser-3_0.lua
Labels: bug

#1067 Fixes new Cluster Notables not showing on tree
  Data/3_0/ClusterJewels.lua
  TreeData/3_11/tree.lua
Labels: bug

#1097 Agnostic
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1098 Eternal youth
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1096 Supreme ego
  Modules/ModParser-3_0.lua
Labels: enhancement

#1092 Ehp Calc modes
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#1095 Update Soul Tether to 3.11
  Data/Uniques/belt.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1091 Support "If you've changed Stance Recently"
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1084 Fix Unbound Ailments Support not working with new ailments
  Data/3_0/SkillStatMap.lua
Labels: bug

#1078 Add Scale of Esh Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1081 Fix a couple of cases where Rage did not work correctly
  Data/3_0/Skills/sup_str.lua
  Export/Skills/sup_str.txt
  Modules/CalcDefence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1077 Fix Baranite Thaumaturge default attack
  Data/3_0/Skills/spectre.lua
  Export/Skills/spectre.txt
Labels: bug

#1076 Fix apostrophes in some tooltips
  TreeData/3_11/tree.lua
Labels: bug

#1103 Updated Pantheon
  Data/3_0/Pantheons.lua
  Export/spec.lua
Labels: bug

#1104 Fix Rage from Chain Hook
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1105 Add support for Rigwald's Command new mod
  Modules/ModParser-3_0.lua
Labels: enhancement
