Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-08, with the labels that each got.

#1305 Add Baranite Preacher Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1302 Fix Spectre Errors
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: bug

#1303 Add Redemption Knight Spectre
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#1301 Fix Crash for minion crit chance on consecrated ground
  Modules/ConfigOptions.lua
Labels: bug, crash

#1299 Update mod tags from 3.11.1e
  Data/3_0/ModItem.lua
Labels: enhancement

#1300 Fix Second Wind Cooldown
  Data/3_0/SkillStatMap.lua
Labels: bug

#1298 Fix Non-Channelling mana cost craft parsing
  Modules/ModParser-3_0.lua
Labels: enhancement

#1297 Add proper support for Carrion Golem
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/minion.lua
  Export/Skills/act_int.txt
  Export/Skills/minion.txt
  Modules/ConfigOptions.lua
Labels: bug, enhancement

#1264 Fix Issue 1263
  Modules/CalcOffence-3_0.lua
Labels: bug, crash
