Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-04, with the labels that each got.

#727 Change ailment thresholds in Calcs tab to use floats to prevent overflows
  Modules/CalcOffence-3_0.lua
Labels: bug

#698 Sort account history in import tab case insensitive
  Classes/ImportTab.lua
Labels: enhancement

#705 Make Ignite Duration breakdown show more consistently
  Modules/CalcOffence-3_0.lua
Labels: enhancement

#694 Add detailed debugging instructions for VS Code
  CONTRIBUTING.md
Labels: documentation

#687 Fix league character filter on subsequent imports
  Classes/ImportTab.lua
Labels: bug

#681 Fix sorting getting stuck
  Modules/ModParser-3_0.lua
Labels: bug

#671 Fix medium cluster jewel rendering
  Classes/PassiveSpec.lua
  Export/spec.lua
Labels: bug

#676 Juggernaut, Action speed cannot be slowed below base
  Modules/ModParser-3_0.lua
Labels: enhancement

#751 Fix for crafted and custom modifiers disappearing from custom items when prefix or suffixes are changed
  Classes/Item.lua
  Classes/ItemsTab.lua
Labels: bug

#748 Fix mod on Paradoxica
  Data/Uniques/sword.lua
Labels: bug

#742 Purposeful Harbinger Fix
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
  TreeData/3_10/tree.lua
Labels: bug

#746 Fix for tooltip display issue caused by a unicode apostrophe character being used for some cluster notable descriptions
  TreeData/3_10/tree.lua
Labels: bug

#741 Replenishing Presence fix
  Modules/CalcPerform.lua
Labels: bug

#713 Remove wrong limit on Synthesis unique rings
  Data/Uniques/ring.lua
Labels: bug

#686 Update branch name to PathOfBuildingCommunity
  patch_fork.ps1
Labels: documentation

#688 Show build name in title bar
  Classes/ImportTab.lua
  Classes/PassiveSpec.lua
  Modules/Build.lua
  Modules/Main.lua
Labels: enhancement

#685 Fix mod on Fortress Covenant
  Data/Uniques/jewel.lua
Labels: bug

#667 Fix Thread of Hope not working correctly when imported from characters
  Data/Uniques/jewel.lua
  Modules/ModParser-3_0.lua
Labels: bug

#663 Fix bug with variants of Doomfletch's Prism
  Data/Uniques/bow.lua
Labels: bug

#651 Fix bug where items with variants from old builds would be parsed incorrectly
  Classes/Item.lua
Labels: bug

#654 Fix level requirements of The Searing Touch
  Data/Uniques/staff.lua
Labels: bug

#766 Fix for crash when viewing a breakdown which includes a cluster node source
  Classes/CalcBreakdownControl.lua
Labels: bug

#765 Added attributes to the power stat list
  Modules/CalcPerform.lua
  Modules/Data.lua
Labels: enhancement

#764 Added conditions for "UsingLifeFlask" and "UsingManaFlask"
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#762 Fix for crash as described in issue #753
  Modules/CalcPerform.lua
Labels: bug

#757 Add parenthesis to GGPK function calls
  Export/Scripts/bases.lua
  Export/Scripts/cluster.lua
  Export/Scripts/enchant.lua
  Export/Scripts/essence.lua
  Export/Scripts/masters.lua
  Export/Scripts/minions.lua
  Export/Scripts/miscdata.lua
  Export/Scripts/mods.lua
  Export/Scripts/skills.lua
Labels: documentation

#759 Add config to toggle build name in titlebar
  Classes/TreeTab.lua
  Modules/Build.lua
  Modules/Main.lua
Labels: enhancement

#738 Implementation of Split Personality Jewel
  Classes/PassiveSpec.lua
  Classes/PassiveTreeView.lua
  Data/Uniques/jewel.lua
  Modules/CalcSetup.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#708 Re-add supported file extensions to manifest updater
  update_manifest.py
Labels: bug

#691 Update experience multiplier to take new game mechanics into account
  Modules/Common.lua
  Modules/Data.lua
Labels: enhancement

#665 DoT & Aura Calc Display Improvements
  Modules/CalcBreakdown.lua
  Modules/CalcOffence-2_6.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: enhancement

#789 Update Banner Skill Tag
  Data/3_0/Skills/act_str.lua
  Data/Global.lua
  Export/Scripts/skills.lua
Labels: enhancement

#778 Fix for the "Elusive" flag recursively checking for itself, causing a stack overflow.
  Modules/ConfigOptions.lua
Labels: bug

#776 Fix gem/cluster jewel importer
  Classes/ImportTab.lua
  Classes/SkillsTab.lua
  Data/3_0/ClusterJewels.lua
  Data/3_0/Gems.lua
  Data/3_0/Skills/sup_dex.lua
  Modules/Data.lua
Labels: bug, enhancement

#777 Fix for Hungry Loop attempting to support the skill with the Barrage skill instead of the Barrage support
  Modules/CalcSetup.lua
Labels: bug

#770 Update nightmare jewel wording
  Data/Uniques/jewel.lua
  Modules/ModParser-3_0.lua
Labels: bug

#763 Added "PercentStat" tag option for mods.
  Classes/CalcBreakdownControl.lua
  Classes/ModStore.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#682 Support Assailum and Snipe skill
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/CalcOffence-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#672 Calc subsections
  Classes/CalcSectionControl.lua
  Classes/CalcsTab.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: enhancement

#351 Changed Holy Relic display from DPS to average dmg
  Data/3_0/Skills/minion.lua
  Export/Skills/minion.txt
Labels: bug

#278 Added Thousands Separator support for tooltip numbers
  Modules/Build.lua
Labels: enhancement

#561 Support for Rapid Infusion notable
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#749 Fix for Master of Metal using 0 impale stacks if the configured number of stacks was blank
  Classes/ConfigTab.lua
  Classes/ModDB.lua
  Classes/ModStore.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#791 Master Of Command Implementation
  Modules/ModParser-3_0.lua
Labels: enhancement

#756 Added second influence dropdown in item crafting for creating dual-influenced items.
  Classes/DropDownControl.lua
  Classes/ImportTab.lua
  Classes/Item.lua
  Classes/ItemsTab.lua
  Modules/ItemTools.lua
Labels: enhancement

#795 Violent retaliation support
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#316 Life, mana, es on block
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#315 Avoidance
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#767 The exporter now includes the mod tags for bases and mods
  Export/Scripts/bases.lua
  Export/Scripts/masters.lua
  Export/Scripts/mods.lua
  Export/statdesc.lua
Labels: enhancement

#774 Fix for Mask of the Tribunal not contributing its mana reservation
  Modules/CalcPerform.lua
Labels: bug

#761 Catalyst support for crafted rare items
  Classes/Item.lua
  Classes/ItemsTab.lua
  Data/Uniques/amulet.lua
  Data/Uniques/belt.lua
  Data/Uniques/ring.lua
  Modules/ItemTools.lua
Labels: enhancement

#506 Added stats for Armour and Physical Damage Reduction
  Data/3_0/Misc.lua
  Data/3_0/SkillStatMap.lua
  Export/Scripts/miscdata.lua
  Export/spec.lua
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#505 Adds support for Martial Momentum
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement, wip

#158 Improve sidebar "combined DPS" display
  Modules/Build.lua
  Modules/CalcOffence-3_0.lua
Labels: enhancement

#803 Fix Doomfletch variant
  Data/Uniques/bow.lua
Labels: bug

#801 Fix issues with lucky hits
  Modules/CalcOffence-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug

#802 Add "Are you Channelling" Checkbox
  Modules/ConfigOptions.lua
Labels: enhancement

#740 Added 2 new Spectre types
  Data/3_0/Skills/spectre.lua
  Data/3_0/Spectres.lua
  Export/Minions/Spectres.txt
  Export/Skills/spectre.txt
Labels: enhancement

#721 Serve all app updates from this repo
  manifest.xml
Labels: documentation

#703 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#824 Fix for the "Show power" calculation thinking all nodes have more power when the impale stacks are configured to be higher than the max.
  Classes/ModDB.lua
  Classes/ModStore.lua
Labels: bug

#822 Fix for crash when hovering a source in the calcs when the source is a cluster jewel node.
  Classes/CalcBreakdownControl.lua
Labels: bug

#819 Fix Enemy Armour calculations
  Modules/CalcOffence-3_0.lua
Labels: bug

#820 Cluster jewel not importing correctly
  Data/3_0/ClusterJewels.lua
Labels: bug

#804 Fix parsing for Nebuloch mod
  Data/Uniques/mace.lua
  Modules/ModParser-3_0.lua
Labels: bug
