Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-03, with the labels that each got.

#282 Add support for Touch of Cruelty
  Modules/ModParser-3_0.lua
Labels: enhancement

#283 Add support for Fasting
  Modules/ModParser-3_0.lua
Labels: enhancement

#279 Add Algor Mortis and support for its mods
  Data/New.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#261 Add prerequisites to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#258 Change all repository references to PathOfBuildingCommunity
  CONTRIBUTING.md
Labels: documentation

#256 Add Intimidating Cry and Nearby Enemy multiplier for Rallying Cry
  Data/3_0/ModCache.lua
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/other.lua
  Export/Skills/act_str.txt
  Export/Skills/other.txt
  Modules/ModParser-3_0.lua
Labels: bug, enhancement

#251 Add "Charan's Sword" type to swords
  Export/Bases/sword.txt
Labels: bug

#249 Fix Soulrest granting incorrect Summon Phantasm skill
  Data/3_0/ModCache.lua
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/ModParser-3_0.lua
Labels: bug

#240 Fixes Item Parsing For Explicits That Contain ":"
  Classes/Item.lua
Labels: bug

#241 Fix Vengeance not working with Painforged
  Data/3_0/ModCache.lua
  Modules/ModParser-3_0.lua
Labels: bug

#238 Add support for mod on Sanctuary
  Modules/ModParser-3_0.lua
Labels: enhancement

#235 Consolidate resistances into single line in sidebar
  Modules/Build.lua
Labels: enhancement

#232 Fixed Cast On Critical Strike support quality stat not included in damage calculations
  Data/3_0/SkillStatMap.lua
Labels: bug

#281 Add Perfidy and support for its mods
  Data/New.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#236 Hide Tooltip When Holding CTRL
  Classes/PassiveTreeView.lua
Labels: enhancement

#229 Update Ballista placement speed
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/sup_str.lua
  Export/Skills/act_dex.txt
  Export/Skills/sup_str.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcSetup.lua
Labels: bug

#295 Implements Unhandeled Wandslinger Mods
  Modules/ModParser-3_0.lua
Labels: enhancement

#293 Add support for Self-fulfilling Prophecy
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#285 Add support for Disciple of Kitava
  Modules/ModParser-3_0.lua
Labels: enhancement

#250 Unencumbered Implementation
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#237 Implemented Perforate DPS calculations in Blood Stance
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#340 Add support for "if you have Stunned an Enemy Recently"
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#331 Added minion mod parser for Vicious Bite notable
  Modules/ModParser-3_0.lua
Labels: enhancement

#332 Add support for Skeletal Atrophy
  Modules/ModParser-3_0.lua
Labels: enhancement

#328 Add support for active brand limit and Sign of Purpose
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#318 Added conditional more multiplier of Groundslam for nearby enemies
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: enhancement

#320 Adds Profane Proxy Unique
  Data/New.lua
Labels: enhancement

#317 Implemented Cry Wolf Notable
  Data/3_0/Skills/act_str.lua
  Data/3_0/Skills/other.lua
  Export/Skills/act_str.txt
  Export/Skills/other.txt
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#313 Add support for mana spent recently mods
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#310 Fixes parsing "Requires Level:" on items
  Classes/Item.lua
Labels: bug

#252 Set Showing of Thousands separator to be on by default. Lined up their options in Options Popup
  Modules/Main.lua
Labels: enhancement

#341 Implemented Quick and Deadly Notable
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#302 Fix AffectedBy conditions
  Modules/CalcPerform.lua
Labels: bug

#292 Fix "with this weapon" modifier handling
  Modules/ModParser-3_0.lua
Labels: bug

#530 Align Ascendancies in 3.10 Tree
  TreeData/3_10/tree.lua
Labels: enhancement

#550 Fix 3.10 tree mods and add mods to ModParser
  Classes/PassiveTree.lua
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: bug

#427 Add support for Kineticism
  Modules/ModParser-3_0.lua
Labels: wip

#284 Implemented Stationary Keystones/Notables
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#253 Add initial code base rundown
  CONTRIBUTING.md
  docs/rundown.md
Labels: documentation

#583 Openarl 1.4.160 changes
  Classes/ImportTab.lua
  Classes/Item.lua
  Classes/ItemDBControl.lua
  Classes/ItemSlotControl.lua
  Classes/ItemsTab.lua
  Classes/PassiveSpec.lua
  Classes/PassiveTree.lua
  Classes/PassiveTreeView.lua
  Classes/TreeTab.lua
  Data/3_0/Bases/jewel.lua
  Data/3_0/Bases/staff.lua
  Data/3_0/ClusterJewels.lua
  Data/3_0/Misc.lua
  Data/3_0/ModFlask.lua
  Data/3_0/ModJewelCluster.lua
  Data/3_0/Rares.lua
  Export/Bases/jewel.txt
  Export/Scripts/cluster.lua
  Export/Scripts/mods.lua
  Export/spec.lua
  Modules/CalcSetup.lua
  Modules/Data.lua
  Modules/Main.lua
  Modules/ModParser-3_0.lua
  TreeData/3_10/tree.lua
  TreeData/GroupBackgroundLargeHalfAlt.png
  TreeData/GroupBackgroundMediumAlt.png
  TreeData/GroupBackgroundSmallAlt.png
  TreeData/JewelCircle1Inverse.png
  TreeData/JewelSocketActiveAbyssAlt.png
  TreeData/JewelSocketActiveBlueAlt.png
  TreeData/JewelSocketActiveGreenAlt.png
  TreeData/JewelSocketActivePrismaticAlt.png
  TreeData/JewelSocketActiveRedAlt.png
  TreeData/JewelSocketAltActive.png
  TreeData/JewelSocketAltCanAllocate.png
  TreeData/JewelSocketAltNormal.png
  TreeData/JewelSocketClusterAltCanAllocate1Large.png
  TreeData/JewelSocketClusterAltCanAllocate1Medium.png
  TreeData/JewelSocketClusterAltCanAllocate1Small.png
  TreeData/JewelSocketClusterAltNormal1Large.png
  TreeData/JewelSocketClusterAltNormal1Medium.png
  TreeData/JewelSocketClusterAltNormal1Small.png
  tree-3_10.zip
Labels: enhancement

#354 Add parsing for "Bloodscent" notable
  Modules/ModParser-3_0.lua
Labels: enhancement

#616 Fix error when socketing non cluster jewel
  Classes/PassiveSpec.lua
Labels: bug

#614 Add back in support for unencumbered
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#615 Fix more poision damage mod applying to attacks
  Modules/ModParser-3_0.lua
Labels: bug

#613 Fix guard skill parsing
  Modules/ModParser-3_0.lua
Labels: bug

#611 Openarl Release 1.4.163 Changes
  Classes/CalcBreakdownControl.lua
  Classes/GemSelectControl.lua
  Classes/Item.lua
  Classes/ItemSlotControl.lua
  Classes/ItemsTab.lua
  Classes/PassiveSpec.lua
  Classes/PassiveSpecListControl.lua
  Classes/PassiveTree.lua
  Classes/PassiveTreeView.lua
  Data/3_0/Bases/jewel.lua
  Data/3_0/ClusterJewels.lua
  Data/3_0/EnchantmentHelmet.lua
  Data/3_0/Gems.lua
  Data/3_0/ModFlask.lua
  Data/3_0/ModItem.lua
  Data/3_0/ModJewel.lua
  Data/3_0/ModJewelAbyss.lua
  Data/3_0/ModJewelCluster.lua
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/sup_dex.lua
  Data/3_0/Skills/sup_int.lua
  Data/New.lua
  Data/Uniques/body.lua
  Data/Uniques/boots.lua
  Data/Uniques/gloves.lua
  Data/Uniques/jewel.lua
  Export/Scripts/cluster.lua
  Export/Scripts/enchant.lua
  Export/Scripts/mods.lua
  Export/Scripts/skills.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/sup_dex.txt
  Export/Skills/sup_int.txt
  Export/spec.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/Data.lua
  Modules/ModParser-3_0.lua
  TreeData/3_10/groups-3.png
  TreeData/3_10/skills-3.jpg
  TreeData/3_10/skills-disabled-3.jpg
  TreeData/3_10/tree.lua
  tree-3_10.zip
Labels: enhancement

#587 Support Fork calculations
  Data/3_0/SkillStatMap.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#551 Support for Surging Vitality notable (burst life regen)
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#514 Add support for # of heralds multiplier and affected by herald condition
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#466 Added support for Heart of Iron Notable
  Modules/CalcDefence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#353 Remove DPS display from the minion stats in the sidebar if the showAverage flag is set
  Modules/Build.lua
Labels: enhancement

#641 Fix "while stationary" condition breaking old builds
  Modules/ConfigOptions.lua
Labels: bug

#634 Clean up mod parser
  Modules/ModParser-3_0.lua
Labels: enhancement

#633 Fix typo
  Classes/PassiveSpec.lua
Labels: enhancement

#619 Update uniques rebalanced in 3.10
  Data/Uniques/amulet.lua
  Data/Uniques/body.lua
  Data/Uniques/bow.lua
  Data/Uniques/flask.lua
  Data/Uniques/gloves.lua
  Data/Uniques/helmet.lua
  Data/Uniques/jewel.lua
  Data/Uniques/mace.lua
  Data/Uniques/shield.lua
  Data/Uniques/sword.lua
  Data/Uniques/wand.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#592 Add support for minion mods on Ghastly Eye Jewels
  Modules/ModParser-3_0.lua
Labels: enhancement

#623 Change # of Brands Attached config option to apply globally
  Modules/ConfigOptions.lua
Labels: bug
