Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-12, with the labels that each got.

#1337 Implement Stages input box in sidebar and Calcs tab
  Classes/CalcsTab.lua
  Classes/SkillsTab.lua
  Data/Skills/act_dex.lua
  Data/Skills/act_int.lua
  Data/Skills/other.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/other.txt
  Modules/Build.lua
  Modules/CalcActiveSkill.lua
  Modules/CalcOffence.lua
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/ModParser.lua
Labels: enhancement

#1718 Refactor keystone data
  Data/Generated.lua
  Modules/Data.lua
Labels: documentation

#1719 Add preFlagList entry for non-vaal skills craft
  Modules/ModParser.lua
Labels: enhancement

#1725 Fixes #1724 - Anointed notables not showing as allocated on the tree
  Classes/PassiveTree.lua
Labels: bug

#1733 Changing bases with variants
  Classes/Item.lua
  Data/Uniques/boots.lua
Labels: enhancement

#1734 Adding quality mods to Zealotry and Anger
  Data/SkillStatMap.lua
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
Labels: enhancement

#1739 Use brand limit from the Arcanist Brand instead of the main skill
  Modules/CalcPerform.lua
Labels: bug

#1742 Remove incorrect Watcher's Eye variant
  Data/Uniques/jewel.lua
Labels: bug

#1765 Improve support for Guard skills and effective life
  Data/Skills/act_int.lua
  Data/Skills/act_str.lua
  Data/Skills/other.lua
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
  Export/Skills/other.txt
  Modules/CalcDefence.lua
  Modules/CalcPerform.lua
  Modules/CalcSections.lua
  Modules/ModParser.lua
Labels: enhancement

#1766 Add support for skills granted by tree nodes
  Classes/SkillsTab.lua
  Data/Skills/other.lua
  Export/Skills/other.txt
  Modules/CalcSetup.lua
  Modules/ModParser.lua
Labels: enhancement

#1767 Add tooltip to skill gem drop-down
  Classes/GemSelectControl.lua
Labels: enhancement
