Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-07, with the labels that each got.

#1162 Fix all sources of Withered, implement Abhorrent Interrogation unique gloves
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/sup_dex.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/sup_dex.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug, documentation, enhancement

#1163 Implement Eye of Malice unique helmet
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1160 Update default number of Abyssal sockets on Shroud of the Lightless
  Data/Uniques/body.lua
Labels: bug

#1158 Fix for the removable crafts remaining after editing an item.
  Classes/ItemsTab.lua
Labels: bug

#1150 Add new harvest league uniques
  Data/Uniques/amulet.lua
  Data/Uniques/belt.lua
  Data/Uniques/body.lua
  Data/Uniques/claw.lua
  Data/Uniques/gloves.lua
  Data/Uniques/helmet.lua
  Data/Uniques/quiver.lua
  Data/Uniques/ring.lua
  Data/Uniques/shield.lua
  Data/Uniques/staff.lua
Labels: enhancement

#1157 Fix Charged Mines quality
  Data/3_0/SkillStatMap.lua
Labels: bug

#1146 Fix parsing for Cat and Avian Aspect duration mods
  Modules/ModParser-3_0.lua
Labels: bug

#1144 Fix Avian Tornado showing DPS numbers
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
Labels: bug

#1145 Fix Wintertide Brand gem quality
  Data/3_0/SkillStatMap.lua
Labels: bug

#1143 Vaal Molten Shell More Armour
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1140 Add tables to Ailment Threshold calculations
  Classes/CalcBreakdownControl.lua
  Modules/CalcOffence-3_0.lua
Labels: enhancement

#1141 Add commas to Calcs tab breakdowns/tooltips
  Classes/CalcBreakdownControl.lua
Labels: enhancement

#1136 Add hit rate to Orb of Storms
  Data/3_0/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#1131 Fixes #1130
  Classes/SkillsTab.lua
Labels: bug

#1127 Support Bonechill support gem, Chill improvements
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#1128 Unique upgrade paths missing
  Data/Uniques/shield.lua
Labels: bug

#1126 Move Shock application to CalcPerform, fix double shock on minions
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1120 Add Combust to Infernal Cry gem
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: enhancement

#1122 Fix The Nomad catalyst mod
  Data/Uniques/belt.lua
Labels: bug

#1113 Fix incorrect number of Brands attached to enemy with multiple Brand skills enabled
  Modules/CalcPerform.lua
Labels: bug

#1111 Handle some more display-only effects
  Modules/ModParser-3_0.lua
Labels: enhancement

#1112 Better Arcanist Brand support
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/sup_int.lua
  Export/Skills/act_int.txt
  Export/Skills/sup_int.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1132 Net regen rework
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: enhancement

#1172 Cluster jewel crafting now includes the new jewel socket enchants
  Classes/ItemsTab.lua
  Data/3_0/ModJewelCluster.lua
Labels: enhancement

#1169 Fix life and elemental catalysts not applying to Doryani's Invitation
  Data/Uniques/belt.lua
Labels: bug

#1142 Item tab unique hide by requirments
  Classes/ItemDBControl.lua
  Classes/ItemsTab.lua
Labels: enhancement

#1204 Add AoE Numbers for many skills
  Data/3_0/Skills/act_dex.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_dex.txt
  Export/Skills/act_int.txt
  Export/Skills/act_str.txt
  Modules/CalcOffence-3_0.lua
Labels: bug, documentation

#1206 Add support for Spectral Wolf buff
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1202 Over reservation
  Modules/CalcPerform.lua
Labels: bug, enhancement

#1200 Herald of Ash damage
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#1201 Molten shell and Vaal Molten shell damage
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#1198 Correct Arcane Surge scaling
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1192 Move Pride's Effect drop-down to the configs page
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#1193 Add proper support for Bannerman and Revelry
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug, enhancement

#1190 Fix Earthshatter AoE mod
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1191 Split mod on Abhorrent Interrogation gloves
  Data/Uniques/gloves.lua
Labels: bug

#1189 Support a couple of places where commas were not showing up in Calcs breakdowns
  Classes/CalcBreakdownControl.lua
Labels: enhancement

#1187 Add upgraded harbinger uniques
  Data/3_0/Skills/other.lua
  Data/Uniques/belt.lua
  Data/Uniques/helmet.lua
  Data/Uniques/quiver.lua
  Data/Uniques/shield.lua
  Data/Uniques/staff.lua
  Data/Uniques/sword.lua
  Export/Skills/other.txt
Labels: enhancement

#1185 Add Forbidden Shako
  Data/Generated.lua
  Data/New.lua
  Modules/Data.lua
Labels: enhancement

#1186 Fix reworded mod on Bloodseeker
  Data/Uniques/claw.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1181 Replenishing Presence fix
  Modules/ModParser-3_0.lua
Labels: bug

#1178 Shaman's Dominion global crit chance
  Modules/ConfigOptions.lua
Labels: bug

#1179 Fix Emberwake ignite stacking
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1177 Emberwake ignite duration
  Data/Uniques/ring.lua
Labels: bug

#1175 Add support for the +1 Curse on Awakened Curse on Hit
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
  Modules/CalcPerform.lua
Labels: bug

#1176 Watchers Eye fast damaging ailments mod
  Modules/ModParser-3_0.lua
Labels: bug

#1168 Automatically Shock enemies with guaranteed sources of Shock, add a couple of Effects to ailment tables
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/other.lua
  Export/Skills/act_int.txt
  Export/Skills/other.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1118 Changes needed to detect new-style installation
  Launch.lua
  Modules/Main.lua
Labels: documentation, enhancement

#1174 Improved tooltip for cluster jewel notables
  Classes/ItemsTab.lua
  Modules/Data.lua
Labels: enhancement

#1171 Restricts minimum charge count to maximum of the same charge
  Modules/CalcPerform.lua
Labels: bug

#1159 Top node and per-point heatmap changes
  Classes/CalcsTab.lua
  Classes/PassiveTreeView.lua
  Classes/TreeTab.lua
Labels: enhancement

#1164 Exerted Attacks
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1125 Added Bear's Girdle new unique
  Data/Uniques/belt.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1027 Add support for mods on Broken Faith
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#975 Add support for new mitigation mechanics involving armour and resistances
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/Data.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#979 Add better support for Blind and related interactions
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#850 Disable Unnerve for DOT
  Modules/CalcOffence-3_0.lua
Labels: wip

#527 Allows you to see all boxes when viewing many jewel sockets
  Classes/ItemsTab.lua
  Classes/Tooltip.lua
Labels: enhancement

#1210 Support for Warning Call cluster notable
  Modules/ModParser-3_0.lua
Labels: enhancement

#1209 Fixes For New Release
  Modules/CalcOffence-3_0.lua
Labels: bug

#1207 Better support for CwC, show "Trigger Rate" in sidebar
  Data/3_0/Skills/sup_int.lua
  Export/Skills/sup_int.txt
  Modules/Build.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
Labels: enhancement

#1208 Fixing errant operation order
  Classes/CalcsTab.lua
Labels: bug

#1220 Fix Saqawals Nest not scaling Aspect of the Avian properly on Allies
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1218 Fix Vinktar crash and a couple of OVERRIDE -> BASE
  Modules/CalcPerform.lua
  Modules/ModParser-3_0.lua
Labels: bug

#1219 Fix Rallying Cry damage cap and config
  Data/3_0/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/CalcOffence-3_0.lua
Labels: bug

#1215 BUG: Ascendancy points showing up on the nearby strong nodes in the heatmap
  Classes/PassiveTreeView.lua
Labels: bug

#1213 New node crash fix
  Classes/ConfigTab.lua
Labels: bug

#1251 Add parsing for a bunch of nodes
  Data/Uniques/belt.lua
  Modules/CalcPerform.lua
  Modules/CalcSetup.lua
  Modules/Calcs.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: bug, enhancement

#1248 Sort by Attack/Cast Speed and Crit Multi
  Modules/Data.lua
Labels: enhancement

#1247 Slipstream from Harbinger of Time support
  Data/3_0/Skills/other.lua
  Export/Skills/other.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#1245 Fix UI wording consistency and polish
  Modules/Build.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#1246 Add output for DoT multi for ailments, change Ignite Calc Mode to Ailment Calc Mode
  Modules/CalcBreakdown.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#1240 Fix Pride not working with old builds
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
Labels: bug

#1238 Explosive arrow fixes
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
Labels: bug

#1233 Adds crit chance for minions when enemy is on consecrated ground
  Modules/ConfigOptions.lua
Labels: bug

#1230 Support "Notable Passive Skills in Radius Instead Grant"
  Modules/CalcSetup.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1227 Remove anoint nodes from top node
  Classes/CalcsTab.lua
  Classes/PassiveTreeView.lua
Labels: bug, enhancement

#1229 Fix minion skills supported by CwC and Arcanist Brand
  Data/3_0/SkillStatMap.lua
  Data/3_0/Skills/act_int.lua
  Data/3_0/Skills/sup_int.lua
  Export/Skills/act_int.txt
  Export/Skills/sup_int.txt
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
Labels: bug

#1225 Emperors vigilance support
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1224 Fix imported Conqueror influences
  Classes/ImportTab.lua
Labels: bug

#1212 Added Calcs Warcry Breakdowns
  Data/3_0/Skills/sup_str.lua
  Export/Skills/sup_str.txt
  Modules/CalcDefence-3_0.lua
  Modules/CalcOffence-3_0.lua
  Modules/CalcPerform.lua
  Modules/CalcSections-3_0.lua
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement, wip

#1222 Adding Alternate Quality
  Classes/Item.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#1034 Adding brand activation count stat
  Modules/Build.lua
  Modules/CalcOffence-3_0.lua
Labels: enhancement

#556 Adds support for Virulence Stack Changes
  Classes/ModStore.lua
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#287 Support Burning Arrow Debuff
  Data/3_0/Skills/act_dex.lua
  Export/Skills/act_dex.txt
  Modules/CalcOffence-3_0.lua
  Modules/ModParser-3_0.lua
Labels: enhancement

#257 Added support for Siegebreaker 'Minions spread caustic ground on death' modifier
  Data/3_0/Skills/minion.lua
  Export/Skills/minion.txt
  Modules/ModParser-3_0.lua
Labels: enhancement

#243 Fixed incorrect display of evasion chance in calc tab
  Modules/CalcDefence-3_0.lua
  Modules/CalcSections-3_0.lua
Labels: enhancement, wip

#1252 Add Lucky Hits Override
  Modules/ModParser-3_0.lua
Labels: enhancement

#1235 Fix Eye of Malice not applying to Ignite damage
  Modules/CalcOffence-3_0.lua
Labels: bug

#1228 Update mods on Impresence
  Data/Uniques/amulet.lua
Labels: enhancement

#1258 Fix Dancing Dervish Crash
  Modules/CalcOffence-3_0.lua
Labels: bug

#1255 Fix Chaos DoT Multiplier not showing up in Poison DoT Multi breakdown
  Modules/CalcSections-3_0.lua
Labels: bug

#1257 Fix Seismic Cry damage and Fist of War ailment calculations
  Data/3_0/Skills/sup_str.lua
  Export/Skills/sup_str.txt
  Modules/CalcOffence-3_0.lua
Labels: bug

#1254 Fix Siegebreaker Belt Bug
  Modules/ModParser-3_0.lua
Labels: bug
