Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2020-11, with the labels that each got.

#1750 Fix creating new builds
  Modules/Build.lua
Labels: bug

#1477 Add support for exporting data from a Steam install
  CONTRIBUTING.md
  Export/Classes/GGPKData.lua
  Export/DatView.sln
  Export/Main.lua
Labels: documentation

#1696 Fix The Peregrine variants
  Data/Uniques/helmet.lua
Labels: bug

#1698 Removing unused variables and 'nil' being displayed in DoT breakdowns
  Modules/CalcBreakdown.lua
  Modules/CalcOffence.lua
Labels: bug

#1708 Fixes #1694 - Quality should round towards 0 in the case of negative stats
  Modules/CalcTools.lua
Labels: bug

#1715 Fixes #1714 - Trim whitespace from item base names
  Export/Scripts/bases.lua
Labels: bug

#1731 Fixing dominating blow quality to apply to minions
  Data/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#1738 Fixes #1717 - Adding enchantment mod for sigil of power
  Modules/ModParser.lua
Labels: enhancement

#1749 Fix gem requirements
  Modules/Build.lua
  Modules/CalcTools.lua
Labels: bug

#1751 Fixes #1748 - Adding parsing for new Rolling Flames wording
  Modules/ModParser.lua
Labels: enhancement

#1752 Adding logic to disable alt ailments when ele focus is used
  Data/SkillStatMap.lua
  Modules/CalcOffence.lua
Labels: bug

#1753 Fixes #1741 - Adding separation of rune daggers, warstaves, and convoking wand
  Data/Bases/dagger.lua
  Data/Bases/staff.lua
  Data/Bases/wand.lua
  Export/Bases/dagger.txt
  Export/Bases/staff.txt
  Export/Bases/wand.txt
  Export/Scripts/bases.lua
Labels: enhancement

#1771 Fixes #1770 - Cold damage can always freeze, no need to double-count it
  Modules/CalcOffence.lua
  Modules/ModParser.lua
Labels: bug

#1773 Fix item text sanitization
  Modules/ItemTools.lua
Labels: bug
