Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-02, with the labels that each got.

#2117 Cameria's Averice Fix
  Data/Uniques/mace.lua
  Modules/ModParser.lua
Labels: bug

#2062 Adds Elevated affixes to item crafting
  Classes/Item.lua
Labels: bug

#2072 Warcry fixes for #1644, #1883, #2029, #2058.
  Data/Skills/act_str.lua
  Export/Skills/act_str.txt
  Modules/CalcPerform.lua
Labels: bug

#2073 Update Tailwind config tooltip with new 8% value
  Modules/ConfigOptions.lua
Labels: bug

#2074 Improved Information in Mods GGPK dumping
  Export/Scripts/mods.lua
Labels: documentation, enhancement

#2086 Update Replica Alberon's Warpath boot per 3.13 patch note
  Data/Uniques/boots.lua
Labels: bug

#2087 Fix Offering to the Serpent
  Data/Uniques/gloves.lua
Labels: bug

#2098 Fixes #2096 - Replace specific colon hack with a more generic solution
  Classes/Item.lua
Labels: enhancement

#2101 Updates Replica Nebulis to add a limit to the damage numbers
  Data/Uniques/mace.lua
  Modules/ModParser.lua
Labels: bug

#2113 Anomalous Quality Minion Life Support
  Data/Skills/sup_int.lua
  Export/Skills/sup_int.txt
Labels: bug

#2119 Belt Enchantments
  Data/EnchantmentBelt.lua
  Export/Scripts/enchant.lua
  Modules/Data.lua
  Modules/ModParser.lua
  manifest.xml
Labels: enhancement

#2122 Update Jack the Axe and add support for Thirst for Blood
  Data/Skills/other.lua
  Data/Uniques/axe.lua
  Export/Skills/other.txt
  Modules/ConfigOptions.lua
Labels: enhancement

#2105 Implemented Shield Shatter buff and skill
  Data/Skills/other.lua
  Export/Skills/other.txt
Labels: enhancement

#2116 Implement Specifier 'multiply_by_four'
  Export/statdesc.lua
  Modules/StatDescriber.lua
Labels: bug, enhancement

#2092 Make Skitterbots automatically Chill
  Modules/CalcPerform.lua
Labels: bug

#2079 Added support for Blizzard Crown implicits
  Modules/CalcBreakdown.lua
  Modules/ModParser.lua
Labels: enhancement

#2080 feat: add support for goblinedge
  Modules/ConfigOptions.lua
  Modules/ModParser.lua
Labels: enhancement

#2082 Scorched Ground Support
  Modules/CalcOffence.lua
  Modules/CalcPerform.lua
  Modules/CalcSections.lua
  Modules/ConfigOptions.lua
  Modules/ModParser.lua
Labels: enhancement

#1952 Dat64 GGPK Viewer
  Export/Classes/Dat64File.lua
  Export/Classes/GGPKData.lua
  Export/Main.lua
  Export/spec.lua
Labels: enhancement

#2129 feat: implement all missing uniques changes
  Data/Uniques/belt.lua
  Data/Uniques/jewel.lua
Labels: enhancement

#2160 Improve manifest updater
  update_manifest.py
Labels: enhancement

#2158 Fix Affliction Charges for Ailments
  Modules/CalcOffence.lua
Labels: bug

#2039 Ability to load a build from commandline.
  Modules/Main.lua
Labels: enhancement, long term

#2180 Divergent Purity of Lightning Fix
  Data/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#2175 Fixes Divergent Cobra Lash
  Data/SkillStatMap.lua
Labels: bug

#2171 Fixes #2159 - Pulled new charges out of config check so minimums stil…
  Modules/CalcPerform.lua
Labels: enhancement

#2169 Pure Talent was looking at the wrong starting node for marauder
  Modules/ModParser.lua
Labels: bug

#2168 Fix Ryslatha's Coil not applying to ailments
  Modules/ModParser.lua
Labels: bug

#2147 Enabling Phantasmal Summon Skeleton and archers for Vaal Summon Skeletons
  Data/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#2151 Added tree comparison
  Classes/PassiveTreeView.lua
  Classes/TreeTab.lua
Labels: enhancement

#2153 Made active minion counts generic, fixes Femurs of the Saints
  Data/Minions.lua
  Export/Minions/Minions.txt
  Modules/CalcPerform.lua
Labels: bug

#2177 Fix Attack Speed affecting Mine or Trap Supported attacks
  Modules/CalcOffence.lua
Labels: bug

#2179 Fix 'enemy is hexproof' Config Setting affecting marks
  Modules/CalcPerform.lua
Labels: bug

#2184 Supreme Ego now works with non-skill Auras
  Data/ModCache.lua
  Modules/CalcPerform.lua
  Modules/ModParser.lua
Labels: bug

#2191 Fixes #2190 - Several issues with Doppelganger Guise
  Data/Skills/other.lua
  Data/Uniques/body.lua
  Export/Skills/other.txt
  Modules/ModParser.lua
Labels: bug

#2195 Sum/More Clean-Up
  Modules/CalcDefence.lua
Labels: enhancement

#2205 Fix Inevitability
  Data/Uniques/jewel.lua
  Modules/ModParser.lua
Labels: bug

#2196 Fix Doedre's Skin
  Data/Skills/other.lua
  Export/Skills/other.txt
  Modules/ModParser.lua
Labels: bug

#2198 Shield Charge: support charge distance multiplier
  Data/SkillStatMap.lua
Labels: enhancement

#2201 FIX: Cospri's Malice wording
  Data/Uniques/sword.lua
Labels: bug

#2199 Fixes #2197 - Intimidate/Unnerve mods throwing error
  Classes/ItemsTab.lua
Labels: bug

#2174 Added group restrictions to crafted mods for crafted items
  Classes/ItemsTab.lua
Labels: enhancement

#2188 Fix for Shockwave secondary trigger rate
  Data/Skills/sup_str.lua
  Export/Skills/sup_str.txt
Labels: bug
