Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-05, with the labels that each got.

#2756 Fix: Mana Reservation mods
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/sword.lua
Labels: bug

#2732 Fix maces/sceptres and thrusting/non-thrusting swords counting as different weapon types
  src/Modules/CalcPerform.lua
Labels: bug

#2726 Add DPS for Choir/Voice of the Storm
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: enhancement

#2725 Fix Cerberus Limb implicit
  src/Data/Uniques/mace.lua
Labels: bug

#2710 Vortex's initial hit is now supported
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#2708 Fix Relic Uniques pasted into the Items page
  src/Classes/Item.lua
Labels: bug

#2690 Fix: changed armabrand radius to newest value
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#2676 Anomalous Zealotry Fix
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#2519 Fix variant bases ordering
  src/Classes/Item.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/sword.lua
Labels: bug

#2537 added support for pastebin alternative websites
  src/Classes/ImportTab.lua
Labels: enhancement

#2628 Interpret pastebin link varations from YouTube descriptions
  src/Classes/ImportTab.lua
Labels: enhancement

#2700 Fixes Maximum Stack logic to use "Effective DPS" mode and include debuffs
  src/Modules/CalcPerform.lua
Labels: bug

#2004 Unit testing PoC
  .busted
  .github/workflows/test.yml
  spec/System/TestAttacks_spec.lua
  spec/System/TestBuilds_spec.lua
  spec/TestBuilds/.gitignore
  src/Export/spec.lua
  src/HeadlessWrapper.lua
Labels: long term

#2788 Add support for Divergent Close Combat
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#2789 Fix Blood Stance not granting more Bleed damage
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug

#2790 Fix Wildwrap Attack Speed mod
  src/Data/Uniques/body.lua
Labels: bug

#2703 Fix The Coming Calamity forced reservation
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug

#2802 Bump SimpleGraphic to latest build
  runtime/SimpleGraphic.dll
Labels: enhancement

#2799 Add support for Rathpith Globe and legacy Femur of the Saints
  src/Classes/ModStore.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug

#2785 Fix power report crash when loading builds
  src/Classes/TreeTab.lua
Labels: bug

#2546 Add search field below principal buttons
  src/Modules/BuildList.lua
Labels: enhancement

#2795 Fix Triggered skill parsings
  src/Data/Uniques/bow.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
  src/Modules/ModParser.lua
Labels: bug

#2825 Fix The Agnostic calculation
  src/Modules/ModParser.lua
Labels: bug

#2820 Implement Replica Siegebreaker burning ground
  src/Data/ModCache.lua
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
  src/Modules/ModParser.lua
Labels: enhancement
