Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-11, with the labels that each got.

#3626 Fix build list loading crash
  src/Modules/BuildList.lua
Labels: bug, crash

#3638 Add Demon Harpy spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#3639 Add Pale Angel spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#3656 Add Demon Herder spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#3651 Fix Small Curse Cluster Jewels rendering on the tree when socketed
  src/Classes/Item.lua
Labels: bug

#3658 Add support for gem level modifiers of socketed active skill gems
  src/Modules/CalcTools.lua
Labels: enhancement

#3677 Fix attack/cast rate cap
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
Labels: bug

#3678 Fix Spell Suppression mastery giving double Crit chance
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug

#3679 Fix Impresence Mana Reservation mod not working
  src/Modules/ModParser.lua
Labels: bug

#3680 Fix parsing for Curse on Hit rings
  src/Modules/ModParser.lua
Labels: bug

#3684 Fix Multistrike not applying attack speed to certain skills
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug

#3685 Fix Multistrike not applying its damage multiplier to Ailments
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug

#3686 Add Pale Seraphim Spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#3687 Add Ravenous Mishapen Spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#3666 Fix Stationary Setting Box Sometimes Not Showing Up
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug

#3689 Fix Flame Totem consecrated ground enchant
  src/Modules/ModParser.lua
Labels: bug

#3691 Fix Voltaxic Burst's # of Casts currently waiting
  src/Modules/ConfigOptions.lua
Labels: bug

#3692 Fix parsing for mod on The Taming ring
  src/Modules/ModParser.lua
Labels: bug

#3693 Fix Mines counting towards # of Auras affecting you mastery
  src/Modules/CalcPerform.lua
Labels: bug

#3676 Add Autowidth to dropdown control, dropped text only
  .gitignore
  src/Classes/DropDownControl.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#3667 feat: support for two Armour Masteries
  spec/TestBuilds/3.13/Dual Savior.lua
  spec/TestBuilds/3.13/Dual Wield Cospris CoC.lua
  spec/TestBuilds/3.13/Generals Perforate Zerker.lua
  spec/TestBuilds/3.13/Mirage Archer Toxic Rain.lua
  spec/TestBuilds/3.13/OccVortex.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3697 add armour and evasion to unqiue sorting
  src/Modules/Data.lua
Labels: enhancement

#3700 Fix bleed damage against poisoned enemy mastery
  src/Modules/ModParser.lua
Labels: bug

#3707 update saqawals flock to 3.16
  src/Data/Uniques/helmet.lua
Labels: bug

#3710 Update wording for Darkness Enthroned
  src/Data/Uniques/belt.lua
  src/Modules/ModParser.lua
Labels: bug

#3714 Fix Two-Toned boots getting the wrong base type
  src/Classes/Item.lua
Labels: bug

#3715 Fix rounding on base percentiles
  src/Classes/Item.lua
Labels: bug

#3724 Poet's Pen total dps calc not working.
  src/Modules/CalcPerform.lua
Labels: bug

#3739 Fix new max res range for Brass Dome
  src/Data/Uniques/body.lua
Labels: bug

#3741 Various fixes for Beacon of Madness boots
  src/Data/Uniques/boots.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug

#3742 Add support for Champion's Inspirational banner life regen
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3744 Fix casing of Magebane keystone in data
  src/Modules/Data.lua
Labels: bug

#3769 fix: Increased Wither Effect does not affect minions
  src/Modules/CalcPerform.lua
Labels: bug

#3770 fix: Awakened Elemental Focus +1 level
  src/Data/SkillStatMap.lua
Labels: bug

#3775 fix: Enemy Physical Damage Reduction should be capped at 90%
  src/Modules/CalcOffence.lua
Labels: bug

#3766 fix: Fixes possible crash with FullDPS and disabled socket groups
  src/Modules/CalcPerform.lua
Labels: bug

#3696 fix: stacking Armour Masteries only taking largest value
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug

#3798 Fix Rage Support with Ancestral Totems
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug

#3800 Fix Phantasmal Sigil of Power spell damage buff not working
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#3801 Fix Elementalist exposure node not working with exposure mastery
  src/Modules/CalcPerform.lua
Labels: bug

#3802 Fix parsing for charges used mod on flasks
  src/Modules/ModParser.lua
Labels: bug

#3803 Add support for Master of Fear notable
  src/Modules/ModParser.lua
Labels: enhancement

#3799 Update Survival Jewels
  src/Data/Uniques/jewel.lua
  src/Modules/ModParser.lua
Labels: bug
