Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-04, with the labels that each got.

#2294 PR: Triggers & FullDPS
  Classes/CalcsTab.lua
  Classes/GemSelectControl.lua
  Classes/Item.lua
  Classes/ItemDBControl.lua
  Classes/ItemsTab.lua
  Classes/NotableDBControl.lua
  Classes/PassiveTreeView.lua
  Classes/SkillsTab.lua
  Classes/TreeTab.lua
  Data/Global.lua
  Data/SkillStatMap.lua
  Data/Skills/other.lua
  Data/Skills/sup_dex.lua
  Data/Skills/sup_int.lua
  Data/Uniques/belt.lua
  Data/Uniques/helmet.lua
  Export/Skills/other.txt
  Export/Skills/sup_dex.txt
  Export/Skills/sup_int.txt
  Modules/Build.lua
  Modules/CalcActiveSkill.lua
  Modules/CalcOffence.lua
  Modules/CalcPerform.lua
  Modules/CalcSections.lua
  Modules/CalcSetup.lua
  Modules/Calcs.lua
  Modules/Common.lua
  Modules/ConfigOptions.lua
  Modules/Data.lua
  Modules/ModParser.lua
  Modules/Profiler.lua
Labels: enhancement

#2359 Profiling
  Classes/GemSelectControl.lua
  Modules/Common.lua
  Modules/Profiler.lua
Labels: enhancement

#2381 Handle Cluster Generation based on New Import Format
  Classes/ImportTab.lua
  Classes/ItemsTab.lua
  Classes/PassiveSpec.lua
Labels: enhancement

#2340 Made inspiration charges default to maximum
  Modules/CalcPerform.lua
  Modules/Calcs.lua
  Modules/ConfigOptions.lua
Labels: enhancement

#2376 Removing garbage collection calls to improve memory
  Classes/CalcsTab.lua
Labels: enhancement

#2395 Lazy Passive Tree Loading
  src/Classes/PassiveSpec.lua
  src/Modules/Main.lua
Labels: enhancement

#2392 Add mana reservation breakdown
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#2387 Fixes #2384 - Right click to paste
  src/Classes/EditControl.lua
Labels: enhancement

#2386 Fix brand attachment limit for several skills
  src/Modules/CalcPerform.lua
Labels: bug

#2304 Add support for Precursor's Emblem
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Generated.lua
Labels: enhancement

#2305 Automatically generate Watcher's Eye
  src/Data/Generated.lua
  src/Data/Uniques/Special/WatchersEye.lua
  src/Export/Scripts/mods.lua
  src/Export/statdesc.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#2399 refactor: vendor lua-profiler correctly
  LICENSE.md
  runtime/lua/lua-profiler.lua
  src/Modules/Common.lua
Labels: documentation

#2250 Moving power report to a drawer and adding additional features
  src/Classes/CalcsTab.lua
  src/Classes/PassiveTreeView.lua
  src/Classes/PowerReportListControl.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#2426 Fix General's Cry and Same Gems Crashes
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: bug

#2430 Fix ability to tab between inputs on the skills tab
  src/Classes/SkillsTab.lua
Labels: bug

#2428 Fixes stat comparison between tree specs
  src/Modules/Calcs.lua
Labels: bug

#2498 Fix DD and VD having their spell damage apply to corpse explosions
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug

#2391 Fix incorrect application of Buff Effect
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
Labels: bug, help wanted

#2481 Fix physical damage reduction for bleed from going below zero
  src/Modules/CalcOffence.lua
Labels: bug

#2474 Fix outdated modifier text on Aberrath's Hooves
  src/Data/Uniques/boots.lua
Labels: bug

#2463 Update Low Life/Mana threshold
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
Labels: enhancement

#2461 Add new Ultimatum uniques, implemented Tecrod's Gaze
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#2496 Add support for count-scaling Active Skills from items
  src/Classes/SkillsTab.lua
  src/Modules/Calcs.lua
Labels: enhancement

#2450 Fix TriggerByBrand interaction with Item-granted Active Skill
  src/Modules/CalcPerform.lua
Labels: bug, crash

#2442 Fix "Socketed Gems are supported by..." mods for trigger skills (e.g. CwC)
  src/Modules/ModParser.lua
Labels: bug

#2493 Adding noGem directive to skills from items
  src/Data/Gems.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug

#2471 Add support for Accelerating, Noxious, and Unstable catalysts
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/ring.lua
Labels: enhancement

#2472 Adding more flags for parsing enemy modifiers
  src/Modules/ModParser.lua
Labels: enhancement

#2513 3.14 Skill Tree
  manifest.xml
  src/GameVersions.lua
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
  src/TreeData/3_14/groups-3.png
  src/TreeData/3_14/skills-3.jpg
  src/TreeData/3_14/skills-disabled-3.jpg
  src/TreeData/3_14/tree.lua
Labels: enhancement

#2453 Generals Cry crash fixes
  src/Classes/GemSelectControl.lua
  src/Classes/PassiveTreeView.lua
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: bug, crash

#2528 Fixes Minion Full DPS crash; Fixes Item Full DPS stat compare
  src/Classes/GemSelectControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/SkillsTab.lua
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: bug, crash

#2460 General's cry: ignore speed for non-channeled skills
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
Labels: bug

#2542 Fix Trap and Mines to use Throwing/Laying Speed for DPS calcs
  src/Modules/CalcOffence.lua
Labels: bug

#2545 Fix Physical Aegis checkbox getting mixed with Innervate
  src/Modules/ConfigOptions.lua
Labels: bug

#2539 Fixes Mirage Archer applying DoT stacks when they shouldn't
  src/Modules/CalcOffence.lua
  src/Modules/Calcs.lua
Labels: bug

#2544 Fix non-integer catalyst scaling issues
  src/Classes/ItemsTab.lua
  src/Modules/ItemTools.lua
Labels: bug

#2547 Add support for Glimpse of Chaos
  src/Modules/ModParser.lua
Labels: enhancement

#2577 Fix Blood Magic
  src/Data/SkillStatMap.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug

#2574 Fix fake minion skill costs
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug

#2575 Add support for Chainbreaker rage cost
  src/Modules/Build.lua
  src/Modules/ModParser.lua
Labels: enhancement

#2579 Fix Exsanguinate and Corrupting Fever stack damage
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#2580 Fix skill tags
  src/Data/Global.lua
  src/Export/Scripts/skills.lua
Labels: bug

#2603 Updating item parser to handle new copy/paste format
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
Labels: bug

#2596 Add parsing for new damage mods
  src/Modules/ModParser.lua
Labels: bug

#2587 Split reservation mod into mana and life reservation mods
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#2586 Fix Prism Guardian
  src/Data/Skills/other.lua
  src/Data/Uniques/shield.lua
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: bug

#2615 Add new bases and clean up base matching
  src/Data/Bases/amulet.lua
  src/Data/Bases/boots.lua
  src/Data/Bases/gloves.lua
  src/Data/Bases/quiver.lua
  src/Data/Bases/ring.lua
  src/Export/Bases/amulet.txt
  src/Export/Bases/belt.txt
  src/Export/Bases/boots.txt
  src/Export/Bases/gloves.txt
  src/Export/Bases/quiver.txt
  src/Export/Bases/ring.txt
Labels: enhancement

#2497 Fixes #2494 - short circuits out of search function if the lua pattern is invalid
  src/Classes/PassiveTreeView.lua
  src/Classes/TreeTab.lua
Labels: bug

#2583 Updated Uniques
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/other.txt
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
  src/Modules/ModParser.lua
Labels: enhancement

#2621 Fix Exsanguinate stacks applying to all DoTs
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#2622 Fix Mine aura effect applying to DoTs from mines
  src/Modules/CalcOffence.lua
Labels: bug

#2630 Add parsing for many new mods
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement

#2644 Update reservation rounding
  src/Modules/CalcPerform.lua
Labels: bug

#2645 Fix scaling for Vaal Righteous Fire
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#2456 Simulation Trigger Enhancements
  src/Modules/CalcPerform.lua
Labels: enhancement

#2443 Implement Portrait Mode
  src/Classes/CalcsTab.lua
  src/Classes/ItemsTab.lua
  src/Classes/PowerReportListControl.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/Main.lua
Labels: enhancement
