Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-08, with the labels that each got.

#3053 Fix error when Main Skill is not-minion but Minion is in FullDPS
  src/Modules/Build.lua
Labels: bug

#3031 Describe installer creation process
  RELEASE.md
Labels: documentation

#2903 Add full support for Close Combat
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_str.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/sup_dex.txt
  src/Export/spec.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#3112 Fix Combat Jewel parsing
  src/Data/Uniques/jewel.lua
  src/Modules/ModParser.lua
Labels: bug

#3113 Add support for new base type implicits
  src/Modules/ModParser.lua
Labels: enhancement

#3117 Update slipstream tooltip
  src/Modules/ConfigOptions.lua
Labels: bug

#3127 Fix Unleash crash with minion skills
  src/Modules/CalcOffence.lua
Labels: bug, crash

#3122 Fix exporter for explosive concoction
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Scripts/statdesc.lua
Labels: bug

#3116 Update images for socketed Cluster Jewels
  src/Classes/PassiveTreeView.lua
  src/TreeData/JewelSocketActiveAltBlue.png
  src/TreeData/JewelSocketActiveAltPurple.png
  src/TreeData/JewelSocketActiveAltRed.png
Labels: enhancement

#3177 Add radius numbers for a number of skills
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_int.txt
Labels: enhancement

#3167 Fix gem levels not being properly limited
  src/Modules/CalcSetup.lua
  src/Modules/CalcTools.lua
Labels: bug, enhancement

#3160 Fix Bane not gaining duration per curse applied
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#3148 Fix exposure not applying from Corrosive Elements notable
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug
