Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-03, with the labels that each got.

#2235 FIX: Removed Attack flag from dotCfg
  Modules/CalcOffence.lua
Labels: bug

#2241 Fix alternate quality Purifying Flame, Hypothermia, Phys to Lightning debuffs
  Data/SkillStatMap.lua
  Data/Skills/sup_dex.lua
  Data/Skills/sup_int.lua
  Export/Skills/sup_dex.txt
  Export/Skills/sup_int.txt
Labels: bug

#2242 Fix Accuracy per quality should be global
  Modules/ModParser.lua
Labels: bug

#2243 Add support for importing from Garena and Tencent realms
  Classes/ImportTab.lua
Labels: enhancement

#2244 Best Guess at numerous skillTypes
  Data/Global.lua
  Data/Skills/act_dex.lua
  Data/Skills/act_int.lua
  Data/Skills/act_str.lua
  Data/Skills/glove.lua
  Data/Skills/other.lua
  Data/Skills/spectre.lua
  Data/Skills/sup_dex.lua
  Data/Skills/sup_int.lua
  Data/Skills/sup_str.lua
  Export/Scripts/skills.lua
  Modules/CalcPerform.lua
Labels: enhancement

#2261 Fix: Oos activation frequency with more multipliers to cast speed
  Data/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#2266 Add generic mod parsing for enemy modifiers
  Modules/ModParser.lua
Labels: enhancement

#2268 Escape file names in URLs the updater visits
  UpdateCheck.lua
Labels: enhancement

#2279 Fix Hydrosphere damage conversion
  Data/Skills/act_int.lua
  Export/Skills/act_int.txt
Labels: bug

#2288 Fix eHP Calculation for Glancing Blows + new Block boots
  Modules/CalcDefence.lua
  Modules/ModParser.lua
Labels: bug

#2219 Divergent Pride Fix
  Data/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#2225 Support "enemies taunted by your warcries take x% increased damage"
  Modules/ModParser.lua
Labels: enhancement

#2227 Update contributing
  CONTRIBUTING.md
Labels: documentation

#2231 Doryani's Prototype: fix typo
  Modules/ModParser.lua
Labels: bug

#2237 Fix Anamalous flesh and stone applying twice with Iron Reflexes
  Data/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#2249 Fix: Added area baseflag to Chain-Hook
  Data/Skills/act_str.lua
  Export/Skills/act_str.txt
Labels: bug

#2265 Fix missing source for affliction charges causing error
  Modules/CalcOffence.lua
Labels: bug

#2298 Fix - 0 being used as a default gem level causes a crash
  Classes/SkillsTab.lua
Labels: bug

#2299 Fix crash when loading old build with new cluster jewel notable added in a later patch
  Classes/PassiveSpec.lua
Labels: crash

#2200 Cast on Death implementation
  Data/Skills/sup_dex.lua
  Export/Skills/sup_dex.txt
  Modules/CalcOffence.lua
  Modules/CalcPerform.lua
Labels: enhancement

#2303 Add support for culling
  Classes/ModStore.lua
  Data/SkillStatMap.lua
  Modules/CalcOffence.lua
  Modules/CalcSections.lua
  Modules/ModParser.lua
Labels: enhancement

#2297 Fixes Cast Rate for Self-Cast Skills that have Cooldown & Display DPS
  Data/SkillStatMap.lua
  Modules/CalcOffence.lua
Labels: bug

#2313 Add Culling DPS left-hand-side Display if build includes culling
  Modules/Build.lua
  Modules/CalcOffence.lua
Labels: enhancement

#2324 Updated ServerTickRate; Added ServerTickTime
  Modules/Data.lua
Labels: bug, enhancement

#2326 Add support for Actum crit modifier
  Modules/CalcOffence.lua
  Modules/ModParser.lua
Labels: enhancement

#2329 Use thousands separator preference in damage header
  Modules/CalcOffence.lua
Labels: enhancement

#2330 Fix Divergent Ensnaring Arrow
  Data/Skills/act_dex.lua
  Export/Skills/act_dex.txt
Labels: bug

#2331 Fix Voidshot Parsing
  Modules/ModParser.lua
Labels: bug

#2332 Add more support for intimidate/unnerve
  Modules/CalcSetup.lua
  Modules/ConfigOptions.lua
  Modules/ModParser.lua
Labels: bug

#2333 Add admiral lowest resist
  Modules/CalcBreakdown.lua
  Modules/CalcOffence.lua
  Modules/ModParser.lua
Labels: enhancement

#2334 Add support for Blunderbore's shrine effects
  Modules/CalcPerform.lua
  Modules/ModParser.lua
Labels: enhancement

#2337 Fix wording on Poet's Pen
  Data/Skills/other.lua
  Data/Uniques/wand.lua
  Export/Skills/other.txt
Labels: bug

#2336 Add support for Doryani's Prototype lightning resist equal to yours
  Modules/CalcOffence.lua
  Modules/ModParser.lua
Labels: enhancement

#2310 Add support for The Dark Seer's Malediction debuff
  Modules/CalcPerform.lua
  Modules/ModParser.lua
Labels: enhancement

#2370 Add enchants and fix enchanting UI
  Classes/ItemsTab.lua
  Modules/ModParser.lua
Labels: bug

#2363 Fix flask effect incorrect in certain situations
  Classes/ModStore.lua
Labels: bug

#2358 Fix: changed divergent nightblade from base crit to inc crit%
  Data/SkillStatMap.lua
Labels: bug

#2352 Add support for Flickershade spectre chaos damage conversion
  Data/Spectres.lua
  Export/Minions/modmap.ini
Labels: bug

#2347 Fix Fanaticism should not apply to attacks
  Modules/CalcPerform.lua
Labels: bug

#2335 Add handling for Doedre's Skin ignore curse limit mod
  Modules/CalcPerform.lua
  Modules/ModParser.lua
Labels: enhancement
