Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2021-07, with the labels that each got.

#2215 Adding viridi's veil hexproof mod
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#2445 Implement a beta testing branch and weekly merge from dev
  .github/workflows/beta.yml
  .github/workflows/release.yml
  src/Modules/Main.lua
Labels: enhancement

#2646 Tooltip changes for newbies
  src/Modules/Build.lua
Labels: enhancement

#2791 Update SHA-1 library
  .busted
  LICENSE.md
  manifest.xml
  runtime/lua/sha1.lua
  runtime/lua/sha1/bit32_ops.lua
  runtime/lua/sha1/bit_ops.lua
  runtime/lua/sha1/common.lua
  runtime/lua/sha1/init.lua
  runtime/lua/sha1/lua53_ops.lua
  runtime/lua/sha1/pure_lua_ops.lua
Labels: documentation, enhancement

#2800 20 Quality gem DPS tooltip comparison (aka. Is GCP vendor recipe worth doing?)
  src/Classes/SkillsTab.lua
Labels: enhancement

#2882 Add unique variant of Commandment of Inferno
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: bug

#2883 Fix Interation between Agnostic and Pious Path
  src/Modules/CalcDefence.lua
Labels: bug

#2796 Update gem tooltip generation
  src/Classes/GemSelectControl.lua
  src/Data/Costs.lua
  src/Export/Scripts/costs.lua
  src/Modules/Common.lua
Labels: bug

#2806 Fix support for Petrified Blood
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
Labels: bug

#2835 CONTRIBUTING overhaul
  CONTRIBUTING.md
Labels: documentation

#2873 Add unique helmet The Fledgling
  src/Data/Uniques/helmet.lua
Labels: enhancement

#2889 Fix Anomalous Chain Hook
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#2901 Add weapon crit to mod breakdown and fix a typo
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#2904 Remove Blood Offering gem
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug

#2905 Added Parsing for 'Perfect Crime' and 'Bomb Specialist'
  src/Modules/ModParser.lua
Labels: enhancement

#2910 Add 3.15 passive skill tree
  RELEASE.md
  fix_ascendancy_positions.py
  src/Classes/PassiveTree.lua
  src/GameVersions.lua
  src/TreeData/3_15/groups-3.png
  src/TreeData/3_15/skills-3.jpg
  src/TreeData/3_15/skills-disabled-3.jpg
  src/TreeData/3_15/tree.lua
Labels: documentation, enhancement

#2874 Fix parsing for Sacrificial Garb implicit
  src/Modules/ModParser.lua
  src/Modules/ModTools.lua
Labels: bug

#2898 Various gem fixes and improvements
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Modules/CalcOffence.lua
Labels: bug, enhancement

#2955 Fix triggered skills not showing the right mana cost
  src/Modules/CalcOffence.lua
Labels: bug

#2989 Fix Mana Reservation Rounding
  src/Modules/CalcPerform.lua
Labels: bug

#2983 Fix skills turned into mines not having reservation
  src/Data/SkillStatMap.lua
  src/Modules/CalcPerform.lua
Labels: bug

#2933 Fix Hexproof to be unaffected by curses, not immune
  src/Modules/ModParser.lua
Labels: bug

#2932 Fix level progress calculations
  src/Modules/Build.lua
Labels: bug

#2981 Fix for downloading tree data if missing
  src/Classes/PassiveTree.lua
Labels: bug

#2999 Update new gems
  src/Classes/ModStore.lua
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/minion_spell_damage_skill_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Minions/Minions.txt
  src/Export/Scripts/statdesc.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
  src/Export/Skills/spectre.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
  src/Modules/StatDescriber.lua
Labels: enhancement

#3007 Add issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: enhancement

#3019 Prevent build code from being interpreted as markdown
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#3016 Fix Voltaxic Burst enchant
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#3037 Sanitize default gem properties when loading a build
  src/Classes/SkillsTab.lua
Labels: bug

#3047 Update Oskarm's chaos resist
  src/Data/Uniques/gloves.lua
Labels: bug

#3049 Update Ailment threshold values
  src/Modules/ConfigOptions.lua
Labels: bug
