Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-05, with the labels that each got.

#4308 Refactor ascendancy fixer
  RELEASE.md
  fix_ascendancy_positions.py
  tests/test_fix_ascendancy_positions.py
Labels: technical

#4288 Add support for reduced mana cost of attacks
  src/Modules/ModParser.lua
Labels: new-calculations

#4329 Add support for ReservationBecomesCost modifier (Divine Blessing/Totems)
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
Labels: enhancement, new-calculations

#4348 Feat: Add support for Massive Radius
  src/Data/Uniques/jewel.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: new-calculations

#4342 Remove ward regen from breakdown
  src/Modules/CalcSections.lua
Labels: user-interface

#4338 Add support for Spellslinger reservation enchant
  src/Modules/ModParser.lua
Labels: new-calculations

#4337 Add support for "for Attack Damage" modifiers
  src/Modules/ModParser.lua
Labels: new-calculations

#4330 Fix Energy Blade Import
  src/Classes/ImportTab.lua
Labels: bug

#4326 Fix Decay breakdown
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug

#4325 Update Vulnerability curse priority
  src/Modules/Data.lua
Labels: bug

#4358 Fix: planning for new unique Forbidden Flame/Flesh Scion notable
  src/Classes/PassiveTree.lua
Labels: enhancement, new-calculations

#4369 New: export of skills; added two new DATs to be pulled; added new skills
  src/Data/Bases/quiver.lua
  src/Data/ClusterJewels.lua
  src/Data/Gems.lua
  src/Data/Minions.lua
  src/Data/ModFlask.lua
  src/Data/ModItem.lua
  src/Data/ModJewel.lua
  src/Data/ModJewelAbyss.lua
  src/Data/ModJewelCluster.lua
  src/Data/ModMaster.lua
  src/Data/ModVeiled.lua
  src/Data/Pantheons.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/buff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Data/Uniques/Special/WatchersEye.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/bases.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Export/spec.lua
Labels: enhancement

#4364 Eldritch Mod Parsing
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: new-calculations

#4367 Clarify build code section in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation, technical

#4365 Sentinel uniques
  src/Classes/ItemsTab.lua
  src/Data/Global.lua
  src/Data/Skills/sup_int.lua
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/New.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
  src/Modules/ItemTools.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement, new-calculations

#4306 Unify Max Stages to not use StagesAfterFirst anymore
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug, technical

#4293 Fix supreme ego more mana reservation of skills to only affect auras
  src/Modules/ModParser.lua
Labels: bug

#4331 Add keyboard shortcut for Notes section "Ctrl+6"
  src/Modules/Build.lua
Labels: user-interface

#4355 Add zoom support by using shift + mouse
  src/Classes/EditControl.lua
  src/Classes/NotesTab.lua
Labels: enhancement, user-interface

#4379 Show Boss 'less curse effect' in resistance breakdown
  src/Modules/CalcSections.lua
Labels: user-interface

#4373 Add mouse shortcuts to skills tab
  src/Classes/ListControl.lua
  src/Classes/SkillListControl.lua
  src/Classes/SkillsTab.lua
Labels: user-interface

#4396 Fix Exposure mastery stacking incorrectly
  src/Modules/CalcPerform.lua
Labels: accuracy

#4395 Adds support for exposure from Eldritch implicits and Archdemon Crown
  src/Modules/ModParser.lua
Labels: new-calculations

#4394 Fix Arrogance Support not working with blasphemy curses
  src/Data/SkillStatMap.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug

#4404 Fix Massive Thread of Hope outer radius
  src/Modules/Data.lua
Labels: bug
