Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-01, with the labels that each got.

#3860 Add missing Bone Offering quality effect
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#3851 Fix Projectile Attack Mod Parsing
  src/Modules/ModParser.lua
Labels: bug

#3844 Fix nearby enemy modifiers merging with resistance modifiers
  src/Data/ModItem.lua
  src/Export/Scripts/mods.lua
Labels: technical

#3818 Add QoL improvements for import tab
  src/Classes/ImportTab.lua
Labels: enhancement

#3808 Fix Summon Raging Spirit to 100% fire conversion
  src/Data/Minions.lua
  src/Export/Minions/Minions.txt
Labels: bug

#3543 Add support for "Arrows gain Critical Strike Chance as they travel farther, up to 100% increased Critical Strike Chance" and "Arrows gain Damage as they travel farther, up to 50% increased Damage with Hits to targets"
  src/Modules/ModParser.lua
Labels: enhancement

#3848 Cluster jewel corruptions
  src/Classes/Item.lua
  src/Data/ModJewelCluster.lua
  src/Export/Scripts/mods.lua
Labels: enhancement

#3813 Ctrl I for import
  src/Modules/Build.lua
Labels: enhancement

#3852 Update SkillTypes to Actuals
  src/Data/Global.lua
  src/Data/Misc.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/spec.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: technical

#3776 fix: Add support for 'inflicted with this weapon' parsing
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement

#3859 feat: Enable stages for multi-part skills at a per-part level
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/Build.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3868 Fix: Viper Strike Poison Stacks with Dual Wield
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: bug, enhancement

#3871 Correct stat on Brass Dome
  src/Data/Uniques/body.lua
Labels: bug

#3832 fix: Fix trigger rate of hard-overridden skills
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
Labels: bug

#3869 fix: removed a StatMap entry that doesn't exist anymore
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: bug, technical

#3760 Update GGPK spec
  src/Export/Classes/Dat64File.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Main.lua
  src/Export/spec.lua
Labels: technical

#3827 Showing stat difference on anointed nodes
  src/Classes/PassiveTreeView.lua
  src/Modules/CalcSetup.lua
Labels: bug, enhancement

#3663 Add support for ongoing costs
  src/Classes/GemSelectControl.lua
  src/Data/Costs.lua
  src/Export/Scripts/costs.lua
  src/Export/spec.lua
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/Common.lua
  src/Modules/Data.lua
Labels: bug, enhancement

#3335 Add support for new mod conversion modifiers
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
  src/Modules/ModParser.lua
  src/Modules/ModTools.lua
Labels: enhancement

#3840 Add Mastery tooltip for an unallocated node when comparing trees
  src/Classes/PassiveTreeView.lua
Labels: bug, enhancement

#3879 fix: moved Scourge uniques still in New.lua to where they belong
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/gloves.lua
Labels: bug, technical

#3875 Add Special Case modifier for Pure Talent jewel and Marauder
  src/Modules/ModParser.lua
Labels: bug

#3876 Add hotkey to edit equipped item
  src/Classes/ItemsTab.lua
Labels: enhancement

#3864 Round Duration of skills to server ticks
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#3865 Change skill cooldown to display in milliseconds
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug

#3723 Refactor rendering of tree node connectors
  src/Classes/PassiveTreeView.lua
Labels: technical

#3213 Move delve mods to "Add modifier..." menu while crafting items
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
Labels: enhancement

#3526 Clean up ModParser
  docs/modSyntax.md
  src/Modules/ModParser.lua
Labels: technical

#3814 fix: Fix Elusive Buff effect from Skills with Withering Step
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcPerform.lua
Labels: bug

#3889 fix: implemented better raw string item parsing
  src/Classes/Item.lua
Labels: bug

#3580 Add support for Energy Blade
  src/Classes/ImportTab.lua
  src/Data/Bases/sword.lua
  src/Data/Skills/act_int.lua
  src/Export/Bases/sword.txt
  src/Export/Scripts/bases.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#3891 Fixed copying magic Two-Toned Boots from trade
  src/Classes/Item.lua
Labels: bug

#3899 Add feature to guess the main socket group when importing a character
  src/Classes/ImportTab.lua
Labels: enhancement

#3919 Add "Cursed Enemies are Hindered" Mastery
  src/Modules/ModParser.lua
Labels: enhancement

#3874 Add starter race uniques
  src/Data/Uniques/Special/race.lua
  src/Modules/Data.lua
Labels: enhancement

#3883 Add support for Mageblood
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement

#3557 Use docker for testing
  .gitignore
  CONTRIBUTING.md
  docker-compose.yml
Labels: technical

#3894 Fix issue where culling DPS wasn't factored in for Full DPS totals
  src/Modules/Calcs.lua
Labels: bug

#3896 Add full support for brand attachment range
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
Labels: enhancement

#3905 Fix triggering skill not properly selected when trigger support came from an item
  src/Modules/CalcPerform.lua
Labels: bug

#3906 Add Lifetap's "20% increased Life Recovery from Flasks" modifier
  src/Modules/ConfigOptions.lua
Labels: enhancement

#3907 Add ability to show DPS for non-cooldown traps and mines
  src/Modules/CalcOffence.lua
Labels: enhancement

#3934 Fix broken link
  README.md
Labels: bug, documentation

#3908 Fix bug where maximum Life could be negative
  src/Modules/CalcPerform.lua
Labels: bug

#3902 fix: remove duplicate and not pertinent values being saved in XML
  src/Modules/Build.lua
Labels: technical

#3909 Fix incorrect reservation on some legacy builds
  src/Modules/CalcPerform.lua
Labels: bug

#3910 Add support for Anomalous Vitality
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#3911 Fix Sidhebreath missing implicit
  src/Data/Uniques/amulet.lua
Labels: bug

#3916 Update Blightwell and Solstice Vigil to 3.16.0
  src/Data/Uniques/amulet.lua
Labels: enhancement

#3918 Add missing Fate/Story of the Vaal modifiers
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3913 Fix elemental damage taken when using The Admiral
  src/Modules/CalcOffence.lua
Labels: bug

#3917 Add feature to match gem level to character level
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
Labels: enhancement

#3912 Fix converted passive tree save error
  src/Classes/PassiveSpec.lua
Labels: bug

#3925 Fix Soul of Solaris not displaying "Nearby Enemies" config option
  src/Modules/ModParser.lua
Labels: bug

#3897 Add improvements to multiple passive tree jewel socket management
  src/Classes/ItemListControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveSpecListControl.lua
  src/Classes/TreeTab.lua
Labels: bug, enhancement

#3914 Fix various item parsing bugs
  src/Classes/Item.lua
  src/Data/Uniques/boots.lua
Labels: bug

#3926 Add separate calculations for Elemental Hit area component
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#3921 Add ability to search skills using multiple tags
  src/Classes/GemSelectControl.lua
  src/Modules/Common.lua
Labels: enhancement

#3923 Add Melding of the Flesh
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3945 fix: fix magic name being copied on flaks into affixes
  src/Classes/Item.lua
Labels: bug, technical

#3763 Add support for Willowgift
  spec/TestBuilds/3.13/Generals Perforate Zerker.lua
  spec/TestBuilds/3.13/Generals Perforate Zerker.xml
  spec/TestBuilds/3.13/OccVortex.lua
  spec/TestBuilds/3.13/OccVortex.xml
  src/Data/Uniques/amulet.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug

#3946 feat: add support for Triple Elemental Damage
  src/Classes/ModStore.lua
  src/Data/Uniques/Special/New.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3952 Fix infinite reservation error with Relic of the Pact
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug, crash

#3125 Fix Charged Dash DPS
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: bug, enhancement

#3977 Reworked release note script to use GitHub release note generation
  .github/release.yml
  .github/workflows/release.yml
Labels: technical

#3960 Fix skills from items getting +1 level from Awakened gems
  spec/System/TestSkills_spec.lua
  src/Classes/SkillsTab.lua
  src/Modules/CalcActiveSkill.lua
Labels: bug

#3954 fix: when doing gem recommendations this can cause a crash
  src/Modules/Calcs.lua
Labels: crash

#3938 Fix: Power Report generating error pop-up
  src/Classes/CalcsTab.lua
  src/Classes/TreeTab.lua
Labels: bug, crash

#3953 Check clampFactor for an edge case causing PoB to crash
  src/Classes/PassiveTreeView.lua
Labels: crash

#3962 Fix Passive Tree Management Titles
  src/Classes/PassiveSpecListControl.lua
Labels: enhancement

#3987 On Kill wording fix
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/sword.lua
Labels: bug

#3986 Update Chaos Resistance roll on unique rings
  src/Data/Uniques/ring.lua
Labels: bug

#3990 Update Crimson Storm changes
  src/Data/Uniques/bow.lua
Labels: enhancement

#4001 feat: added Polaric Devastation ring and mod support
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3956 Add partial support for Fleshcrafter
  src/Modules/ModParser.lua
Labels: enhancement

#3950 Remove trailing and leading spaces from the import character name
  src/Classes/ImportTab.lua
Labels: bug

#3948 fix: remove non-existing stat-map entry
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: technical

#3904 Transcendent Flesh rounding not matching in game
  src/Modules/ModParser.lua
Labels: bug

#3935 Get maximum animated weapon from gem level instead of configuration
  src/Data/Skills/act_dex.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/other.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#3928 Updated Kingmaker, fixed Fortify mods to use "Fortified" condition
  src/Data/Uniques/axe.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3884 Remove Dummy skill mods
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/spectre.txt
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: technical

#4005 fix: update ignite value from 125% to 90% for 28% nerf in 3.17
  src/Modules/Data.lua
Labels: enhancement

#4004 feat: Add support for new Precision Technique Keystone
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3930 Fix incorrect curse priority
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
Labels: bug

#3980 Beta branch auto-update fix
  .github/workflows/beta.yml
Labels: technical

#3893 Max mods not using proper default
  src/Classes/ModStore.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug

#4002 feat: add support for Adder's Touch modifier
  src/Modules/ModParser.lua
Labels: enhancement
