Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-02, with the labels that each got.

#4015 fix: Whispering Ice & Trigger Conditions
  src/Data/Skills/other.lua
  src/Modules/CalcPerform.lua
Labels: bug, enhancement

#3947 Add global modifier limit support
  src/Classes/ModDB.lua
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3976 Add support for new wording on War Bringer
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4006 Fix 'defend with % armour' mastery to not effect total armour value
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug

#3931 Delete jewels, skills, and equipment by default
  src/Classes/CheckBoxControl.lua
  src/Classes/ImportTab.lua
  src/Classes/SkillsTab.lua
Labels: enhancement

#4032 Cap Explosive Arrow Bonus Explosion Radius
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug

#4030 Fix Vaal BV hit rate override being too high
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug

#4031 fix: redo how useFullDPS is calculated
  src/Classes/ItemsTab.lua
  src/Classes/SkillsTab.lua
  src/Data/Global.lua
  src/Modules/Calcs.lua
Labels: bug

#4013 Fix several minor bugs in the exporter UI
  src/Export/Classes/GGPKSourceListControl.lua
  src/Export/Main.lua
Labels: technical

#3637 Delete modmap ini for minion mods
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Spectres.lua
  src/Export/Minions/Minions.txt
  src/Export/Minions/modmap.ini
  src/Export/Scripts/minions.lua
Labels: enhancement, technical

#3949 Add 'Delete Unused' button on the items tab
  src/Classes/ItemListControl.lua
Labels: enhancement

#3958 Add support for additional life recovery flask mods
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3982 fix: un-krangle cluster jewel orbit calculations
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTree.lua
Labels: bug, technical

#3271 Refactor non-damaging elemental ailments
  src/Data/Global.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4017 Add build code export to pobb.in
  CONTRIBUTING.md
  src/Classes/ImportTab.lua
Labels: enhancement

#3294 Add config options for self-chill builds
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug

#4008 Additional curse priority fixes
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
Labels: bug

#4029 Fix: SkillPart Stage DropDown
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/other.txt
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
Labels: bug

#4018 feat: Put FullDPS breakdown into XML Build Save file
  src/Modules/Build.lua
Labels: enhancement

#4041 Improve bulk item deletion performance
  src/Classes/ItemListControl.lua
  src/Classes/ItemsTab.lua
Labels: technical

#4037 Fix missing physical damage reduction caps
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
Labels: bug

#4012 Add more explanation to non-damaging ailment breakdown
  src/Classes/CalcBreakdownControl.lua
  src/Modules/CalcOffence.lua
Labels: enhancement

#3992 Feat: Add Support for Claw Mastery modifier
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4047 Fix: correct two modifiers on Survivor's Guilt (unique belt)
  src/Data/Uniques/belt.lua
Labels: bug

#3974 Siege Unique Changes
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4049 Swap ailment threshold and effect in breakdown
  src/Modules/CalcOffence.lua
Labels: enhancement

#3975 Add support for Forbidden Flesh and Flame
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTree.lua
  src/Data/Uniques/Special/Generated.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3937 [Siege] add support for omniscience and it's unique
  src/Data/Uniques/Special/New.lua
  src/Modules/Build.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#3927 Updated Bleed/Ignite Ailment calculation to use weighted average
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#4055 Parse new "for spell damage" mod
  src/Modules/ModParser.lua
Labels: enhancement

#2390 Implement Effective HP and refactor defence calculations to be more accurate
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement, wip

#4039 Add support for Atziri's Rule
  src/Classes/PassiveTreeView.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement

#3932 Add support for several different spectres: Arena Master, Ruins Hellion (partial), Trial Windchaser, Aurid Synthete, Ancient Wraith, They of Tul, Ancient Suffering, Merveil's Retainer, Primal Crushclaw, and Primal Rhex Matriarch
  src/Classes/ConfigTab.lua
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Scripts/minions.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/spectre.txt
  src/Modules/Build.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4057 Fix unused Abyss Jewel deletion
  src/Classes/ItemListControl.lua
Labels: bug

#3985 Add support for several veiled uniques: Paradoxica, Replica Paradoxica, Cane of Kulemak, and The Queen's Hunger
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
Labels: enhancement

#4042 Allow import on startup for sites other than pastebin
  manifest.xml
  src/Classes/ImportTab.lua
  src/Modules/BuildSiteTools.lua
  src/Modules/Main.lua
Labels: enhancement

#4060 Petrifiedblood
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#4061 Add Black Zenith, The Gluttonous Tide, and Divine Inferno
  src/Data/Uniques/Special/New.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4063 Frost shield
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4065 Fix maxhit
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: technical

#4066 fix: Mirage Archer culling DPS
  src/Modules/CalcOffence.lua
  src/Modules/Calcs.lua
Labels: bug, crash

#4054 QoL: Confirm import with 1-click or Return key
  src/Classes/ButtonControl.lua
  src/Classes/ImportTab.lua
Labels: enhancement

#4067 fix: Inspired Learning modifier fix
  src/Classes/Item.lua
Labels: bug

#4070 Properly detect equipped Abyssal Jewels when Deleting Unused Items
  src/Classes/ItemListControl.lua
Labels: bug

#4074 Add all data from 3.17
  src/Data/Bases/bow.lua
  src/Data/Bases/quiver.lua
  src/Data/ClusterJewels.lua
  src/Data/EnchantmentHelmet.lua
  src/Data/Essence.lua
  src/Data/Gems.lua
  src/Data/Global.lua
  src/Data/LegionPassives.lua
  src/Data/Minions.lua
  src/Data/ModFlask.lua
  src/Data/ModItem.lua
  src/Data/ModJewel.lua
  src/Data/ModJewelAbyss.lua
  src/Data/ModJewelCluster.lua
  src/Data/ModMaster.lua
  src/Data/ModVeiled.lua
  src/Data/Pantheons.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/Spectres.lua
  src/Data/StatDescriptions/active_skill_gem_stat_descriptions.lua
  src/Data/StatDescriptions/aura_skill_stat_descriptions.lua
  src/Data/StatDescriptions/buff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/curse_skill_stat_descriptions.lua
  src/Data/StatDescriptions/debuff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Data/StatDescriptions/minion_attack_skill_stat_descriptions.lua
  src/Data/StatDescriptions/minion_skill_stat_descriptions.lua
  src/Data/StatDescriptions/monster_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Data/Uniques/Special/WatchersEye.lua
  src/Export/Bases/quiver.txt
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
  src/Export/Skills/spectre.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
Labels: enhancement

#4075 Fix flask export
  src/Export/spec.lua
Labels: technical

#4098 Update all new league Uniques
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4126 Fix issue where General's Cry would set attack rate to 1 for certain skills
  src/Modules/CalcOffence.lua
Labels: bug

#4121 Fix issue importing Fobidden Flame/Flesh
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Data/Uniques/Special/Generated.lua
  src/Modules/ModParser.lua
Labels: bug

#4114 Fix Energy Blade incompatibility with new Fobidden Prismatic Jewels
  src/Modules/CalcSetup.lua
Labels: bug

#4116 Fix for culling strike on mirages adding extra damage
  src/Modules/CalcOffence.lua
Labels: bug

#4095 Fix an issue where degens were not working with Mind Over Matter
  src/Modules/CalcDefence.lua
Labels: bug

#4086 Fix issue where certain modifiers weren't being converted properly (e.g. Battlemage)
  spec/System/TestAttacks_spec.lua
  src/Modules/CalcTools.lua
Labels: bug

#4127 Fix an issue where chance to inflict an ailment on a critical strike could be lower than on a non-crit for alternate ailments
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug

#4112 Add support for Elementalist's Primal Aegis
  src/Classes/ModStore.lua
  src/Classes/PassiveSpec.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4096 Implement Life Recoverable
  src/Modules/CalcDefence.lua
Labels: enhancement

#4129 Update Uniques that used old Blood Magic wording
  src/Data/Uniques/axe.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: bug

#4128 Add support for 2 new cluster jewel mods
  src/Modules/ModParser.lua
Labels: enhancement

#4131 Fix Rigwald's Curse mod parsing
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug

#4134 Add Delirium effect scaling
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4136 Update README images
  README.md
Labels: documentation

#4151 Fix Kinetic Bolt and Earthquake not fully scaling with Spell Damage/Cast Speed
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
Labels: bug

#4160 Fix ensnare stacks not showing for Ensnaring Arrow
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/ConfigOptions.lua
Labels: bug

#4148 Bow Proj Speed as damage only applies to hits
  src/Modules/CalcOffence.lua
Labels: bug

#4188 Fix missing catalyst on 'Mark of the Elder' ring
  src/Data/Uniques/ring.lua
Labels: accuracy

#4181 Corrected spelling of Effective Hit Pool Description
  src/Modules/CalcDefence.lua
Labels: user-interface

#4161 Fix chilling areas not applying Bonechill
  src/Modules/CalcPerform.lua
Labels: bug

#4187 Display session ID box when 401 is encountered on Import
  src/Classes/ImportTab.lua
Labels: bug

#4211 Absolution Quality is now a minion mod
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#4185 Feat: Updated Exported Data to Patch 3.17.1
  src/Data/Bases/quiver.lua
  src/Data/EnchantmentHelmet.lua
  src/Data/Global.lua
  src/Data/ModItem.lua
  src/Data/ModJewel.lua
  src/Data/ModJewelAbyss.lua
  src/Data/ModJewelCluster.lua
  src/Data/ModMaster.lua
  src/Data/ModVeiled.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/minion_skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Data/Uniques/Special/WatchersEye.lua
  src/Export/Scripts/skills.lua
Labels: enhancement

#4213 fix "maxmium" in test builds
  spec/TestBuilds/3.13/Dual Savior.lua
  spec/TestBuilds/3.13/Dual Savior.xml
  spec/TestBuilds/3.13/Dual Wield Cospris CoC.lua
  spec/TestBuilds/3.13/Dual Wield Cospris CoC.xml
  spec/TestBuilds/3.13/Generals Perforate Zerker.lua
  spec/TestBuilds/3.13/Generals Perforate Zerker.xml
  spec/TestBuilds/3.13/Mirage Archer Toxic Rain.lua
  spec/TestBuilds/3.13/Mirage Archer Toxic Rain.xml
Labels: technical

#4214 minor spelling corrections
  CHANGELOG.md
  changelog.txt
  docs/rundown.md
Labels: technical

#4215 minor spelling corrections
  src/Classes/DropDownControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/SearchHost.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
Labels: technical

#4216 minor spelling corrections
  src/Data/Global.lua
  src/Data/Uniques/Special/race.lua
  src/Modules/CalcPerform.lua
  src/Modules/Common.lua
Labels: technical

#4236 Add missing spell flag to triggered spells from Atziri's Rule
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug

#4232 Add missing duration flag to Flame Surge
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug, accuracy

#4239 Swap subtext and appname positions in window title
  src/Modules/Main.lua
Labels: user-interface

#4238 Fix nil error when comparing passive tree skill nodes
  src/Classes/PassiveTreeView.lua
Labels: bug, crash

#4237 Fix two nil errors related to equipped items
  src/Classes/ItemsTab.lua
  src/Modules/CalcActiveSkill.lua
Labels: bug, crash

#4231 Fix crash caused by Mortal Conviction still appearing on some uniques
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/shield.lua
  src/Modules/CalcPerform.lua
Labels: bug, crash

#4229 Fix: Update skills to use values from the ggpk
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/spectre.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcActiveSkill.lua
Labels: technical

#4225 Remove royale mods from crafting dropdowns
  src/Data/ModItem.lua
  src/Export/Scripts/mods.lua
Labels: bug

#4224 Add increased trap damage back as a stat
  src/Data/SkillStatMap.lua
Labels: bug

#4175 Fixes #2736: ExtraAuraEffect now respects skill config for effects th…
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: accuracy

#4177 Fix an issue where Secrets of Suffering wasn't applying
  src/Modules/CalcOffence.lua
Labels: bug

#4170 fix: battlemage's cry spell damage to attacks not applying
  src/Modules/CalcPerform.lua
Labels: bug
