Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-08, with the labels that each got.

#4681 FIX: Add an emtpy stat to remove confusing red text on incinerate
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: user-interface

#4645 Fix buff stages on Scorching Ray, Frost Shield, and Sigil of Power
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/StatDescriber.lua
Labels: bug:calculation

#4668 fixes various typos in "safe" text
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  CHANGELOG.md
  changelog.txt
  src/Classes/ModDB.lua
  src/Classes/PassiveSpec.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: documentation

#4651 Fix veiled mod pool on autogenerated unique weapons
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/jewel.lua
Labels: bug:accuracy

#4650 Fix Bleed DPS when using multiple totems
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#4656 Fix alternate ailments not working with anomalous grace.
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#4672 Update timeless schema
  src/Export/spec.lua
Labels: technical

#4637 General improvements to "Damaging Hits" section and armour breakdown.
  src/Modules/CalcDefence.lua
Labels: enhancement, user-interface

#4602 Update a wide variety of unique items
  src/Data/Uniques/Special/race.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4453 Always use configured or base chill for bonechill and remove bonechill config
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: bug, bug:accuracy

#4686 Apply spell suppress early if 100% and add gain on suppress
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4701 Support for non critical strikes deal less damage
  src/Modules/ModParser.lua
Labels: enhancement

#4693 Fix bottom bar wrapping in the tree tab
  src/Classes/TreeTab.lua
Labels: user-interface

#4646 Fix Sidebar always showing Culling DPS and Recoverable ES
  src/Modules/Build.lua
Labels: user-interface

#4707 Add support for more Ailment effect
  src/Modules/ModParser.lua
Labels: enhancement

#4704 Properly support gain on kill
  src/Data/Uniques/jewel.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4688 Add support for deal 10% less damage on IndomitableResolve
  src/Modules/ModParser.lua
Labels: enhancement

#4687 Condition used Life flask in the past 10 seconds
  src/Modules/ModParser.lua
Labels: enhancement

#4703 Add support for Debuff expiration rate
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4706 Add support for recoup
  src/Data/Uniques/jewel.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4685 Add more sources of modifiers to enemy damage
  src/Modules/ModParser.lua
Labels: enhancement

#4664 Add basic support to show skill PvP scaling
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#4677 Add warning not to edit file manually
  src/Data/StatDescriptions/active_skill_gem_stat_descriptions.lua
  src/Data/StatDescriptions/aura_skill_stat_descriptions.lua
  src/Data/StatDescriptions/banner_aura_skill_stat_descriptions.lua
  src/Data/StatDescriptions/beam_skill_stat_descriptions.lua
  src/Data/StatDescriptions/brand_skill_stat_descriptions.lua
  src/Data/StatDescriptions/buff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/curse_skill_stat_descriptions.lua
  src/Data/StatDescriptions/debuff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Data/StatDescriptions/minion_attack_skill_stat_descriptions.lua
  src/Data/StatDescriptions/minion_skill_stat_descriptions.lua
  src/Data/StatDescriptions/minion_spell_damage_skill_stat_descriptions.lua
  src/Data/StatDescriptions/minion_spell_skill_stat_descriptions.lua
  src/Data/StatDescriptions/monster_stat_descriptions.lua
  src/Data/StatDescriptions/offering_skill_stat_descriptions.lua
  src/Data/StatDescriptions/secondary_debuff_skill_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Data/StatDescriptions/variable_duration_skill_stat_descriptions.lua
  src/Export/Scripts/statdesc.lua
Labels: documentation

#4640 Improve scaled modifier precision
  src/Classes/ModStore.lua
  src/Modules/Data.lua
Labels: bug:calculation

#4518 Display reservation efficiency as percentage with two decimal places instead of a full float multiplier
  src/Modules/CalcPerform.lua
Labels: user-interface, bug:accuracy

#4633 Display effect of active gem variant when mousing over the "Variant" drop-down selector and small behaviour change to gemSelectControl
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
Labels: user-interface

#4712 Fix spell and correct tooltip
  src/Modules/ConfigOptions.lua
Labels: documentation

#4711 Feat: add support for Non-Vaal gems
  src/Modules/CalcTools.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4710 Add support for Debilitate
  src/Classes/ConfigTab.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4735 Imported items were getting incorrect variable percentages because of default quality coming in as 20
  src/Classes/Item.lua
Labels: bug:calculation

#4673 Jugg armour applies to ele damage
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4357 Update fix_ascendancy_positions.py to support new extra tree nodes
  fix_ascendancy_positions.py
  src/Export/spec.lua
Labels: enhancement, technical

#4765 Fix: Selected Mastery Tree Upconversion Error
  src/Classes/PassiveSpec.lua
Labels: bug

#4767 [Kalandra] Batch of unique update. All remaining from M to O
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#4763 [Kalandra]Batch of uniques update. All missing starting with T
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
Labels: bug:accuracy

#4760 [Kalandra]Batch of uniques update. All missing starting with R
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/wand.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4752 [Kalandra] Lifetap & Blessing interaction
  src/Data/Skills/sup_str.lua
  src/Data/Uniques/shield.lua
Labels: bug:behaviour

#4769 [Kalandra] Batch of uniques update. All missingfrom D to L
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4753 [Kalandra] Batch of uniques update. All missing starting with S
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4729 Fix: Blood of the Karui Life recovered and wording
  src/Data/Uniques/flask.lua
Labels: bug:accuracy

#4740 Fix: Multistrike damage calculation with skills which have bow and melee Tag
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug:behaviour

#4697 [Kalandra] update ward recharge speed
  src/Modules/Data.lua
Labels: bug:calculation

#4696 [Kalandra] Update brittle values
  src/Modules/Data.lua
Labels: bug:calculation

#4780 Add support for minions have unholy might
  src/Modules/ModParser.lua
Labels: enhancement

#4747 [Kalandra] Update batch 1 of uniques.
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/wand.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4751 [Kalandra] Update batch 2 of uniques.
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4754 [Kalandra] Update batch 3 of Uniques
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4748 [Kalandra] No longer obtainable uniques
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#4757 [Kalandra] Update batch 4 of uniques.
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4779 [Kalandra] Add support for Arrow Dancing
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4775 [Kalandra] Update replica bitterdream
  src/Data/Uniques/mace.lua
Labels: bug:accuracy

#4774 [Kalandra] Add new uniques
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4755 [Kalandra] Update Ngamahu's Sign
  src/Data/Uniques/ring.lua
Labels: bug:accuracy

#4746 [Kalandra] Add support for counting Mastery Type allocations
  src/Classes/PassiveSpec.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4727 Add support for piecewise parsing triple damage mods.
  src/Modules/ModParser.lua
Labels: enhancement

#4702 [Kalandra] update bitterdream
  src/Data/Uniques/mace.lua
Labels: bug:accuracy

#4772 Set skillset to nil instead of removing it from table and reordering it
  src/Classes/SkillSetListControl.lua
Labels: crash

#4720 Fix: Thrusting should be a base subType
  src/Data/Bases/sword.lua
  src/Export/Bases/sword.txt
Labels: bug:accuracy

#4756 [Kalandra] Support for inverted reflection stats
  src/Modules/ModParser.lua
Labels: enhancement

#4745 Update uniques for 3.19.0 Kalandra
  src/Data/Uniques/belt.lua
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#4800 Fix two export script errors
  src/Export/Main.lua
  src/Export/spec.lua
Labels: technical

#4797 Fix: correct size for raw data read bounds checking
  src/Export/Classes/Dat64File.lua
Labels: bug, technical

#4795 Take into account weapon conditions for shock
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug

#4786 [Kalandra] Add new chainbreaker wording and displays Rage Regeneration
  src/Data/LegionPassives.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4750 [Kalandra] Add support for stacking max shock
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4749 [Kalandra] Trickster mods and action speed
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4709 Longshot affects all projectiles that hit
  src/Modules/ModParser.lua
Labels: bug:behaviour

#4694 [Kalandra] Minion charges and ailments work like players
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#4782 Add support for trickster node Heartstopper
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4718 Add support for PvP hit taken
  src/Classes/ConfigTab.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4715 Improve stun on you calcs
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4721 Add support for Ryslatha life flask charge generation
  src/Modules/ModParser.lua
Labels: enhancement

#4700 [Kalandra] removal of 10% taken from mana before life
  src/Data/Uniques/body.lua
Labels: bug:accuracy

#4699 [Kalandra] nerf to omniscience
  src/Data/Uniques/amulet.lua
Labels: bug:accuracy

#4698 [Kalandra] add minus max res for 3.19 melding of the flesh
  src/Data/Uniques/jewel.lua
Labels: bug:accuracy

#4638 Fix Blood offering stats not calculated #744
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: enhancement, bug:behaviour

#4770 Add support for chill and shock effect mod parsing
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement, technical

#4806 Improve shock and chill multipliers
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: technical

#4623 Fix "save" on generate #4619
  src/Classes/CalcsTab.lua
  src/Classes/ConfigTab.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveSpec.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: bug

#4649 Cap of dot dps
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/Calcs.lua
  src/Modules/Data.lua
Labels: bug:calculation

#4808 Add warning for full dot DPS cap
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: enhancement

#4802 Feat: add support for Lightning Conduit's New Trigger Flag
  src/Modules/CalcPerform.lua
Labels: enhancement

#4809 Restructure leech to apply cap later.
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#4814 Update unique changes from patch note updates
  src/Data/Uniques/belt.lua
  src/Data/Uniques/gloves.lua
Labels: bug:accuracy

#4705 Add support for enemy overwhelm and fixes some issues.
  src/Modules/CalcDefence.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4820 Prevent differnt types of burning/caustic ground from stacking
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/minion.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/minion.txt
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/Calcs.lua
Labels: bug:behaviour

#4821 Fix scorching ray not stacking as totems
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#4826 Fix: Tornado calculates DPS with hit rate instead of cast rate
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#4817 [Kalandra] Kaoms spirit
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4816 Add support for basic link skill passing.
  src/Modules/ModParser.lua
Labels: enhancement

#4813 Show/Hide skill cost based upon whether it has a base cost.
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#4819 Update changelog 2.20.0
  CHANGELOG.md
  changelog.txt
Labels: technical

#4829 Use correct max shock in breakdown
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#4832 Fix timeless jewel socket index bug
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: bug

#4835 Fix missing unique sliders
  src/Modules/Main.lua
Labels: bug

#4836 Filter out unused modifier line ranges
  src/Classes/Item.lua
Labels: bug:behaviour

#4838 Reintroduce Show/Hide skill cost based upon whether it has a base cost
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#4901 August 18th Replica Adjustment
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/ring.lua
Labels: bug:accuracy

#4893 Rebuild all timeless data on load
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: bug, crash

#4894 Update Ventor's Gamble and Soul RIpper
  src/Data/Uniques/flask.lua
  src/Data/Uniques/ring.lua
Labels: bug

#4881 Apply dps multiplier fix to spells
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#4860 PvP Hit Taken Colour for changes was inverted
  src/Modules/Build.lua
Labels: user-interface

#4857 Fix gain on kill not working for attacks
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#4846 Add The Poised Prism and Elevore
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4844 Fix timeless jewel node weight bugs
  src/Classes/TreeTab.lua
Labels: bug

#4916 add breakdowns for burning and caustic ground from ailments
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#4859 Update Heartstopper config
  src/Modules/ConfigOptions.lua
Labels: user-interface

#4880 Rage regen fixes
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#4878 Fix spelling (in comments)
  fix_ascendancy_positions.py
Labels: documentation

#4903 Fix checbox not updating when selecting vaal skills
  src/Classes/SkillsTab.lua
Labels: bug

#4911 [Kalandra] adds support for Lose 29 Life Per Second
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4897 Add new Grand Spectrum mods and change Grand Spectrum parsing to generic one
  src/Classes/Item.lua
  src/Data/Uniques/jewel.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4922 Remove Main Hand background color from global Ignite Dot Multi section
  src/Modules/CalcSections.lua
Labels: user-interface

#4858 Fix missing life on Demon Stitcher
  src/Data/Uniques/gloves.lua
Labels: bug:accuracy

#4925 Kalandra Data Export
  src/Data/Global.lua
  src/Data/SkillStatMap.lua
  src/Export/Bases/ring.txt
  src/Export/Bases/wand.txt
  src/Export/Scripts/enchant.lua
  src/Export/Scripts/masters.lua
  src/Export/Scripts/mods.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_int.txt
  src/Export/spec.lua
  src/Export/statdesc.lua
  src/Modules/StatDescriber.lua
Labels: enhancement

#4928 Fix: updated mod parsing for new claw implicit
  src/Modules/ModParser.lua
Labels: enhancement

#4926 Fix regression in #4893
  src/Classes/TreeTab.lua
Labels: bug, technical

#4918 Adds ability to automatically calculate # of Explosive Arrow Fuses
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: enhancement

#4931 Fix caustic ground breakdown
  src/Modules/CalcOffence.lua
Labels: crash

#4935 fix watchers eye export
  src/Export/Scripts/mods.lua
Labels: bug

#4965 Fix parsing of Grand Spectrum for minions
  src/Classes/Item.lua
Labels: bug

#4989 Clean up "Aul's Uprising (Intelligence)" mod-list
  src/Data/Uniques/amulet.lua
Labels: bug:accuracy

#4986 Add support for Frostblink CDR from nearby enemy
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#4979 Change Vorana's March to be auto generated
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/WatchersEye.lua
  src/Data/Uniques/boots.lua
  src/Export/Scripts/mods.lua
Labels: bug:accuracy

#4978 Fix Lightning Conduit and Galvanic Field scaling with area damage
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#4977 Fix Aura effect on Self not counting towards Aura effect breakdown
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#4950 Update stormfire and add support for mod.
  src/Data/Uniques/ring.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4948 FIX: fix jewels applying to the same node twice if overlapping
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#4945 Use Life/EnergyShieldRegenRecovery for power builder
  src/Classes/CalcsTab.lua
Labels: crash

#4934 Remove Dot Ground incorrect caps
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#4921 Add support for "nearby allies have culling strike"
  src/Modules/Build.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4920 Add button to filter unique source
  src/Classes/ItemDBControl.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
Labels: enhancement

#4919 Fix energy blade applying each iteration.
  src/Modules/CalcOffence.lua
Labels: bug

#4883 Improve avoidance calcs
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
Labels: enhancement
