Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-07, with the labels that each got.

#4510 Legacy of Fury level requirement
  src/Data/Uniques/boots.lua
Labels: bug, accuracy

#4505 Fix corrosion not being disabled when mod is not present.
  src/Modules/ConfigOptions.lua
Labels: bug, accuracy

#4504 Fix Energy Shield Recharge mastery
  src/Modules/CalcDefence.lua
Labels: bug, accuracy

#4496 Fix ignite with cast on death
  src/Modules/CalcOffence.lua
Labels: bug, accuracy

#4495 Fix Paradoxica
  src/Data/Uniques/Special/Generated.lua
Labels: bug, accuracy

#4493 Improve skill gem state persistence
  src/Classes/SkillsTab.lua
Labels: bug

#4491 Fix Chain Hook Radius per Rage
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug, accuracy

#4490 Add Pale Seraphim "Thunder Web" debuff
  src/Data/Skills/spectre.lua
  src/Export/Skills/spectre.txt
Labels: enhancement

#4489 Save anointed notables to legion jewel editedNode data
  src/Classes/PassiveSpec.lua
Labels: bug

#4488 Fix warcry duration and cooldown calcs
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: bug, accuracy

#4486 Fixes labels having an incorrect font size and alignment for checkmark boxes.
  src/Classes/CheckBoxControl.lua
Labels: bug, user-interface

#4479 Remove Phase Acrobatics from Impossible Escape
  src/Data/Uniques/Special/Generated.lua
Labels: bug

#4472 Fix incorrect Cruelty effect scaling
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug

#4471 Fix Flat Reservation Rounding
  src/Modules/CalcPerform.lua
Labels: bug, accuracy

#4478 Rename old dodge chance mods on watcher's eye
  src/Data/Uniques/Special/Generated.lua
Labels: accuracy

#4464 Add support for "% increased cast speed if a minion has been killed recently"
  src/Modules/ModParser.lua
Labels: accuracy

#4463 Stop Noxious Catalyst from scaling Icefang Orbit's chance to poison
  src/Data/Uniques/ring.lua
Labels: bug, accuracy

#4461 Add support for Magic Utility Flasks applied to you have inc effect
  src/Classes/ItemsTab.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4443 Add support for brittle/sapped ground and alt ailment boot implicits
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug, enhancement

#4439 Fix unicode sanitization issues
  src/Classes/ItemsTab.lua
Labels: bug

#4426 put move speed below resists in side-bar
  src/Modules/Build.lua
Labels: user-interface

#4436 Add new config options for Boss Skill Presets
  src/Classes/ConfigTab.lua
  src/Classes/EditControl.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: user-interface

#4515 Fixed smite area hit being classed as melee
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#4512 Update Skyforth, Victario's Flight, Mindspiral, Mutewind Seal
  src/Data/Uniques/boots.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/ring.lua
Labels: accuracy

#4542 Update source text of unique cluster jewels
  src/Data/Uniques/jewel.lua
Labels: accuracy

#4531 Fix Vaal lightning strike projectiles not counting as projectiles
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug, accuracy

#4529 Further timeless jewel search improvements
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TimelessJewelSocketControl.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#4441 Fix overlapping tooltips, move bandit and pantheon options into the Config tab
  src/Classes/ButtonControl.lua
  src/Classes/CalcSectionControl.lua
  src/Classes/CalcsTab.lua
  src/Classes/CheckBoxControl.lua
  src/Classes/ConfigTab.lua
  src/Classes/ControlHost.lua
  src/Classes/DropDownControl.lua
  src/Classes/EditControl.lua
  src/Classes/GemSelectControl.lua
  src/Classes/ListControl.lua
  src/Modules/Build.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug, user-interface

#4543 Docs - Fix dead links and refactor to use relative links
  docs/addingMods.md
  docs/modSyntax.md
Labels: documentation

#4448 Add enter function for Import Edit control
  src/Classes/ImportTab.lua
Labels: user-interface

#4519 Update wording on Maw of Conquest, Thousand Teeth Temu
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/shield.lua
Labels: accuracy

#4492 Fix a bug where if affected by a vaal aura you weren't considered affected by the regular aura
  src/Modules/CalcPerform.lua
Labels: bug, accuracy

#4537 Add self curse effect to calcs tab.
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#4309 Refactor manifest updater
  manifest.cfg
  update_manifest.py
Labels: technical

#4514 Correctly handle 100% reduced reservation efficiency and greater.
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug, accuracy

#4435 Update ailment threshold to current values
  src/Data/Misc.lua
  src/Export/Scripts/miscdata.lua
  src/Export/spec.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement, accuracy

#4440 Fix elemental ailments defensive calculations
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: bug, accuracy

#4452 Fix socket group copy/paste
  src/Classes/SkillsTab.lua
Labels: bug

#4523 Add display for totem resistances in skill type specific stats
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#4507 Fix more Eldritch mods
  src/Classes/ModStore.lua
  src/Modules/ModParser.lua
Labels: bug, accuracy

#4526 Fix Flask Duration to match in game values
  src/Classes/Item.lua
Labels: bug, accuracy

#4546 Further Timeless Jewel search improvements
  src/Classes/PassiveSpec.lua
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TimelessJewelSocketControl.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#4547 Fix Herald of Purity minions missing a duration
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug

#4532 Fix alternate quality dropdown options not changing on gem deletion
  src/Classes/SkillsTab.lua
Labels: bug

#4524 Add Support for Supreme Ego
  src/Classes/ModStore.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4525 Refactor wither to apply strongest wither effect
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug, accuracy

#4487 Feat: initial support for Unearth corpse calculation
  src/Data/Misc.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Scripts/miscdata.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4520 Add Default Item Affix Quality option
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Modules/Main.lua
Labels: enhancement

#4530 Fix Out of Memory crash in Items Tab
  src/Classes/ItemsTab.lua
Labels: crash

#4548 Fix saving of changed placeholdered values
  src/Classes/ConfigTab.lua
Labels: bug

#4549 Add support for % of damage taken bypasses ward
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4447 Add support for skill sets (socket group sets)
  src/Classes/SkillSetListControl.lua
  src/Classes/SkillsTab.lua
Labels: enhancement

#4552 Add support for ailment immunity mod on timeless jewels
  src/Modules/ModParser.lua
Labels: enhancement

#4484 Fix multi number mods scaling the wrong number with catalysts
  src/Classes/Item.lua
  src/Modules/ItemTools.lua
Labels: bug, accuracy

#4554 Fix undo resetting active display group
  src/Classes/SkillsTab.lua
Labels: bug

#4557 Exclude failing build tests
  .busted
  spec/System/TestBuilds_spec.lua
Labels: technical

#4556 Automate installer upload
  .github/workflows/installer.yml
Labels: technical

#4555 Fix saving of section/subsection collapsing in calcs
  src/Classes/CalcSectionControl.lua
  src/Classes/CalcsTab.lua
Labels: enhancement

#4575 Fix DoT skill handling in export
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_int.lua
  src/Export/Scripts/skills.lua
  src/Export/spec.lua
Labels: bug

#4578 Fix legion passive index off-by-one error
  src/Classes/PassiveSpec.lua
  src/Classes/TreeTab.lua
  src/Data/LegionPassives.lua
  src/Export/Scripts/legionPassives.lua
  src/Modules/Data.lua
Labels: bug, crash

#4579 Remove invalid Lua pattern text
  src/Classes/TreeTab.lua
Labels: technical

#4580 Search timeless jewel node stats in dropdown
  src/Classes/TreeTab.lua
Labels: enhancement

#4581 Fix auras disabling due to multiple iterations of reservation calculations
  src/Modules/CalcPerform.lua
Labels: bug

#4586 Fix anointed notables not being conquered
  src/Modules/CalcSetup.lua
Labels: bug

#4587 Skip invalid nodeIDs for Glorious Vanity
  src/Modules/Data.lua
Labels: crash

#4588 Skip writing uncompressedFile if denied access, and skip reading changelog.txt if it doesn't exist
  src/Modules/Data.lua
  src/Modules/Main.lua
Labels: crash

#4589 Prevent saving nil groupCount to build XML
  src/Classes/SkillsTab.lua
Labels: technical

#4590 Fix broken mastery import state
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTreeView.lua
Labels: crash

#4593 Improve default item affix quality UI
  src/Modules/Main.lua
Labels: user-interface

#4591 Fix "NaN" EHP initialization error and cap enemyLevel
  src/Classes/EditControl.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug

#4594 Allow certain controls not require focus to display tooltips
  src/Classes/ButtonControl.lua
  src/Classes/DropDownControl.lua
  src/Classes/GemSelectControl.lua
  src/Classes/ItemListControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/ListControl.lua
  src/Classes/SharedItemListControl.lua
  src/Classes/SkillsTab.lua
Labels: user-interface

#4584 Remove leftover skillSet field on Skill when saving to XML
  src/Classes/SkillsTab.lua
Labels: technical

#4595 Fix Skill Set manage naming and remove socket group global variable in CalcSetup
  src/Classes/SkillsTab.lua
  src/Modules/CalcSetup.lua
Labels: technical, user-interface

#4608 Fix Vaal Discipline not counting towards Aura count
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#4606 Fix enable skill tooltip visibility for non-vaal active skill gems
  src/Classes/SkillsTab.lua
Labels: bug

#4604 Fix default level for pinnacles
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug

#4600 Fix evasion to armour conversion calculation not including "armour and evasion" base stats
  src/Modules/CalcDefence.lua
Labels: bug, accuracy

#4609 Prevent invalid character level values
  src/Modules/Build.lua
  src/Modules/Main.lua
Labels: bug, crash

#4610 Fix Trypanon crit chance calculations
  src/Modules/CalcOffence.lua
Labels: bug, accuracy

#4603 Fix catalysts visually not scaling certain mods.
  src/Classes/Item.lua
  src/Modules/ItemTools.lua
Labels: bug

#4641 Fix total more multipliers not being round to nearest percent as done ingame.
  src/Classes/ModDB.lua
Labels: bug:calculation

#4643 Fix Evasion as Extra Armour with Iron Reflexes
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#4634 Makes pobbin matching less restrictive
  src/Modules/BuildSiteTools.lua
Labels: technical

#4626 cleanup Boss Presets
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: technical

#4620 fix showwarnings: remove unnecessary (and broken) code
  src/Modules/Build.lua
Labels: technical

#4621 fix spelling in Build.lua
  src/Modules/Build.lua
Labels: technical

#4618 Change sidebar to show red numbers for unreserved life of 0
  src/Modules/Build.lua
Labels: user-interface

#4613 Add full support for Vorana's March
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Uniques/boots.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
  src/Modules/ModParser.lua
Labels: enhancement

#4612 Fix placeholder physical damage applying to bosses
  src/Modules/CalcDefence.lua
Labels: bug

#4615 force rebuild to initialise boss presets and remove phys fallback
  src/Classes/ConfigTab.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/ConfigOptions.lua
Labels: bug

#4617 Node power sorting
  src/Classes/NotableDBControl.lua
  src/Modules/CalcDefence.lua
Labels: bug, user-interface

#4624 Fix config tab being 1 change behind enemy level
  src/Classes/ConfigTab.lua
  src/Modules/Build.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug, user-interface

#4652 cleanup impossibleEscape by combining similar variant lines
  src/Data/Uniques/Special/Generated.lua
Labels: technical

#4622 Timeless jewel search improvements
  src/Classes/PassiveSpec.lua
  src/Classes/SliderControl.lua
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TimelessJewelSocketControl.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
  src/Modules/Main.lua
Labels: enhancement

#4667 Add missing DLL for local dev
  runtime/msvcr100.dll
Labels: technical
