Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-09, with the labels that each got.

#5059 Fix Lucky Attack Damage Applying to spells
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5045 Fix ice spear enchant not applying to all projectiles skill part.
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5041 Add Physical KeywordFlag
  src/Data/Global.lua
Labels: bug, technical

#5040 Generalise Multistrike implemenation for shields.
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: technical

#4583 Add reservation scaling with stages for blood sacrament
  src/Modules/CalcPerform.lua
Labels: enhancement

#5022 Fix Cluster Jewels not showing DPS stats in item crafter
  src/Modules/CalcSetup.lua
Labels: bug

#5021 Fix: Add support for Cold Conduction cluster jewel notable
  src/Modules/ModParser.lua
Labels: enhancement

#5047 Fix count being nil when importing a build and add default altQu…
  src/Classes/SkillsTab.lua
Labels: bug

#5046 Fix some stats with bloodstorm conditionals being considered a buff
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug:behaviour

#5039 Fix "tag" being used in place of "tagList" causing only the first tag to be added
  src/Modules/ModParser.lua
Labels: bug

#5038 Shock effect should apply to shocked ground
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#5036 fix crash for pvp when checking support gems
  src/Modules/CalcOffence.lua
Labels: bug, crash

#5035 Add rage generation flag to chains of empacipation
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5018 Update Brittle Formula
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5015 Re-order the leagues dropdown in the import menu
  src/Classes/ImportTab.lua
Labels: enhancement

#5003 FIX: Ailement mods from skill active skill gems not applying
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#5014 Implement parsing for some currently unsupported reflected mods.
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5061 Show Increased Global Energy Shield on Calcs
  src/Modules/CalcDefence.lua
Labels: bug

#5067 Fix Thread of Hope allowing you to allocate ascendancy nodes
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#4899 Add google sheets parsing to build import
  src/Classes/ImportTab.lua
Labels: enhancement

#4906 Improve handling of unscalable mods and fix some mods from alternate qualities not applying.
  src/Classes/ModStore.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#4636 fix totems not being affected by auras
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#5055 FIX crash when generating fall back weights caused by missing source
  src/Classes/ModDB.lua
Labels: bug, crash

#4886 Fix support gems not adding their flags if they themselves require a flag added by a support gem lower in the supportList
  src/Modules/CalcActiveSkill.lua
Labels: bug:behaviour

#5029 Fix Barrage and Barrage Support ambiguity
  src/Classes/GemSelectControl.lua
  src/Data/Gems.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Scripts/skills.lua
  src/Modules/CalcTools.lua
Labels: enhancement

#5099 Fix Lightning Conduit More damaging with hits missing hit tag.
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation
