Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-06, with the labels that each got.

#4406 Fix: Double Counting Dual Wield Poison Stacks
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug

#4401 Fix pobb.in match pattern used while importing
  src/Modules/BuildSiteTools.lua
Labels: bug

#4398 Change import from website to be 1 click operation
  src/Classes/ImportTab.lua
Labels: user-interface

#4386 Fix crash when loading build containing a newer tree
  src/Modules/Build.lua
Labels: crash

#4377 Remove tooltip if covering dropdown is opened
  src/Modules/Build.lua
Labels: user-interface

#4415 Add support for Weapon local Overwhelm mod
  src/Modules/ModParser.lua
Labels: new-calculations

#234 Fixed Summon Holy Relic's Boon Aura
  src/Data/Skills/act_int.lua
  src/Data/Skills/minion.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/minion.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4371 Split max hit display (and colorize it) in sidebar
  src/Data/Global.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#4416 Fix Shaper of Winter + Storms not affecting Brittle + Sap
  src/Modules/ModParser.lua
Labels: bug

#4420 Add self damage breakdown for Forbidden Rite
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: new-calculations

#4419 Add support for many helmet enchants
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: new-calculations

#4454 Fix Ming's Heart variant typo
  src/Data/Uniques/ring.lua
Labels: bug

#4458 Fix: Patch 3.18.1 changed Granted Effects DAT structure
  src/Classes/GemSelectControl.lua
  src/Classes/ModList.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/stat_descriptions.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/spectre.txt
  src/Export/spec.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
Labels: bug, help wanted

#4502 Fix Determination aura alt quality mod
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug, accuracy
