Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-10, with the labels that each got.

#3885 Add build pricing and item optimization to Items Tab
  .gitignore
  src/Classes/EditControl.lua
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/SkillsTab.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeQueryRateLimiter.lua
  src/Classes/TradeQueryRequests.lua
  src/Classes/TreeTab.lua
  src/Data/Global.lua
  src/Data/QueryMods.lua
  src/Launch.lua
  src/Modules/BuildSiteTools.lua
  src/Modules/CalcSetup.lua
  src/Modules/Common.lua
  src/Modules/Main.lua
Labels: enhancement

#4766 Add support for "chance for flasks you use to not consume charges"
  src/Classes/ItemsTab.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4611 Documentation - Add more tips to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4724 Extend default gem level functionality
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
Labels: enhancement

#4716 Do not hide config options that are configured without source
  src/Classes/ConfigTab.lua
Labels: bug

#4734 Add breakdown for Boneshatter self damage
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcSections.lua
Labels: enhancement

#5142 Fix incorrect timeless jewel ring colors when searching a node on the passive tree
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#5145 Fix Divergent Fist of War increasing Stun Threshold
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug:calculation

#5146 Fix breakdown of mana cost not showing in certain situations
  src/Modules/CalcOffence.lua
Labels: user-interface

#5139 Fix Anomalous Energy Blade Shock Chance
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug

#5137 Add support for Soul Eater stack limit
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement, bug:calculation

#5136 Adjust sample Brittle effects
  src/Modules/CalcOffence.lua
Labels: user-interface, bug:accuracy

#5135 Add support for Anomalous Predator
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: enhancement

#5134 Fix missing elemental resist calculation
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5133 Fix Devotion not working with minion mods
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5119 Fix global energy shield being mistaken for local
  src/Modules/ModParser.lua
Labels: bug:calculation

#5115 Truncate resistances.
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5103 Correct Fanaticism tooltip
  src/Modules/ConfigOptions.lua
Labels: user-interface

#5090 Add missing poison multiplier breakdown for spells
  src/Modules/CalcSections.lua
Labels: user-interface

#5082 fix punctuation
  src/Classes/TreeTab.lua
  src/Modules/CalcDefence.lua
Labels: documentation

#5155 Fix parsing for new wording on Aegis Aurora
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy
