Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-03, with the labels that each got.

#4276 Fix parsing of Soul of Abberath self Ignite duration
  src/Modules/ModParser.lua
Labels: bug

#4264 Fix Challenger Charges affecting Cast Speed
  src/Modules/ModParser.lua
Labels: bug

#4255 Apply global limit to Expansive Might notable
  src/Modules/ModParser.lua
Labels: bug

#4249 Fix Dancing Duo Cyclone dealing twice as much damage as it should be
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: accuracy

#4247 Fix blastchain mine not applying less damage to all gems
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: accuracy

#4279 Add Support for Temporal Rift CDR buff Alt Quality
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#4226 Move columns vertically when screen width is too low
  src/Classes/ConfigTab.lua
Labels: user-interface

#4169 Add support for showing which lines are supported on skills
  src/Classes/GemSelectControl.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/StatDescriber.lua
Labels: user-interface
