Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2022-12, with the labels that each got.

#5182 fixes non-curse hex skills treated as curse skills #5170
  src/Modules/CalcActiveSkill.lua
Labels: bug:behaviour

#5181 Fix inconsistent display of additional quality and gem levels in skill group tooltip
  src/Classes/SkillsTab.lua
Labels: user-interface

#5193 Add support for Hex Master
  src/Modules/ModParser.lua
Labels: enhancement

#5191 fix typo in config tab
  src/Modules/ConfigOptions.lua
Labels: user-interface

#5168 Glorious Madness poison chance mod
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5184 Update existing uniques for 3.20
  src/Classes/ItemDBControl.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
Labels: bug:accuracy

#5079 dontUseCache --> noCache
  src/Data/Global.lua
  src/Modules/CalcPerform.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: documentation, technical

#5147 fix spelling/punctuation
  CONTRIBUTING.md
  src/Classes/Item.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRateLimiter.lua
  src/Classes/TradeQueryRequests.lua
Labels: documentation

#5186 Fix conversion and charges being negative
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#5189 untying chill from frozen PathOfBuildingCommunity/PathOfBuilding#4144
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#5149 Fix rare templates not getting implicit mod tags
  src/Modules/Main.lua
Labels: bug:calculation

#5159 Fix "no reservation" mods affecting cost of blessings.
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5192 Fixes weapon range on weapons not counting towards cyclone aoe
  src/Classes/Item.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#5204 Fix: crash on crafting certain quirky items
  src/Classes/Item.lua
Labels: crash

#5210 Fix: Fetching Search Query via HTML is no longer allowed
  src/Classes/TradeQueryRequests.lua
Labels: bug

#5205 Fix: Weighted Search Category fix Jewels
  src/Classes/TradeQueryGenerator.lua
Labels: bug

#5217 Fix PobTrader HTML parsing for search queries
  src/Classes/TradeQueryRequests.lua
Labels: bug:behaviour

#4865 Passive count multipliers preview on nodes
  src/Classes/PassiveSpec.lua
  src/Modules/CalcSetup.lua
Labels: bug

#5211 Fix jewel implict button crashing
  src/Classes/ItemsTab.lua
Labels: crash

#5219 Fix: Over-write URL league name to use League Dropdown Selection
  src/Classes/TradeQueryRequests.lua
Labels: technical

#5100 Update affix limit for corrupted abyss jewels.
  src/Classes/Item.lua
Labels: bug:behaviour

#5222 Fix UI spacing on Items tab
  src/Classes/ItemsTab.lua
Labels: user-interface

#5225 Correctly apply elemental hits area radius mod
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#5224 Fix: make URL update to league selection
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
Labels: bug:behaviour

#5213 Fix Item Corruptor having empty space
  src/Classes/ItemsTab.lua
Labels: bug

#4733 Fix: Icenova interaction with GreaterSpellEcho and AwakenedSpellecho on Casting on Frostbolt
  src/Data/Skills/other.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/other.txt
  src/Export/Skills/sup_int.txt
Labels: bug:behaviour

#5226 Feat: update Data/QueryMods.lua for Finding Best Items via Trader
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: enhancement

#5165 Fix shav's revelation removing life recharge.
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug:behaviour

#5199 Display resource costs per second
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#5121 Implement 'Your Blessing Skills are Disabled' for Essence Worm
  src/Data/Uniques/ring.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5216 Add spectre Deadly Tarantula
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/act_dex.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#4875 fix bleed and ignite critical strike proportions to be based on how many applications you can apply during the duration
  src/Modules/CalcOffence.lua
Labels: enhancement

#5212 Implement Seismic / Lightning Spire Trap DPS
  src/Classes/CalcsTab.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5196 Max hit improvement
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: enhancement

#5120 Implement ring reflection from Kalandra's Touch.
  spec/System/TestItemMods_spec.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5201 Add Armour Cruncher Spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#5209 Add max calculcated fuses for Expl Arrow to calcs
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#5203 Added Mod Tooltip
  src/Classes/ItemsTab.lua
Labels: enhancement

#5202 Convert all ailment effect to assume enemy and self behave multiplicativly
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/other.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: technical

#5197 Add support for several curse mods
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5172 Relabel "Total DPS" to "Hit DPS"
  src/Classes/SkillsTab.lua
  src/Modules/Build.lua
  src/Modules/Data.lua
Labels: user-interface

#5171 Add button to go to privacy settings
  src/Classes/ImportTab.lua
Labels: user-interface

#5185 New uniques 3.20
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Uniques/Special/New.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5049 Calculate maximum sustainable trauma stacks
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5016 Automatically apply Energy Blade buff
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5009 Fix Skill Costs
  src/Classes/ModList.lua
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#4975 Fix influence modifers not behaving correctly and rune daggers missing rune dagger tag.
  src/Classes/Item.lua
  src/Data/Bases/dagger.lua
  src/Export/Bases/dagger.txt
  src/Modules/Data.lua
Labels: bug

#4966 Fix arcanist brand giving brand skill flag to gems breaking stuff.
  src/Modules/CalcOffence.lua
Labels: bug, crash

#5230 Fix dangling enemy radius config
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
Labels: technical

#5095 Implement "Quicksilver Flasks you Use also apply to nearby Allies" mod on Victario's Flight
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5089 Fix dagger mastery and radius jewels applying to masteries.
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#4635 Fix dps comparison not working correctly when using the saviour and using overrides
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
Labels: bug

#5158 Fix Varunastra not working with Nightblade support
  spec/System/TestItemMods_spec.lua
  src/Classes/ModStore.lua
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#4792 Add support for low tolerance
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5234 Update pledge of hands and atzri's disfavour sources
  src/Data/Uniques/axe.lua
  src/Data/Uniques/staff.lua
Labels: bug:accuracy

#4952 Update Unqiue wording differences post launch and other changes.
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/Special/race.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4915 Remove overkill damage and fix some bugs in eHP
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/Data.lua
Labels: enhancement, bug:calculation

#5238 Update Grants wording change on uniuqes and support
  src/Data/Uniques/Special/race.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#3088 Add Reaper's Consume buff
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#4653 Fix Absolution spell hit counted multiple times in the Total DPS
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#5237 Fix spelling errors
  spec/System/TestItemMods_spec.lua
  src/Classes/ModStore.lua
  src/Export/spec.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: documentation

#5078 Fix parsing for some pobb.in links
  src/Modules/BuildSiteTools.lua
Labels: bug

#5231 Fix typo breaking tests
  spec/System/TestItemMods_spec.lua
Labels: technical

#5235 Add Dawnstrider
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#5236 Update flask wording
  src/Data/Uniques/flask.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#4825 Add support for burning ground from Essence of Hysteria
  spec/System/TestItemMods_spec.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5019 Add warnings if skill cost exceeds avilable resource.
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: enhancement

#4648 Add initial support for enemy block chance
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/Common.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#5164 Fix Scorching Ray exposure not applying when using calculate maximum sustainable stages option.
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#4981 Add support for socketed in specific socket color mods found on Dialla's Malefaction and Malachai's Artifice and Doomsower
  spec/System/TestItemMods_spec.lua
  src/Classes/ModStore.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4230 Fix a crash when loading spectres with discontinous levels
  src/Modules/CalcTools.lua
Labels: bug, crash

#5011 Generalise Regeneration Calculations adding full support for degens and breakdowns.
  src/Modules/Build.lua
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5148 Update TradeQuery.lua
  src/Classes/TradeQuery.lua
Labels: documentation, technical

#5083 Add spell check github action
  .github/workflows/spellcheck.yml
Labels: documentation, enhancement, technical

#4614 Add new issue templates and try to implement better tagging.
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/release.yml
Labels: documentation, technical

#5241 Fix changelog.txt
  changelog.txt
Labels: technical

#5260 Fix issue tags not automatically apply for issues
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: technical

#5251 Cost per second fixes for totems and eldritch battery
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#5247 FIX: incorrect warnings when using eb and drop support for per second costs.
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: bug:calculation

#5267 Add Hex Master to Impossible Escape
  src/Modules/Data.lua
Labels: bug:behaviour

#5270 Fix Onslaught Effect nodes on tree not working
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5281 Update all unique flasks to reflect current version
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5280 Add price cap to the trading tool and fix several bugs in it
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
Labels: bug, enhancement

#5298 Fix: Use actual Sweep Radii
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug:accuracy

#5294 Use trap cooldown for mana cost per second
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5303 FIX: add area flag to Minion Instability.
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#5279 Updates to current known variants of new uniques
  src/Data/Skills/other.lua
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement, bug:accuracy

#5324 Add modifiable critical strike chance cap
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5340 Fix an issue where the trade generator wasn't generating a sufficient minimum weight for some builds
  src/Classes/TradeQueryGenerator.lua
Labels: bug

#5343 Fix Import Tab not properly using your session ID
  src/Classes/ImportTab.lua
Labels: bug

#5315 Update Fated End and doom mechanics
  src/Data/Skills/spectre.lua
  src/Data/Uniques/ring.lua
  src/Export/Skills/spectre.txt
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5289 Improve accuracy of mana cost calculations
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5308 Add support for new curse mods without increased effect
  src/Modules/ModParser.lua
Labels: bug:calculation

#5291 Fix crash when using Hand of the Fervent with a life cost
  src/Modules/CalcOffence.lua
Labels: crash

#5309 Implement Explosive Trap DPS
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5307 Fix crash related to base cost mod parsing and overhual resource relating parsing to be more generic
  src/Modules/ModParser.lua
Labels: crash

#5317 Fix fullDPS having signifcantly larger numbers on second pass
  src/Modules/CalcSetup.lua
Labels: bug

#5312 Fix importing characters with barrage support
  src/Modules/Data.lua
Labels: bug

#5344 Fix an issue with headers on some implementations of curl
  src/Classes/TradeQueryRateLimiter.lua
Labels: bug

#5345 Fix spacing issue in portrait mode on the Items tab
  src/Classes/ItemsTab.lua
Labels: user-interface

#5349 Correct max fuse calculation
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5359 Fix energy blade not getting disabled
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#5358 Fix odd edit behavior with protected inputs
  src/Classes/EditControl.lua
Labels: user-interface

#5357 Fix session IDs not saving separately per imported account
  src/Classes/ImportTab.lua
Labels: bug

#5355 Fix for minion mods not being considered for "Find Best" tool
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: bug:behaviour

#5385 Add rotting legion missing zombie mod
  src/Modules/ModParser.lua
Labels: enhancement

#5394 Fix minion specific mod no longer apply to specific minion
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5409 Fix Divergent Cast while Channeling adding "More" damage
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: bug:calculation

#5388 Use default item affix quality rather than 50%
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#5396 Improve item pricer error handling
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeQueryRequests.lua
Labels: enhancement

#5379 Query Options Improvements
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#5410 Fix Rotgut mods
  src/Data/Uniques/flask.lua
Labels: bug:accuracy

#5384 Add support for mutewind pennant warcry mod
  src/Modules/ModParser.lua
Labels: enhancement

#5374 Add support for Phantasmal Reave radius
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#5306 Ensure item base type follows item title for unique items
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/sword.lua
Labels: technical

#5395 Adjusted seismic and spire wave count calculation
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#5398 Add support for Sandstorm Visage crit mod
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5378 Critical cull chance uses hit rate
  src/Modules/CalcOffence.lua
Labels: enhancement

#5296 Support for Frozen Sweep DPS and burst damage
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5372 Feat: add realm support; no support for currency conversion
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
Labels: enhancement

#5415 Fix unarmed sandstorm visage not setting spell crit to zero
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#5414 Add sanctum unique drop locations
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/staff.lua
Labels: bug:accuracy

#5426 Add Original Sin
  src/Data/Uniques/ring.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5425 Update wording on sandstorm visage
  src/Data/Uniques/helmet.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5423 Fix relic uniques mod parsing changing
  src/Classes/Item.lua
Labels: technical

#5421 Fix sort by full dps not working on anoints and appearing in other locations
  src/Classes/ItemDBControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/NotableDBControl.lua
Labels: bug

#5420 Remove duplicate bleed / poison config option
  src/Modules/ConfigOptions.lua
Labels: user-interface

#5407 +Flask effect works with silver flask
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#5431 Clarified instructions for adding EmmyLua to VSCode
  CONTRIBUTING.md
Labels: documentation

#5434 Implement profiler toggling on pause
  CONTRIBUTING.md
  src/Launch.lua
  src/Modules/Common.lua
Labels: technical

#5439 Fix profiler crashing
  src/Launch.lua
  src/Modules/Common.lua
Labels: crash, technical

#5442 Fix kalandra's touch not working
  spec/System/TestItemMods_spec.lua
  src/Modules/CalcSetup.lua
Labels: bug

#5447 Remove legacy Crystalised Omniscience that no longer exists
  src/Data/Uniques/amulet.lua
Labels: bug:accuracy

#5446 FIX: exerts applying to triggered skills
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#5458 Fix more than 100% reduced resistances causing negative res to turn postive.
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5445 Fix Implicit mods on Kalandra's Touch not applying.
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#5440 Fix Timeless Jewel tree radius effect not appearing sometimes
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#5461 Fix modCache not being used during startup causing long loading times
  src/Modules/Main.lua
Labels: bug

#5469 Update other Militant Faith cost mod
  src/Classes/TimelessJewelListControl.lua
Labels: bug:accuracy

#5466 Fixed messed up contents for profiler
  CONTRIBUTING.md
Labels: documentation, technical

#5465 Fix singular element modes not working with phys as random element.
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#5481 Add name to elemental damage Grand Spectrum variant
  src/Data/Uniques/jewel.lua
Labels: bug:accuracy

#5479 Fix: Deleting gem level causing a crash
  src/Classes/SkillsTab.lua
Labels: crash

#5478 PoB Trader: fix indentation
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeQueryRequests.lua
Labels: technical

#5424 Apply enemy damage multiplier to max hit taken
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5468 Minor renaming to improve clarity
  src/HeadlessWrapper.lua
  src/Modules/Main.lua
Labels: documentation, technical

#5452 Fix issue parsing certain item bases
  src/Classes/Item.lua
Labels: bug

#5402 add search trade for timeless jewels
  src/Classes/ListControl.lua
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#5392 Doc to explain passes and outputs in CalcOffence
  docs/calcOffence.md
  src/Modules/CalcOffence.lua
Labels: documentation, technical

#5498 Fix Frenzy Charges and Onslaught using one stat for Wilma's Requital
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
Labels: bug:calculation
