Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-03, with the labels that each got.

#5507 Allow Trade to weight by multiple stats
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeStatWeightMultiplierListControl.lua
Labels: enhancement

#5525 Update Trader, Item weight and sorting to use percentage change rather than absolute
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#5734 Minor improvements to trade tool stat weights
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeStatWeightMultiplierListControl.lua
Labels: user-interface

#5709 Fix enemy level getting out of sync due to updating later than expected
  src/Classes/ConfigTab.lua
  src/Classes/ImportTab.lua
  src/Modules/ConfigOptions.lua
Labels: bug

#5694 Move Timeless Jewel TradeIds out of Tree Tab
  src/Classes/TreeTab.lua
  src/Data/LegionTradeIds.lua
  src/Modules/Data.lua
Labels: technical

#5730 Fix Double/Triple Damage calculations
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5733 Fix colour codes and number formating
  src/Modules/Common.lua
Labels: user-interface

#5702 add Help Section for Timeless jewels
  help.txt
Labels: user-interface

#5669 High precision handling for more multipliers
  src/Classes/ModDB.lua
  src/Classes/ModList.lua
  src/Modules/Data.lua
Labels: bug:calculation

#5737 Fix hex codes with number formatting
  src/Modules/Common.lua
Labels: technical, user-interface

#5736 remove byte order mark
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/dagger.lua
  src/Data/Uniques/fishing.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
Labels: technical

#5739 Update pvp multipliers
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#5742 Vaal skill Improvements
  src/Classes/GemSelectControl.lua
  src/Data/Costs.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Scripts/costs.lua
  src/Export/Scripts/skills.lua
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5755 Add missing skilltype tag to minion skill.
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#5760 Vaal lightning strike export
  src/Data/Skills/act_dex.lua
  src/Export/Scripts/skills.lua
Labels: bug:calculation

#5768 Update Tree version to latest upon import
  src/Classes/ImportTab.lua
  src/Classes/PassiveSpec.lua
Labels: bug

#5780 Fix Cremation explosion part skill types
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#5800 Update Vessel of Vinktar to have correct mod values
  src/Data/Uniques/flask.lua
Labels: bug:accuracy

#5801 Improve development setup documentation
  CONTRIBUTING.md
Labels: documentation

#5812 Fix tree conversion
  src/Classes/PassiveSpec.lua
  src/Classes/TreeTab.lua
Labels: bug, technical

#5806 Crucible League: Updated Uniques
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#5803 Added accuracy equal to int mod
  src/Modules/ModParser.lua
Labels: enhancement

#5804 Bugfix: Strength adding to minions at half value
  src/Modules/ModParser.lua
Labels: bug:calculation

#5805 Widowhail unique implementation
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5808 3.21/minion accuracy equals accuracy
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5809 Implement Blood Price, El'Abin's Visage uniques
  src/Data/Uniques/Special/New.lua
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5810 Fix mod parser to support equipped formatting in all cases
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5813 Add support for potential alt primal aegis wording
  src/Modules/ModParser.lua
Labels: enhancement

#5811 Implement Ancestral Vision unique jewel
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5794 Fix fire exposure/action speed mod on Balance of Terror
  src/Modules/ModParser.lua
Labels: bug

#5758 Fix more multipliers on skill damage being incorrectly rounded.
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5792 fix misc spelling issues
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  CHANGELOG.md
  changelog.txt
  src/Classes/DropDownControl.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: documentation

#5746 Fix Ball Lightning Projectile Speed
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:accuracy

#5816 Add shaper influce to entropic devastion
  src/Data/Uniques/gloves.lua
Labels: bug:accuracy

#5815 Fix incorrect profane ground numbers
  src/Modules/ConfigOptions.lua
Labels: bug:calculation

#5753 Colorize and group defensive calc sections
  src/Data/Global.lua
  src/Modules/CalcSections.lua
Labels: user-interface

#5781 Fix brainstorm trees not being saveable
  src/Classes/PassiveSpec.lua
Labels: crash

#5785 Fix crash caused by very long lines without spaces
  src/Modules/Main.lua
Labels: crash

#5774 Block chance reduction
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5797 Fix helmet enchant script
  src/Data/EnchantmentHelmet.lua
  src/Export/Scripts/enchant.lua
Labels: bug

#5793 Improve blade blast using stages
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#5786 Add word wrap to help section and cleanup some lines
  help.txt
  src/Modules/Main.lua
Labels: user-interface

#5776 add fourth unique modifier to Vorana's March
  src/Data/Uniques/Special/Generated.lua
Labels: enhancement

#5814 Initial support for some 3.21 Masteries
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5817 Fix unparsed new unique mods from existing uniques
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement
