Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-04, with the labels that each got.

#4541 Add parsing support for arcane surge and implement non gem arcane surge
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5664 Add support for items that disable other item slots
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5826 Fix eternal damnation
  src/Modules/CalcDefence.lua
Labels: technical, bug:calculation

#5784 Removed duplicate types from ModMaster.lua
  src/Data/ModMaster.lua
  src/Export/Scripts/masters.lua
Labels: bug, technical

#5763 Fix incorrect variable causing sort cache to rebuild everytime
  src/Classes/GemSelectControl.lua
Labels: bug

#5749 Add flask breakdown to Calcs tab
  src/Classes/CalcBreakdownControl.lua
  src/Classes/CalcSectionControl.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5765 Fix skill sets sometimes being deleted after deleting first one
  src/Classes/SkillsTab.lua
Labels: bug

#5681 Do not strip colors when rendering dropdowns
  src/Classes/DropDownControl.lua
Labels: user-interface

#5731 Fix crash caused by missing EnemyMod missing source.
  src/Modules/CalcPerform.lua
Labels: crash

#5577 Fix skillType tags for maximum Ballista Totem mods
  src/Data/SkillStatMap.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5830 3.21: 100% increased Armour and Energy Shield from Equipped Body Armour if equipped...
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5838 Excluding data files from LuaCov test coverage report
  .luacov
Labels: technical

#5836 Correct base for Saemus' gift
  src/Data/Uniques/quiver.lua
Labels: bug:accuracy

#5666 Add support for jewel limits
  src/Classes/PassiveSpec.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5833 [3.21] Support for Spell Suppression and Stun Masteries
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5827 Add support for new passive stats
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5840 Add support for Leech, Claw, and Elemental Masteries
  src/Modules/ModParser.lua
Labels: enhancement

#5837 Set character level to level requirement for allocated passives
  src/Classes/ImportTab.lua
  src/Modules/Build.lua
Labels: enhancement

#5595 Add option to disable autosaving on developer mode
  src/Modules/Build.lua
  src/Modules/Main.lua
Labels: enhancement, technical

#5761 Fix export of skills with different amounts of stats
  src/Data/Skills/other.lua
  src/Export/Scripts/skills.lua
Labels: technical

#5849 Add Stormseeker
  src/Data/Uniques/Special/New.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5850 Add Tainted Pact
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#5845 Remove incorrect tooltip from "Have you Suppressed Recently"
  src/Modules/ConfigOptions.lua
Labels: technical, user-interface

#5844 3.21 Soulbound Unique
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#5843 3.21 - X% more max life if you have at least X life masteries allocated
  src/Classes/PassiveSpec.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5841 Added support for new Adrenaline on changing stance mastery
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5829 Implement life on hit/kill mods in 3.21 tree
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5847 Add support for Claw Mastery
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: technical, bug:calculation

#5825 Add support for Caster Mastery
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5834 Phys, Reservation, Crits masteries
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5842 3.21 attack and lightning masteries
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5846 feat: add some more 3.21 masteries
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5828 3.21 Improve instant leech and support for new masteries
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5756 Fix/improve some EHP / max hit stuff:
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: enhancement

#5712 Hide config options that can be hidden by default behind conditions
  src/Classes/ConfigTab.lua
  src/Classes/TooltipHost.lua
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
Labels: user-interface

#5720 Recolor custom mods like items based on mod being parsed or not
  src/Classes/ConfigTab.lua
  src/Classes/EditControl.lua
  src/HeadlessWrapper.lua
  src/Modules/ConfigOptions.lua
Labels: user-interface

#5858 Fix hex code crash
  src/Modules/Common.lua
Labels: crash, technical

#5796 Fix EB MoM With Bypass for dot pool and max hit
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5859 Fix Damage taken conversion using wrong variable (#5859)
  src/Modules/CalcDefence.lua
Labels: technical, bug:calculation

#5866 use slot concatenation rather than checking specific slot
  src/Modules/CalcDefence.lua
Labels: technical

#5873 Fix mastery choices overlapping when they had multiple lines
  src/Classes/PassiveTree.lua
Labels: bug, user-interface

#5878 Fix gems in the Squire counting multiple times
  src/Modules/CalcSetup.lua
Labels: bug

#5874 Fix Formless Inferno not increasing minion life properly
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#5879 Update assailum to 3.21
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#5772 Update mod values on Betrayal uniques
  src/Data/Uniques/belt.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
Labels: bug:accuracy

#5894 Fix several minion buffs not being calculated correctly
  src/Modules/CalcPerform.lua
Labels: bug

#5908 Fix MoM and Prevented Life loss effect interaction
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5910 Stop life loss prevention occuring on overkill damage resulting in breakpointing behaviour
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5891 Prevent levelup stats from appearing on tooltips
  src/Modules/Build.lua
Labels: bug

#5888 Refactor leech to handle ghost reaver and mines leech
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5823 [3.21] Item modifier parsing for crucible
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Global.lua
  src/Modules/CalcSetup.lua
  src/Modules/ItemTools.lua
Labels: enhancement

#5773 Split calc defence and only run ehp calcs on first pass of full dps
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/Calcs.lua
Labels: enhancement

#5928 Enhance crucible modifier parsing support
  src/Classes/ItemsTab.lua
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement, technical

#5819 Add support for mods conditional on the modifiers of other equipped items
  src/Classes/Item.lua
  src/Classes/ModStore.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5927 Add Bloodnotch
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#5920 Set level mode to manual if default level is above 1
  src/Modules/Build.lua
  src/Modules/Main.lua
Labels: bug, enhancement

#5942 Fix issue where Sceptres and One Handed Maces were considered the same weapon type
  src/Modules/Data.lua
Labels: bug:behaviour

#5941 Fix Reverberation Rod to add back Controlled Destruction
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#5932 Hide the power report on loading a build and unchecking "Show node power"
  src/Classes/PassiveTreeView.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#5931 Add skill names to cost warnings
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: enhancement

#5904 Add support for new Low Life and Full Life Masteries
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5955 Add support for Warcry Mastery
  src/Modules/ModParser.lua
Labels: enhancement

#5956 Remove the auto application of full pool
  src/Modules/CalcPerform.lua
Labels: technical

#5676 Add support for repeat-based modifiers
  src/Classes/ModStore.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_int.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5930 Prompt for saving after altering the passive search string
  src/Classes/PassiveTreeView.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#5618 Fix default state validation for lists and color labels properly
  src/Classes/ConfigTab.lua
Labels: bug

#5954 Add support for Saboteur Ascendancy
  src/Modules/ModParser.lua
Labels: enhancement

#5971 Fix a few uniques for 3.21
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/shield.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5960 Parse the modifier for less damage on subsequent hits on lancing steel
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: technical

#5945 Correct display of max mana leech rate breakdown
  src/Modules/CalcDefence.lua
Labels: user-interface

#5989 Fix crucible item colour
  src/Classes/ImportTab.lua
Labels: user-interface

#5982 Fix + to level of active skill gem mods not working
  src/Classes/GemSelectControl.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5990 Fix crash in the Trader from not having jewel data
  src/Modules/CalcSetup.lua
Labels: bug, crash

#5995 Fix formless inferno, Uul-Netol's Kiss and tulborn
  src/Data/Uniques/axe.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/wand.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy, bug:calculation

#5980 Fix Absolution Enchant Parsing
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5969 Add support for Prismatic Burst
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: enhancement

#5979 Fix Snipe Support + update Assailum
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Uniques/helmet.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6005 Fix low life recoverable calculation
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6022 Fix Prismatic Burst not choosing 1 damage type for DPS
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: bug:calculation

#6014 Add Forged Frostbearer Spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement

#5968 Manaforge implementation
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#6015 Fix active skill mods applying to support gems
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcTools.lua
Labels: bug:behaviour

#5856 Parse chance to get flask charge on crit for flask breakdown
  src/Modules/ModParser.lua
Labels: enhancement

#6021 Fix 'Damage per aura' mastery incorrectly working with some gems
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6018 Add hostName for future garena or qq hosts
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
Labels: enhancement, technical

#5998 Update Tomb Fist to 3.21
  src/Data/Uniques/gloves.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5999 Update and Add 3.21 Uniques
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6030 Fixed incorrect display of leech breakdown
  src/Modules/CalcBreakdown.lua
Labels: user-interface

#6053 fix typo: `serve` -> `severe`
  .github/ISSUE_TEMPLATE/crash_report.yaml
Labels: documentation

#6076 Support for Crucible Mods
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Crucible.lua
  src/Export/statdesc.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6077 Add support for many crucible mods
  src/Classes/Item.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6079 add support for `chance on hit for impales to last an additional hit`
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6082 add basic support for vaal animate weapon
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#6087 Add ability to sort by EHP change for gems
  src/Classes/SkillsTab.lua
Labels: enhancement

#6080 Implement vaal firestorm burning ground and aoe
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#6081 add support for vaal lightning arrow barrage
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#6088 Add support for Vaal Arctic Armour
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcDefence.lua
Labels: enhancement

#6097 Fix the remaining issues on 3.21 unique changes
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/claw.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/wand.lua
  src/Modules/Build.lua
Labels: bug:accuracy

#5714 Add Megalomaniac search to Trader
  src/Classes/Item.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeQueryRequests.lua
  src/Data/QueryMods.lua
  src/Modules/Common.lua
Labels: enhancement

#6099 Support excluding tags in GetModSpawnWeight
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
Labels: technical

#6072 Fix colour codes leaking into formated numbers
  src/Modules/Common.lua
Labels: user-interface

#6101 Fix Juggernaut Unbreakable not working with Iron Reflexes + evasion
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6103 Fix Fanaticism applying to triggered skills
  src/Modules/CalcActiveSkill.lua
Labels: bug:behaviour

#6102 Correct burst damage when using unleash
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6104 Support Uniques with Extra Crucible Mod Tags
  src/Classes/ItemsTab.lua
  src/Modules/Data.lua
Labels: enhancement

#5741 Timelessjewel search improvements
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#5923 Fix Sleight of Hand and other One Handed Weapon + Damage with Ailments passives
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6091 Use nearest keystone for timeless jewel search name
  src/Classes/TreeTab.lua
Labels: enhancement

#6068 Fix Life Mastery item condition to include Enchants
  src/Classes/Item.lua
Labels: bug:behaviour

#6041 Generalise count types
  src/Classes/PassiveSpec.lua
  src/Modules/CalcSetup.lua
Labels: enhancement, technical

#6059 Fix infinite recursion issue with Manaforged arrows
  src/Modules/CalcPerform.lua
Labels: crash

#6057 Fix missing title for tree rename popup causing crash
  src/Classes/PassiveSpecListControl.lua
  src/Classes/SkillSetListControl.lua
Labels: crash

#5947 Recalculate level requirement when extra skillpoints change
  src/Modules/Build.lua
Labels: bug

#6056 Fix discontinuous mod values occuring with range tier slider
  src/Classes/ItemsTab.lua
Labels: user-interface

#6110 Add support for hits against you overwhelm pdr
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6111 Fix trader occasionally ignoring sort selection
  src/Classes/TradeQuery.lua
Labels: bug

#5716 Fix enemy chance to hit not affecting crit effect in defence calculations
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6107 Fix Poison chance for Spells mod on weapons
  src/Classes/Item.lua
Labels: bug:accuracy

#5948 Fix ailment conditionals not being preemptively enabled when an ailment can be applied.
  src/Modules/Calcs.lua
Labels: enhancement

#5766 Add support for regex OR to tree and item search
  src/Classes/ItemDBControl.lua
  src/Classes/NotableDBControl.lua
  src/Classes/PassiveTreeView.lua
  src/Classes/TreeTab.lua
  src/Modules/Common.lua
Labels: enhancement

#6116 Fix alt quality Lacerate and Chance to Bleed Support not affecting Bleed duration
  src/Data/SkillStatMap.lua
Labels: bug:calculation

#6115 Fix Bladestorm Attack part having 100% bleed chance
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug:behaviour

#5735 Add support for essence and crafted mods in trader
  src/Classes/CheckBoxControl.lua
  src/Classes/Item.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Data/Bases/amulet.lua
  src/Data/Bases/axe.lua
  src/Data/Bases/belt.lua
  src/Data/Bases/body.lua
  src/Data/Bases/boots.lua
  src/Data/Bases/bow.lua
  src/Data/Bases/claw.lua
  src/Data/Bases/dagger.lua
  src/Data/Bases/gloves.lua
  src/Data/Bases/helmet.lua
  src/Data/Bases/mace.lua
  src/Data/Bases/quiver.lua
  src/Data/Bases/ring.lua
  src/Data/Bases/shield.lua
  src/Data/Bases/staff.lua
  src/Data/Bases/sword.lua
  src/Data/Bases/wand.lua
  src/Data/QueryMods.lua
  src/Export/Bases/amulet.txt
  src/Export/Bases/axe.txt
  src/Export/Bases/belt.txt
  src/Export/Bases/body.txt
  src/Export/Bases/boots.txt
  src/Export/Bases/bow.txt
  src/Export/Bases/claw.txt
  src/Export/Bases/dagger.txt
  src/Export/Bases/gloves.txt
  src/Export/Bases/helmet.txt
  src/Export/Bases/mace.txt
  src/Export/Bases/quiver.txt
  src/Export/Bases/ring.txt
  src/Export/Bases/shield.txt
  src/Export/Bases/staff.txt
  src/Export/Bases/sword.txt
  src/Export/Bases/wand.txt
  src/Export/Scripts/bases.lua
  src/Modules/Common.lua
Labels: enhancement

#6117 Fix Trader crash when sorting results by some stats
  src/Classes/TradeQueryGenerator.lua
Labels: crash

#6070 Allow custom hex colors for positive and negative breakdown values
  src/Classes/ConfigTab.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveTreeView.lua
  src/Data/Global.lua
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/Main.lua
Labels: user-interface

#5717 Highlight borders for changed config options in config tab
  src/Classes/CheckBoxControl.lua
  src/Classes/ConfigTab.lua
  src/Classes/DropDownControl.lua
  src/Classes/EditControl.lua
  src/Modules/ConfigOptions.lua
Labels: user-interface

#4967 Add support for Supports via Party tab
  help.txt
  src/Classes/ImportTab.lua
  src/Classes/PartyTab.lua
  src/Modules/Build.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Main.lua
  src/Modules/ModTools.lua
Labels: enhancement

#6118 Support trade inversed mods and improve flask mod's behaviour in trader
  src/Classes/TradeQueryGenerator.lua
  src/Data/QueryMods.lua
Labels: enhancement

#6135 Allow Vaal auras to work as well with Sublime Vision
  src/Classes/ModStore.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6130 Fix local gain on hit
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6126 Do not modify env.configInput.conditionLeching directly
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6134 Add support for Master Distiller
  src/Modules/ModParser.lua
Labels: enhancement

#6123 Add support for a lot of Crucible skill mods
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6121 Cap trader stat weight per mod to 100% increased
  src/Classes/TradeQueryGenerator.lua
  src/Modules/Data.lua
Labels: bug

#5696 Add support for on-kill explosions
  src/Classes/ModStore.lua
  src/Classes/SkillsTab.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5897 Add support for enduring flask recovery to be displayed as life/es recovery
  src/Classes/ItemsTab.lua
  src/Modules/Build.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6133 Fix lowlife and full life percent being global (in data)
  src/Classes/ConfigTab.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: technical

#6128 Improve map mod selection UI in the Configuration tab
  src/Data/ModMap.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#6062 Fix multiple Mastery-related crashes
  src/Classes/PassiveSpec.lua
  src/Classes/TreeTab.lua
Labels: crash

#6146 Add support for Vaal Reap
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_int.txt
Labels: enhancement

#5943 Taken from allies before you
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement
