Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-02, with the labels that each got.

#5655 Goddess Unleashed Wording Update, Support enemies x by you have, bleeed/poison on self, used mana in last 10 seconds and distanceRamp updates
  src/Data/Uniques/sword.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement, bug:accuracy

#5650 Fix imported characters missing voidborn uniques
  src/Classes/ImportTab.lua
Labels: bug

#5599 Change foil search to correctly assign foil to voidborn uniques
  src/Classes/Item.lua
Labels: enhancement

#5672 Fix Minion overwhelm mastery missing skillType restriction
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5684 Fix movement speed on Warped Timepiece
  src/Data/Uniques/amulet.lua
Labels: bug:accuracy

#5687 Fixing Missing Variant on replica hyrri's truth
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#5690 Allow setting Blood Charges to 0
  src/Modules/ConfigOptions.lua
Labels: bug

#5659 add support for `extra-en-dict.txt`
  .github/workflows/spellcheck.yml
Labels: enhancement, technical

#5692 Fix Galvanic Field shock effect scaling all damage instead of hits
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#5691 Avoid Collison of weapon melee and fishing rod.
  src/Data/Global.lua
Labels: bug

#5670 Allow for custom mod dps multiplier
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5671 Estimate resistance penalty on import
  src/Classes/ImportTab.lua
  src/Modules/Build.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#5677 Improve eldritch mod sorting and grouping
  src/Classes/ItemsTab.lua
Labels: enhancement, user-interface

#5652 FIX: Ancestral Bond - mirage interaction.
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5656 Make race uniques not show up as obtainable
  src/Classes/ItemDBControl.lua
Labels: enhancement

#5660 More consistent enemy resistance calculations
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#5651 Prevent pathing through class starts for Split Personality
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#5661 Enable searching for Militant Faith devotion modifiers
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#5625 Hide rampage config by default and propery parse rampage sources
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5645 Fix ignite chance display
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug:calculation

#5620 Update boss armour/evasion multipliers and add override fields to config
  src/Data/Bosses.lua
  src/Export/Enemies/Bosses.txt
  src/Export/Scripts/enemies.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#5601 FIX crash on import if abyss jewel socketed in weapon swap weapon
  src/Classes/ItemsTab.lua
Labels: crash

#5600 Fix socket group linking not working on weapon swap and generalize socket group linking code.
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#5574 Fix punctuation error in trauma calculation message
  src/Modules/CalcOffence.lua
Labels: user-interface

#5589 Fix Enabled and FullDPS checkboxes not updating when mouse shortcuts are used
  src/Classes/SkillListControl.lua
Labels: bug

#5569 Fix missing nameSpec for skills granted by items on export
  src/Modules/CalcSetup.lua
Labels: bug, technical

#5567 Fix values of mods on Devouring Diadem
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#5564 Use average elusive value by default instead of max one
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#5557 PoB Trader: rename constants to conform spellchecking
  src/Classes/TradeQuery.lua
Labels: documentation, technical

#5552 PoB Trader: Fix issues caused by sorting mode change
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
Labels: bug, crash

#5326 Fix player specific flask mods applying to actors
  src/Classes/ModStore.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#1006 Support new Adjacent Animosity node
  src/Modules/ModParser.lua
Labels: enhancement

#4467 Fixed a variety of incorrect catalyst scaling
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/ring.lua
Labels: bug:accuracy

#5608 Fix Energy Blade not working with socketed Abyssal jewels
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#5607 Fix energy blade not importing on copy paste
  src/Classes/Item.lua
Labels: bug

#5603 Update pobb.in to default
  src/Modules/BuildSiteTools.lua
Labels: enhancement

#5571 Fix minion data getting in xml of non minion skills
  src/Modules/CalcActiveSkill.lua
Labels: bug, technical

#5566 Add support for more mods on precusor's emblem
  src/Data/Uniques/Special/Generated.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5565 Add support for enemy regen and sanctum x can y.
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#5537 Add support for skill uses
  src/Classes/GemSelectControl.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#4629 Add a Help section
  help.txt
  src/Modules/Main.lua
Labels: documentation, user-interface

#5612 Add new boss skills, auto apply uber changes if set to uber, and update non-uber pen/chaos mix
  src/Classes/ConfigTab.lua
  src/Data/BossSkills.lua
  src/Export/Scripts/bossSkills.lua
  src/Export/bossSkills.txt
  src/Export/spec.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
Labels: enhancement

#5697 Fix crash related to uninitalised srcInstance
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
Labels: crash, technical

#5727 Fix buff effect scaling guard absorption rate
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
Labels: bug:calculation

#5726 Fix local flask duration effecting total amount recovered
  src/Classes/Item.lua
Labels: bug:calculation

#5725 Add support for non-aura cost no life/mana while focused
  src/Modules/ModParser.lua
Labels: enhancement

#5722 Follow Through not applying to poison
  src/Modules/ModParser.lua
Labels: bug:calculation

#5719 Fix group disable not disabling support gems and two part skills not applying support part to linked groups
  src/Modules/CalcSetup.lua
Labels: bug

#5710 Fix Rational Doctrine Not gaining highest mods when using Crystallised Omniscience
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#5705 Fix incorrect serialization of math.huge by writeLuaTable.
  src/Modules/Common.lua
Labels: bug

#5728 Add support for cat's stealth avoid damage
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcDefence.lua
Labels: enhancement
