Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-01, with the labels that each got.

#5514 Fix wither on hit from balance of terror
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#5512 fix missing passive tree assets
  src/TreeData/3_20/PassiveMasteryConnectedButton.png
  src/TreeData/3_20/ascendancy-3.png
  src/TreeData/3_20/ascendancy-background-3.jpg
  src/TreeData/3_20/background-3.png
  src/TreeData/3_20/frame-3.png
  src/TreeData/3_20/group-background-3.png
  src/TreeData/3_20/jewel-3.png
  src/TreeData/3_20/jewel-radius.png
  src/TreeData/3_20/line-3.png
Labels: technical

#5511 PoB Trader: No Session Mode, private leagues support and some more
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
  src/Modules/Common.lua
Labels: enhancement

#5510 PoB Trader: add self adjusting weighted search to prevent result clipping
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryRequests.lua
Labels: enhancement

#5400 Item pricing mod calculation does now use dps instead of damage
  src/Classes/TradeQueryGenerator.lua
Labels: bug

#5500 PoB Trader: add dynamic sorting and fall back from price sorting
  src/Classes/TradeQuery.lua
Labels: enhancement

#5522 Fixing missing radius on timeless jewels and missing variant on millitant faith when adding via double click on results.
  src/Classes/TimelessJewelListControl.lua
Labels: bug

#5524 Fix Atziri's Mirror's source
  src/Data/Uniques/shield.lua
Labels: bug:accuracy

#5519 Support magic utility flask effect for silver flasks
  src/Modules/CalcPerform.lua
Labels: enhancement

#5551 removing per stage multiplier on blood sacrament
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug:calculation

#5550 Fix crash caused by item stuck on cursor when dragging
  src/Classes/ControlHost.lua
Labels: bug, crash

#5547 FIX: whispering ice crash if triggered
  src/Modules/CalcPerform.lua
Labels: crash

#5543 Fix Crash caused by loading shared items too early
  src/Modules/Main.lua
Labels: crash

#5528 Fix spell supression mastery not working with Acrobatics.
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#5559 Fix missing physical skill keyword flag setting
  src/Modules/CalcActiveSkill.lua
Labels: bug:behaviour

#5561 Fix Voltaxic missing shock effect mod
  src/Data/Uniques/bow.lua
Labels: bug:accuracy

#5582 Feat: updated data to 3.20.1b Patch
  src/Data/EnchantmentHelmet.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Data/StatDescriptions/minion_skill_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Data/StatDescriptions/stat_descriptions.lua
Labels: enhancement

#5624 The Iron Mass 3.20.1b Wording Update
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5623 Sandstorm Visage 3.20.1b Wording Update
  src/Data/Uniques/helmet.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#5643 Fix Summon Skeletons enchant not appearing in filtered list
  src/Data/EnchantmentHelmet.lua
  src/Export/Scripts/enchant.lua
Labels: bug

#5639 Add missing "Damage" tag to some golem skills
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#5638 Implement "You can't deal Damage with Skills yourself" mod from Ancestral Bond
  src/Modules/ModParser.lua
Labels: enhancement

#5630 Fix Adrenaline, Her Embrace and Boot Enchant with Wilma's Requital
  src/Data/SkillStatMap.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#5616 Fix missing mana on mindspiral
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#5611 Stop Vaal Smite and Smite auras from stacking
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug:behaviour
