Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-09, with the labels that each got.

#6573 Add missing variant to Tulborn
  src/Data/Uniques/wand.lua
Labels: bug:accuracy

#6576 Fix typo in Death Rush ring
  src/Data/Uniques/ring.lua
Labels: bug:accuracy

#6578 Fix typo in Ashrend body armour
  src/Data/Uniques/body.lua
Labels: bug:accuracy

#6602 Remove logging for missing trigger config
  src/Modules/CalcTriggers.lua
Labels: technical

#6591 Fix Ahuana's Bite 'Chill as though dealing' mod
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6589 move devMode check out of the loop
  src/Modules/Data.lua
Labels: technical

#6586 Fix chance to Inflict ailments breakdown
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6585 Fix Energy Blade alt qualities failing to apply twice when Dual Wielding
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6584 Fix breakdown for skills that grant Ailment Immunities
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug:behaviour

#6583 Sort ModCache when generated
  src/Modules/Common.lua
  src/Modules/Main.lua
Labels: technical

#6572 Limit application of unique item configs.
  src/Modules/CalcTriggers.lua
Labels: crash

#6569 Only check for mods on current variants of unique items
  src/Classes/Item.lua
Labels: bug:behaviour

#6565 Fix mainOutput crash
  src/Modules/Build.lua
Labels: crash

#6560 Fix crash caused by trigger source being disabled.
  src/Modules/CalcTriggers.lua
Labels: crash

#6559 Fix Fresh Meat Support incorrectly granting all minions Adrenaline
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6550 Only add abyssal socket if the item is an energy blade
  src/Classes/ImportTab.lua
Labels: bug:behaviour

#6556 Exclude jewels from all slot equipment checks
  src/Classes/ModStore.lua
Labels: bug:calculation

#6549 Fix some mod ranges being inverted
  src/Classes/ItemsTab.lua
Labels: bug:behaviour

#6562 Optimize loading items, improve startup time
  spec/System/TestItemParse_spec.lua
  src/Classes/Item.lua
  src/Modules/ItemTools.lua
  src/Modules/Main.lua
Labels: enhancement

#6547 Fix missing config causing cast speed to not apply to activation freq of arcanist brand
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6595 Added max level field to the trade query generator
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#6566 Misc FullDPS fixes
  src/Classes/CalcsTab.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
Labels: bug:calculation

#6604 Add legacy tag to Clusters that no longer drop
  src/Data/ClusterJewels.lua
  src/Export/Scripts/cluster.lua
Labels: user-interface

#6598 Limit Node Depth in Heatmap generation
  src/Classes/CalcsTab.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#6231 update enemy crit chance overrides to actuly use flags on the enemy
  src/Modules/ModParser.lua
Labels: technical

#6608 Fix damage flag causing dual wield attack rate penalty to apply to spells
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6610 Fix Ahuana's Bite only increasing Cold damage taken
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6532 Add support for item enchantment comparison on hover
  src/Classes/ItemsTab.lua
Labels: enhancement

#6503 Add support for ignoring weapon swap on character import
  src/Classes/ImportTab.lua
Labels: enhancement

#6371 Add confirmation popup for tree version convert
  src/Classes/TreeTab.lua
Labels: enhancement

#6403 [EXPORT] Fix Spec.Lua and Lowercase Stuff
  .gitignore
  src/Export/Classes/Dat64File.lua
  src/Export/Main.lua
  src/Export/spec.lua
Labels: technical

#6607 Optimize AddMasteryEffectOptionsToNode, improve startup time
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveTree.lua
  src/Launch.lua
  src/Modules/Main.lua
Labels: enhancement

#6615 Disable skill rotation for CWDT
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6614 Fix tooltip stats comparison always showing ehp calcs.
  src/Modules/CalcPerform.lua
  src/Modules/Calcs.lua
Labels: technical

#6613 Update wording on Uul-Netol's Vow
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6621 Don't try to flip ranges that aren't ranges
  src/Classes/ItemsTab.lua
Labels: bug:behaviour

#6622 Improve dev mode startup time
  src/Modules/Data.lua
  src/Modules/Main.lua
Labels: technical

#6619 Importing a new tree spec will create a new tree spec always
  src/Classes/TreeTab.lua
Labels: enhancement

#6617 Fix "Show allocated nodes" button and convert to dropdown
  src/Classes/CalcsTab.lua
  src/Classes/PowerReportListControl.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#6623 Fix Trauma Rate doubling when dual wielding
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6624 Display AoE values as metres
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/sword.lua
  src/Export/Skills/act_int.txt
  src/Modules/Build.lua
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6383 Add support for more map mods
  src/Data/ModMap.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#5959 Initial support for applying link skills
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6228 Stun Duration Improvements
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6139 Link skill improvements
  src/Classes/CalcBreakdownControl.lua
  src/Classes/ModStore.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6280 Add poeplanner.com tree import ability
  src/Classes/PassiveSpec.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#6143 Party tab improvements
  help.txt
  src/Classes/ImportTab.lua
  src/Classes/PartyTab.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
  src/Modules/ModTools.lua
Labels: enhancement

#6339 ux: Add icons to Socket Group skill list based on the item slot
  src/Assets/icon_amulet.png
  src/Assets/icon_belt.png
  src/Assets/icon_body_armour.png
  src/Assets/icon_boots.png
  src/Assets/icon_bow.png
  src/Assets/icon_gloves.png
  src/Assets/icon_helmet.png
  src/Assets/icon_quiver.png
  src/Assets/icon_ring_left.png
  src/Assets/icon_ring_right.png
  src/Assets/icon_shield.png
  src/Assets/icon_shield_swap.png
  src/Assets/icon_weapon.png
  src/Assets/icon_weapon_2.png
  src/Assets/icon_weapon_2_swap.png
  src/Assets/icon_weapon_swap.png
  src/Classes/ListControl.lua
  src/Classes/SkillListControl.lua
Labels: user-interface

#6631 Reduce EstimatePlayerProgress memory usage
  src/Modules/Build.lua
Labels: bug:behaviour

#6632 Fix +1 Socketed Skill gems mods not working
  src/Modules/CalcTools.lua
Labels: bug:calculation

#6635 Add item load coroutine to improve startup time
  src/Classes/ItemDBControl.lua
  src/Modules/Common.lua
  src/Modules/Main.lua
Labels: enhancement

#6639 Show version and branch in error box
  src/Launch.lua
Labels: enhancement

#6570 More accurate icdr suggestions
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6640 Gem level parsing
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: technical

#6637 Move mirage calcs to a new file
  spec/System/TestSkills_spec.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_dex.txt
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcMirages.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
Labels: bug:calculation

#6641 Add a remove account button to ImportTab
  src/Classes/ImportTab.lua
Labels: enhancement

#6642 Fix Party tab export crash for the node storm weaver
  src/Modules/CalcPerform.lua
Labels: technical

#6636 Party tab link skills
  help.txt
  src/Classes/PartyTab.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#6626 Add Profane Map Mod
  src/Data/ModMap.lua
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6646 Change curse effect on self to curse immunity from link skills and fix breakdown
  src/Data/ModCache.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: technical

#6648 Attempt to open help popup at index of current tab
  src/Modules/Main.lua
Labels: enhancement

#6655 Fix imported magic flasks missing their implicits
  src/Classes/Item.lua
Labels: bug, beta

#6657 Fix league and type dropdown in ItemDBControl
  src/Classes/ItemDBControl.lua
Labels: beta

#6660 updates help section
  help.txt
Labels: documentation

#6665 remove triggerDuration from Tawhoa's cooldown calculation
  src/Modules/CalcMirages.lua
Labels: bug:calculation

#6666 Fix magic Two-Toned Boots and add tests
  spec/System/TestItemParse_spec.lua
  src/Classes/Item.lua
Labels: bug:behaviour

#6671 Party Tab, remove unnecessary addition to modDB for player life
  src/Classes/PartyTab.lua
Labels: technical

#6669 Fix Unicode input for PoeCharm
  src/Classes/EditControl.lua
  src/Modules/Main.lua
Labels: enhancement

#6673 Fix negative EHP from progenesis by capping its effect
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6672 Implement movement speed link mastery
  src/Classes/PartyTab.lua
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6644 Add option to disable JIT
  src/Modules/Main.lua
Labels: enhancement

#6651 add support for Maata's Teaching minion crit mod
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6092 Add support for Momentum support
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6670 Prestack mine auras for party tab export
  src/Modules/CalcPerform.lua
Labels: enhancement

#6220 Fix accuracy of skill Mana/Life cost calculations
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6675 PoeCharm detection now checks for global utf8 table
  src/Modules/Main.lua
Labels: technical

#6677 Fix crash when using Saviour Mirages in FullDPS
  src/Modules/CalcMirages.lua
Labels: crash

#6681 Restrict trigger source for CwC using CwC gem tags
  src/Modules/CalcTriggers.lua
Labels: crash

#6689 Update tooltip wording for Magmatic Strikes
  src/Modules/ConfigOptions.lua
Labels: user-interface

#6687 Limit application of curse mods from The Felbog Fang and Fated End to hexes
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6686 Fixes parsing for some mods from the pantheon
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6692 Assume 1 stage by defualt for sigil of power
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6691 Show warcry calc mode for Fist of War
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6693 Fix Fist of War not applying to projectile skill parts
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6694 Disable forced ModCache regen for tests
  src/HeadlessWrapper.lua
  src/Modules/Main.lua
Labels: technical

#6695 Fix Divergent Arcane Cloak
  src/Classes/CalcBreakdownControl.lua
  src/Classes/ModStore.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#6697 Fix Scorching Ray Max Stacks
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6704 Fix Arcane Cloak not affecting max hit
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:behaviour

#6701 Fix rare bug affecting allocating imported cluster nodes
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#6678 Use HitSpeed as source rate if avilable
  src/Modules/CalcTriggers.lua
  src/Modules/Common.lua
Labels: bug:calculation

#6712 Fix Honoured Tattoo of the Tuatara interaction with Stat Conversion jewels
  src/Modules/ModParser.lua
Labels: bug:calculation

#6717 Tooltip showing path allocation difference for intuitive leap allocatable nodes
  src/Classes/PassiveTreeView.lua
Labels: bug:behaviour

#6756 Set placeholder default of 15 for wither on self from map mod
  src/Modules/ConfigOptions.lua
Labels: user-interface

#6752 Fix dps multiplier cfg
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6749 Fix gem display issues with red text when supported
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
Labels: bug:behaviour

#6747 Fix Summon Sentinel of Radiance having 2 burning area skills
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: bug:calculation

#6740 Add Multicastable to IceElementalSpearSummoned
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#6733 Cleanup trigger source permissions
  src/Modules/CalcTriggers.lua
Labels: bug:calculation, bug:behaviour

#6732 Implement Intuitive Link
  src/Classes/ConfigTab.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcTriggers.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6726 Fix potential cache access null deref and check noCache flag
  src/Modules/CalcMirages.lua
Labels: crash

#6725 Fix negative duration values
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6724 Fix parsing for many Explode mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6711 Fix Accuracy rating against enemy mods affecting Accuracy Stat
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6758 Fix Mantra of Flames not counting stacks from Trauma or Voltaxic Burst
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6746 Fix guardian minion levels
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcActiveSkill.lua
Labels: bug:calculation
