Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-08, with the labels that each got.

#6296 Cleanup Doom Blast implementation
  src/Modules/CalcTriggers.lua
Labels: technical

#6317 Force skill groups to display as active based on main skill
  src/Classes/SkillListControl.lua
Labels: user-interface

#6315 Lack of config causing conditional minion aura effect mods to not be applied.
  src/Modules/CalcPerform.lua
Labels: bug

#6311 Add support for generic damage range for Volatility support
  src/Modules/CalcOffence.lua
Labels: technical

#6310 Fix Lancing Steel hit rate calculations
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#6309 Only imply recent minion skill use on non-permanent minions
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcPerform.lua
Labels: enhancement

#6308 Add a warning when exceeding jewel limits
  src/Modules/Build.lua
  src/Modules/CalcSetup.lua
Labels: enhancement

#6306 Fix unreadable values in taken damage filters
  src/Modules/Data.lua
Labels: bug

#6307 Implement flamethrower trap DPS
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#6303 Fix crash on 100% reduced reservation efficiency for relic of the pact
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: crash

#5432 Fix Explosive Arrow Full DPS
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6302 Explosive arrow accuracy improvements
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug:calculation

#6301 Fix Battlemage's Cry and Redblade Banner not working correctly
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6300 Fix crash on unusable weapon swap
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: crash

#6299 Fix multiple instances of 'x stat is increased by overcapped y resistance' stacking
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6297 Fix ailment immune applying 100% ailment avoid
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: technical

#6295 Use highest max shock from any active skill, not from main skill
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6293 Strip unmet tag from imported jewels
  src/Classes/Item.lua
Labels: bug:behaviour

#6292 Fix resistance penalty none not saving
  src/Modules/ConfigOptions.lua
Labels: bug

#6291 Fix Life Mastery not working correctly with Skin of the Loyal
  src/Classes/Item.lua
Labels: bug:behaviour

#6286 Fix spellslinger reservation incorrectly scaling with stages
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6283 Make build search immediate
  src/Modules/BuildList.lua
Labels: enhancement, user-interface

#6278 Prevent stat doubling for radius jewels coming from GrantedPassive mod
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#6276 Improve pvp breakdowns
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
Labels: enhancement

#6270 Fix default uber boss evasion rating
  src/Modules/ConfigOptions.lua
Labels: bug

#6269 Add Ctrl-M to the tree drop down to open manage trees dialog
  help.txt
  src/Classes/TreeTab.lua
Labels: enhancement

#6266 Make Adjacent Animosity work with both attacks and spells
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6264 Fix division by zero in resource recovery calculations
  src/Modules/CalcDefence.lua
Labels: user-interface, bug:calculation

#6261 Fix Flameblast not gaining damage from first stage
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#6247 Add support for cooldown on skills in Black Zenith gloves
  src/Modules/ModParser.lua
Labels: enhancement

#6245 Add proper support for DPS with Scourge Arrow, Divine Ire, Flameblast and Incinerate
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6242 Fix crash sometimes occuring when searching for Timeless Jewel
  src/Classes/TreeTab.lua
Labels: crash

#6246 Add support for crucible min stages/cooldown with Incinerate/Flameblast
  src/Modules/CalcActiveSkill.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6230 Fix defences on normal and magic Two-Toned Boots
  src/Classes/Item.lua
Labels: bug

#6251 Stop crucible aoe mod from applying to any skill.
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6252 Fix crash when hovering over life mastery mod.
  src/Modules/CalcSetup.lua
Labels: crash

#6257 Fix incorrect keystone source on keystones coming from items.
  src/Modules/CalcPerform.lua
Labels: bug

#6249 Don't apply energy shield stun avoidance if EB allocated. Add note regarding stun avoidance calcs.
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug:behaviour

#6225 Add name to top left Timeless Jewel socket
  src/Classes/TreeTab.lua
Labels: bug

#6320 Only apply combustion fire resistance effect with skills that can ignite
  src/Data/Skills/sup_int.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#6312 Add support for changing Tree Version
  src/Classes/TreeTab.lua
Labels: enhancement

#6282 Add clear button to text inputs
  src/Classes/EditControl.lua
  src/Classes/ImportTab.lua
  src/Classes/ItemDBControl.lua
  src/Classes/NotableDBControl.lua
  src/Classes/TreeTab.lua
  src/Modules/BuildList.lua
Labels: enhancement, user-interface

#6326 Remove Minimum Ignite Duration
  src/Modules/CalcOffence.lua
  src/Modules/Data.lua
Labels: bug:accuracy

#6324 Fix a crash relating to accessing gemdata for granted supports
  src/Modules/CalcPerform.lua
Labels: crash, technical

#6322 Add missing skillTypes to Infernal Legion
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#6223 Add Help documentation for Items tab
  help.txt
Labels: documentation, user-interface

#6224 Improve node in radius calculation performance
  src/Classes/PassiveTree.lua
  src/Modules/Data.lua
Labels: enhancement

#6321 Fix Calculation of Ignite/Bleed when at low stacks + show min/max DPS for Ignite/Bleed/Poison
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement, bug:calculation

#6248 Add support for triggered skills with Snipe Support
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6304 Add snipe to trigger rework
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcTriggers.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: technical

#6330 Lancing steel less damage fix
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: technical

#6335 Undo incorrect explosive arrow change
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#6331 Exclude frozen legion from exerts
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#6344 Combustion fix when a non-damaging skill precedes a damaging skill
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6352 Fix Tree conversion stopping you from allocating some tree nodes
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#6346 Fix Crash when using a weapon with a crafted Trigger mod
  src/Modules/CalcTriggers.lua
Labels: crash

#6333 'Wait for max unleash seals' mana cost fix
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6156 Help section improvements
  help.txt
  src/Classes/TextListControl.lua
  src/Modules/ItemTools.lua
  src/Modules/Main.lua
Labels: user-interface

#6389 Add immunity flags to breakdown
  src/Modules/CalcSections.lua
Labels: user-interface

#6388 Fix totem duration mods not applying
  src/Data/SkillStatMap.lua
  src/Modules/ModParser.lua
Labels: user-interface

#6380 Fix DPS on Vaal Flicker when using 2x 1h weapons
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6376 Apply RepeatCount according to their SkillTypes
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#6364 Fix allocation issue on tree conversion
  src/Classes/PassiveSpec.lua
Labels: bug

#6381 Fix lower channel time stat using red text
  src/Modules/Build.lua
  src/Modules/CalcSections.lua
Labels: bug:behaviour

#6400 Fix "Enemies maimed by you take inc damage over time` not in breakdown display
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6401 Fix Pierce and Chain count config not appearing sometimes
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6399 Fix Snipe damage going negative
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6408 Null-check node.finalModList when hovering trees
  src/Modules/CalcSetup.lua
Labels: crash

#6415 Fix Snipe showing DPS values when triggering support skills
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6431 Implement Sadism Support less ailment duration mod
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: enhancement

#6434 Fix incorrect increased usage mod range on Cinderswallow Urn
  src/Data/Uniques/flask.lua
Labels: bug:accuracy

#6426 Add support for new Ancestor uniques
  src/Classes/ItemsTab.lua
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6374 Removing allocated mastery from hover list
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#6393 Fix secondary effect skills being added as supports
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6386 Fix Bleed/Ignite Stack potential issues
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6365 Version dropdown QoL
  src/Classes/TreeTab.lua
Labels: technical

#6443 Add support for Fresh Meat Support
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6445 Add initial support for Guardian Minions
  src/Data/Minions.lua
  src/Data/Skills/other.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/other.txt
  src/Export/spec.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6448 Add a null check for src instance in slot match
  src/Modules/CalcPerform.lua
Labels: crash

#6450 Fix editing tattoo under timeless jewel influence
  src/Classes/TreeTab.lua
Labels: bug:behaviour

#6460 Fix missing source and lack of base mod filtering on resistance conversion
  src/Modules/CalcDefence.lua
Labels: bug:behaviour

#6458 Implement Flamewood Support trigger
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcTriggers.lua
Labels: enhancement

#6471 Fix Chain count box not appearing sometimes
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6473 Fix Crash when using Ruthless Support in a Poison build
  src/Modules/CalcOffence.lua
Labels: crash

#6474 Fix gems not benefitting from Supports sometimes
  src/Data/Global.lua
Labels: bug:calculation

#6475 Fix Trauma duration sometimes using skill duration
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6478 Fix Strength of Blood not working
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6479 Add Support for Guardian's minion RF skill
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
Labels: enhancement

#6446 Fix issue with abyssal sockets on imported Energy Blade
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
Labels: bug, crash

#6489 Fix supported by edge case
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6488 Fix separate totem duration from skill duration
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6490 Fix melding being calculated before res convert
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6487 Fix Flamewood not being affected by totem mods
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/Build.lua
  src/Modules/CalcSections.lua
Labels: bug:calculation

#6502 Fixed an error when searching trade for jewels (Issue #6501)
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#6499 Fix flamewood crash and Ancestral Bond interaction
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcTriggers.lua
Labels: crash

#6504 Fix Spellblade not scaling past level 13
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6505 Fix Flamewood support not scaling with spell and projectile damage
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug:calculation

#6514 Fix Militant Faith jewel not overriding small attribute tattoos
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#6511 Fix full dps not working for skills coming from triggerExtraSkill
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6497 Harden trigger config finder
  src/Modules/CalcTriggers.lua
Labels: technical

#6537 Doom blast ignore tick rounding
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6536 Stop totem duration from using skill duration
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6535 Prevent tawhoa chosen attacks from being exerted.
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6531 Fix kitava's thirst triggered skill condition
  src/Modules/CalcTriggers.lua
Labels: crash

#6525 Fix crash related to boss skill preset
  src/Classes/ConfigTab.lua
Labels: bug

#6510 Fix uuid collision related issues.
  src/Classes/Item.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: bug:calculation

#6521 Fix mirage archer and manaforged interaction
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_dex.txt
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
Labels: bug:behaviour

#6541 Flamewood fix breaking doom blast
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6530 Fix revert to old skill rotation simulation
  src/Modules/CalcTriggers.lua
Labels: bug:calculation
