Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-05, with the labels that each got.

#6182 Fix error on disabling node power mid-generation
  src/Classes/TreeTab.lua
Labels: crash

#6181 Fix local Flask effect mods not working with Mother's Embrace and Umbilicus Immortalis
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6170 Fix crash when searching for Timeless Jewel and using filter nodes
  src/Classes/TreeTab.lua
Labels: crash

#6185 Fix export of tags for Sceptres and Fishing Rods
  src/Data/Bases/dagger.lua
  src/Data/Bases/fishing.lua
  src/Data/Bases/mace.lua
  src/Export/Bases/amulet.txt
  src/Export/Bases/axe.txt
  src/Export/Bases/belt.txt
  src/Export/Bases/body.txt
  src/Export/Bases/boots.txt
  src/Export/Bases/bow.txt
  src/Export/Bases/claw.txt
  src/Export/Bases/dagger.txt
  src/Export/Bases/fishing.txt
  src/Export/Bases/flask.txt
  src/Export/Bases/gloves.txt
  src/Export/Bases/helmet.txt
  src/Export/Bases/jewel.txt
  src/Export/Bases/mace.txt
  src/Export/Bases/quiver.txt
  src/Export/Bases/ring.txt
  src/Export/Bases/shield.txt
  src/Export/Bases/staff.txt
  src/Export/Bases/sword.txt
  src/Export/Bases/wand.txt
  src/Export/Scripts/bases.lua
Labels: bug:accuracy

#6183 Add support for Vaal Absolution + Vaal Domination
  src/Data/Minions.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/minion.txt
Labels: enhancement

#6179 Fix calculation of hybrid mana+life costs
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6174 Round down Ailment Avoid chance value
  src/Modules/CalcDefence.lua
Labels: bug:accuracy

#6186 Fix Trigger skills not gaining cooldown from 'CDR per x Charge' mods
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6164 Fix Ailments breakdown showing crit damage while you have Res Technique
  src/Modules/CalcOffence.lua
Labels: user-interface

#6163 Fix Energy Leech Support not working for Minions
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#6161 Fix Exsanguinate stages scaling Ignite damage with Crucible conversion mod
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug:behaviour

#6157 Fix Cospri's Will poison mod not working
  src/Data/Uniques/body.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6155 Fix ItemsTab Display for Betrayal Uniques
  src/Classes/ItemsTab.lua
Labels: user-interface

#6145 Correct handling of Firesong and Stormshroud
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
Labels: bug

#6144 Improve or add support for more "nearby" mods
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6162 Fix Cannot be Blinded interaction with You are Blind keystone
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6192 Fix Ruthless Crucible mods appearing in mod list
  src/Data/Crucible.lua
  src/Export/Scripts/crucible.lua
Labels: bug:behaviour

#6198 fix missing parsing for Freeze As Though Dealing More Damage
  src/Modules/ModParser.lua
Labels: enhancement

#6202 Update "obtaining an oodle extractor" in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: technical

#6199 Fix Supreme Ego taking effect with Blood Magic
  src/Classes/ModStore.lua
Labels: bug:behaviour

#6205 Fix Chain count not appearing on Calcs page
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/spectre.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/spectre.txt
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: user-interface
