Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2023-12, with the labels that each got.

#6879 Fix Widowhail multiplying mods individually, oddly interacting with weapon swaps.
  src/Classes/ItemsTab.lua
  src/Modules/CalcSetup.lua
Labels: bug:calculation

#6878 Implement if corrupted mod condition.
  src/Classes/ModStore.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6859 Resolves lua: Classes/PassiveSpec.lua:237: bad argument #1 to 'pairs' (table expected, got nil)
  src/Classes/PassiveSpec.lua
Labels: crash

#6852 Fix minion trigger skills when minion is triggered
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
  src/Modules/CalcTriggers.lua
Labels: crash, bug:calculation

#6858 Fix timeless jewel devotion filter generation
  src/Classes/TreeTab.lua
Labels: bug

#6844 Remove the normalisation of taken as if over 100%
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6841 Widen filename list
  src/Modules/BuildList.lua
Labels: enhancement, user-interface

#6807 Add support for Sacrifice anomalous quality mod
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6802 Prevent negative damage taken over time
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6801 Fix order of calcs for afflication charges
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6795 Update a few mods in mod parser to make them more consistent with others
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6794 Fix Flamewall added Fire damage Enchant
  src/Modules/ModParser.lua
Labels: bug:calculation

#6793 Fix Slavedriver's Hand Bloodmagic mod not working
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6792 Fix missing gemData on triggeredBy sources if coming from ExtraSupport mods
  src/Modules/CalcSetup.lua
  src/Modules/CalcTriggers.lua
Labels: crash, bug:calculation

#6779 Hit chance applying twice to triggers relying on crits
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#6751 Add support for Shrapnel Ballista's "projectiles can shotgun"
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6836 update some mods which should apply to party to apply
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy, bug:behaviour

#6823 Add support for divergent temporal rift
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: enhancement

#6822 Update stat descriptions export to be more similar to the exporter one
  src/Export/Scripts/statdesc.lua
Labels: enhancement, technical

#6821 Change Exporter runall to add to a list which is consumed per frame
  src/Export/Main.lua
Labels: enhancement, technical

#6818 Fix master surgion
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#6816 Fix crash when opening help sections from build list
  src/Modules/Main.lua
Labels: crash, bug:calculation

#6813 Fix Phantasmal Flameblast AoE values
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:behaviour

#6805 Update against damage over time to apply the modFlag directly
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#6811 Implement wither effect on self
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6824 Apply blue colour to dev branch help sections to highlight them
  src/Modules/Main.lua
Labels: enhancement, bug:accuracy

#6899 Fix fullDPS not working with two part skills
  src/Modules/Calcs.lua
Labels: bug:calculation, bug:behaviour

#6897 3.23 More skills
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Modules/CalcPerform.lua
Labels: enhancement

#6900 Fix extra damage taken mod from bear trap not ending up in enemyDB
  src/Modules/ModParser.lua
Labels: bug:calculation

#6898 Fix rare crash ccaused by forcing active an inactive group containing a trigger setup.
  src/Modules/CalcSetup.lua
Labels: crash

#6893 Add support for new tree nodes
  src/Classes/CalcBreakdownControl.lua
  src/Classes/ModStore.lua
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6882 Support for alternate ascendancies
  src/Classes/PassiveSpec.lua
  src/Classes/PassiveSpecListControl.lua
  src/Classes/PassiveTreeView.lua
  src/Modules/Build.lua
Labels: enhancement

#6803 Split damage taken as from hits and calculate it for damage over time
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug:accuracy, bug:calculation

#6652 Implement basic enemy damage conversion
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6806 Update Boss skills to use conversion rather than hardcoded elemental
  src/Data/BossSkills.lua
  src/Export/Scripts/bossData.lua
Labels: bug:calculation, bug:behaviour

#6834 Add support for enemy resistance config to increase max res
  src/Modules/CalcBreakdown.lua
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6810 Add support for enemy impale and fix some reflect mods
  src/Data/ModMap.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#6905 Add support for new charm assets
  src/Classes/PassiveTree.lua
  src/Classes/PassiveTreeView.lua
Labels: enhancement

#6745 Improve support for minions applying auras
  src/Classes/PartyTab.lua
  src/Data/Minions.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/other.txt
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#6820 Code cleanup
  src/Classes/CheckBoxControl.lua
  src/Classes/DropDownControl.lua
  src/Classes/EditControl.lua
  src/Classes/SkillListControl.lua
  src/Classes/TradeQuery.lua
Labels: technical

#6716 Recursively process ExtraJewelFunc mods
  src/Modules/CalcSetup.lua
Labels: bug:calculation

#6574 Add rudimentary trigger tests
  spec/System/TestTriggers_spec.lua
  src/Classes/SkillsTab.lua
  src/Modules/CalcTriggers.lua
Labels: technical

#6907 Fix combust looking for a source only in the same group.
  src/Modules/CalcTriggers.lua
Labels: technical

#6910 Fix rare incorrect calculations bug when mirages use forced active skills
  src/Modules/CalcMirages.lua
Labels: bug:behaviour

#6915 Fix importing passive tree
  src/Classes/ImportTab.lua
Labels: bug:behaviour

#6916 Fix Phys Damage taken As not contributing to eHP
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6923 Fix Ball Lightning quality stat
  src/Data/Skills/act_int.lua
Labels: bug:accuracy

#6922 Remove dead Divine Ire mods
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
Labels: bug:accuracy

#6919 Fix Tailwind not applying
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#6921 Fix Blade Vortex gaining damage from Unleash
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#6927 Update splitting steel quality impale effect
  src/Data/Skills/act_dex.lua
Labels: bug:calculation

#6931 Fix spell suppression chance not displaying Lucky
  src/Modules/Build.lua
Labels: bug:behaviour

#6932 Fix damage taken as mods not appearing in breakdown
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#6945 Fix Vortex base damage over time values
  src/Data/Skills/act_int.lua
Labels: bug:accuracy

#6944 Fix Evasion ES Mastery
  src/Modules/ModParser.lua
Labels: bug:accuracy

#6178 Add support for search input to Configuration tab
  src/Classes/ConfigTab.lua
Labels: user-interface

#6970 Remove Pastebin as a build export option
  src/Modules/BuildSiteTools.lua
Labels: enhancement

#6956 Add support for importing new ascendancies
  src/Classes/ImportTab.lua
  src/Classes/PassiveSpec.lua
  src/Modules/Build.lua
Labels: enhancement

#6954 Save trade search weights to build xml
  src/Classes/ItemsTab.lua
  src/Classes/TradeQuery.lua
Labels: enhancement

#6969 Add Sin Trek and Legacy of Fury to Utula exclude list
  src/Modules/Data.lua
Labels: bug:calculation

#6983 Adding new uniques, sans "That Which Was Taken", which will need to be generated
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#6992 Fix negative bypass being ignored
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#6995 Fix Crash when opening Timeless Jewel search
  src/Classes/TreeTab.lua
Labels: crash

#6989 Fix crash when hovering over Masteries
  src/Classes/PassiveSpec.lua
Labels: bug

#7008 Change Manastorm config option to not overrun options box
  src/Modules/ConfigOptions.lua
Labels: user-interface

#7002 Fix Ascendant nodes counting towards allocated passive skill total
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#7005 Fix Pyroclast Mine Aura Effect scaling Maximum Added Flat Damage
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/other.txt
Labels: bug:calculation

#7017 Fix Herald of Agony quality not working
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcSetup.lua
Labels: bug:calculation

#7006 Fix projectile count being 1 higher on all skills
  src/Data/SkillStatMap.lua
Labels: bug:calculation

#7011 Fix error when using Trader
  src/Data/QueryMods.lua
Labels: bug:behaviour

#7014 Fix Necromancer Offering charm not working
  src/Modules/ModParser.lua
Labels: bug:calculation

#7018 Fix ES from Tricksters Escape Artist when using Oath of the Maji
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#7016 Add support for new Uniques + fix parsing for changed mod names
  src/Data/ModCache.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7023 move contribs to separate file
  .github/workflows/spellcheck.yml
Labels: technical

#7035 Fix Tinctures when using Micro-Distillery Belt
  src/Data/ModCache.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug

#6984 Add support for many transfigured gems
  src/Data/Gems.lua
  src/Data/Minions.lua
  src/Data/ModTincture.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/glove.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/other.lua
  src/Data/Skills/spectre.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/skills.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/minion.txt
  src/Export/Skills/sup_str.txt
  src/Export/spec.lua
  src/Export/statdesc.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/StatDescriber.lua
Labels: enhancement

#7039 Implement Righteous Fire of Arcane Devotion
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#7041 Update int gem mods lines 1486-3453
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcPerform.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7047 Storm Rain Transfigured gems
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7040 Fix Lord of Drought increasing curse limit
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7038 Fix hidden blade not using main weapon and its supports
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7037 Fix Rigwald's Curse damage conversion with specific claw mods
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7024 Reset ascendancy class before changing base class again
  src/Classes/PassiveSpec.lua
Labels: bug:behaviour

#7032 Make minion instability hitspeed based off the summon speed instead
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
  src/Modules/CalcOffence.lua
Labels: enhancement

#7043 Hacky save fix to not change save format and keep gemId making sense
  src/Classes/SkillsTab.lua
Labels: enhancement

#7048 Add Gems for all Vaal Transfiguration Variants
  src/Modules/Data.lua
Labels: enhancement

#7057 Fix Oath of the Maji applying when gear slot is empty
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7056 Fix Rage not working when using Warlord's Mark
  src/Data/Skills/act_str.lua
  src/Export/Skills/spectre.txt
Labels: bug:behaviour

#7055 Fix Deadly Ailments less hit damage multiplier not working
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: bug:calculation

#7054 Fix Crash when using the Adorned and items with abyssal sockets
  src/Modules/CalcSetup.lua
Labels: crash

#7053 Support Vaal Transfigured Gem imports
  src/Classes/ImportTab.lua
Labels: enhancement

#7042 fix: shako and megalomaniac displaying variants as explicit modifiers
  src/Data/Uniques/Special/Generated.lua
Labels: bug:behaviour

#7050 New save format
  src/Classes/SkillsTab.lua
  src/Data/Gems.lua
  src/Export/Scripts/skills.lua
  src/Modules/Data.lua
Labels: enhancement

#7028 Add support for selecting league for Timeless Jewel search
  src/Classes/TradeQueryRequests.lua
  src/Classes/TreeTab.lua
Labels: enhancement

#7065 Fix "Cast on Frostbolt" config not showing for Ice Nova of Frostbolts
  src/Modules/ConfigOptions.lua
Labels: bug:behaviour

#7072 Fix Lacerate of Haemorrhage "more damage with Bleeding" using increased
  src/Data/SkillStatMap.lua
Labels: bug:calculation

#7075 Fix tooltip for Summon Chaos Golem of the Maelstrom
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Classes/SkillsTab.lua
  src/Modules/Common.lua
  src/Modules/Data.lua
  src/Modules/ItemTools.lua
Labels: user-interface

#7077 F Devouring Diadem using legacy Ailment duration mod
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#7078 Fix Flicker Strike DPS being limited by cooldown
  src/Modules/ConfigOptions.lua
Labels: enhancement, bug:behaviour

#7082 Fix Vaal gems loading incorrect variant after reopening a build
  src/Classes/SkillsTab.lua
  src/Modules/Data.lua
Labels: bug:behaviour

#7084 Fix Pyroclast Mine aura not affecting the damage of other skills
  src/Data/Skills/act_int.lua
Labels: bug:behaviour

#7085 Revert preffered slot for Unseen Strike / Fix skillData nil crash
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7074 Fix catalysts not working correctly on Replica Dragonfang's Flight
  src/Data/Uniques/amulet.lua
Labels: bug:behaviour

#7086 Fix The Adorned not applying to jewels in outer tree sockets
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7087 Fix gem mods on Forbidden Shako not working correctly with Utula's Hunger
  src/Modules/Data.lua
Labels: bug:behaviour

#7093 Fix "damage taken by at least x%" Ailment mods not stacking
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#7094 Fix Frost Blades of Katabasis DoT not being scaled by area damage
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#7095 Fix Blade Blade of Dagger Detonation having a stages box
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: user-interface

#7097 Fix Dual Strike of Ambidexterity not using offhand attack time
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7101 Allow selectively matching variants for GemProperty mods
  src/Modules/CalcSetup.lua
  src/Modules/CalcTools.lua
Labels: bug:behaviour

#7104 Fix Bodyswap of Sacrifice explosion not scaling correctly
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#7109 Fix Oath of the Magi not working for Body Armour slot
  src/Modules/ModParser.lua
Labels: bug:calculation

#7113 Update The Adorned to work in Cluster Jewel sockets
  src/Data/ModCache.lua
  src/Data/Uniques/Special/New.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7114 Fix Lancing Steel less damage multiplier only applying to Hits
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug:calculation

#7116 Fix crash when checking the breakdown for Transfigured Eye of Winter and Infernal Blow
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Modules/CalcPerform.lua
Labels: crash

#7120 Fix occasional crash when loading build on Beta branch
  src/Modules/Data.lua
Labels: crash

#7178 Add support for That Which Was Taken jewel
  src/Data/Uniques/Special/Generated.lua
Labels: enhancement

#7170 Sanitize skills passed to createActiveSkill by copyActiveSkill
  src/Modules/CalcActiveSkill.lua
Labels: bug:calculation

#7168 Fix Crash on Beta branch when using trade search
  src/Classes/TradeQueryRequests.lua
Labels: crash, beta

#7164 Make culling strike mods unscalable
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7142 Fix Ngamahu, Flame's Advance adding Strength to Unique jewels
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7138 Fix boneshatter missing self damage mod
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_str.txt
Labels: bug:calculation

#7132 Fix odd null compare caused by column alighnement on odd viewport sizes.
  src/Classes/ConfigTab.lua
Labels: crash

#7131 Fix Vortex of Projection damage when cast on Frostbolt from increased to more
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug:calculation

#6720 Cap Doom Blast expiration mode and use charge based calcs for skills that ignore tick rate
  src/Modules/Build.lua
  src/Modules/CalcTriggers.lua
  src/Modules/ConfigOptions.lua
Labels: bug:calculation

#7182 ItemCondition fixes. Kalandra's Touch not adding to influenced items multiplier.
  spec/System/TestItemMods_spec.lua
  src/Classes/Item.lua
  src/Classes/ModStore.lua
  src/Data/ModCache.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug:calculation, bug:behaviour

#6830 Sort and cleanup data.lua to make it easier to manage
  src/Modules/Data.lua
Labels: enhancement, technical
