Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-06, with the labels that each got.

#7653 Fix Abyss jewels not working in weapon swap
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7652 Use less damage mod for Elemancer instead of resistance overrides
  src/Modules/ModParser.lua
Labels: bug:calculation

#7636 Fix manaforged trigger rate calculations
  src/Modules/CalcOffence.lua
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7634 Fix kalandra's touch implicits and mult interactions
  src/Modules/CalcSetup.lua
Labels: bug:behaviour

#7632 Implement Call to Arms gem
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcTriggers.lua
Labels: enhancement

#7631 Fix spellsinger triggered skill trigger rate not being capped by spellslinger cooldown
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7628 Fix Forbidden Flesh&Flame (Duellist) Impact doesn't update required class.
  src/Data/Uniques/Special/Generated.lua
Labels: bug:behaviour

#7633 Fix Tree Management Keyboard Shortcut #7406
  help.txt
  src/Classes/TreeTab.lua
Labels: user-interface

#7617 Fix breakdown crash when using Crit Chance Perandus Pact
  src/Modules/ModParser.lua
Labels: crash

#7611 Fix Ngamahu, Flame's Advance working correctly with Timeless jewels
  src/Modules/ModParser.lua
Labels: bug:calculation

#7599 Update Mutewind Pennant Shield
  src/Data/Uniques/shield.lua
Labels: bug:accuracy

#7597 Split Player and Minion Info lines if they are too long
  src/Modules/Build.lua
Labels: user-interface

#7596 Fix Stance Cooldown mastery affecting attack speed
  src/Modules/ModParser.lua
Labels: bug:calculation

#7595 Show Trap Cooldown for Trap Supported Spell in Black Zenith
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7637 Use duration as pseudo cooldown for shattershard
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7572 Fix error when toggling 'Include Enchants' checkbox in trader
  src/Classes/TradeQuery.lua
Labels: crash

#7566 Support Cold Snap more chill effect quality
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#7565 Fix timeless jewel trade league url
  src/Classes/TreeTab.lua
Labels: bug:behaviour

#7561 Fix manage trees in tree compare dropdown
  src/Classes/TreeTab.lua
Labels: bug:behaviour

#7559 Move "Insane" config to skills section
  src/Modules/ConfigOptions.lua
Labels: user-interface

#7552 Fix exclude anoint mod lines for item cond match
  src/Modules/Data.lua
Labels: bug:calculation

#7551 Fix remove redundant cacheSkillUUID calls
  src/Modules/CalcMirages.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
Labels: technical

#7550 Fix crash caused by Call to Arms conversion
  src/Classes/PassiveSpec.lua
Labels: crash

#7549 Fix faulty uuid calculation causing cache miss
  src/Modules/CalcSetup.lua
Labels: crash

#7531 Fix tawhoa not showing trigger rate on calcs page
  src/Modules/CalcMirages.lua
Labels: bug:calculation

#7492 Redesigned the Import Chararacter menu to improve readability
  src/Classes/DropDownControl.lua
  src/Classes/ImportTab.lua
Labels: user-interface

#7532 Implement wisps support
  spec/System/TestSkills_spec.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/Build.lua
  src/Modules/CalcMirages.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7656 Fix crash caused by 7551 missing from 7637
  src/Modules/CalcTriggers.lua
Labels: crash, technical

#7558 Implement Automation support/skill
  spec/System/TestTriggers_spec.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcTriggers.lua
Labels: enhancement

#7620 Fix "Deal 10% more Chaos Damage to enemies which have Energy Shield" chaos mastery should be limited to hits and ailments #7582
  src/Modules/ModParser.lua
Labels: bug:calculation
