Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-10, with the labels that each got.

#8335 Add name of item causing requirements warning to warning message
  src/Modules/Build.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#8337 Move build display stats to its own file
  src/Modules/Build.lua
  src/Modules/BuildDisplayStats.lua
Labels: technical

#8317 Fix abyss socket items with no selectableSocketCount (eg Wraithlord)
  src/Classes/Item.lua
Labels: bug: behaviour

#8318 Default "Enemy Damage Type" to "Average"
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#7568 Improve EHP overkill approximation, especially for MoM
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#8307 Hollow Palm Technique proper Dual Wielding
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#8303 Vengeful Cry Improvements
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour
