Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-11, with the labels that each got.

#8362 Fix Warden Import Colour
  src/Classes/ImportTab.lua
Labels: user-interface

#8353 Fix special characters in set name causing crash
  src/Modules/Build.lua
Labels: crash

#8331 Fixed Off hand detection regarding Necromantic Aegis
  src/Modules/CalcPerform.lua
Labels: bug: calculation

#8330 Fix Herald of Ash overkill damage incorrectly scaling with global damage increases
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8327 Fix broken tests after changing default boss preset
  spec/System/TestDefence_spec.lua
  spec/System/TestSkills_spec.lua
Labels: technical

#8324 Fix blasphemy auras triggering mana cost warning
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: user-interface

#8323 Fix kalandra's touch skipping mods
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#8320 Fix Rupture sometimes applying multiple times
  src/Data/Skills/sup_dex.lua
  src/Export/Skills/sup_dex.txt
Labels: bug: behaviour

#8366 Add discriminator check to account import
  src/Classes/ImportTab.lua
Labels: enhancement

#8368 Chore: cspell-action: bump to v6.9.0
  .github/workflows/spellcheck.yml
Labels: technical
