Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-09, with the labels that each got.

#8286 Fix The Taming affecting Elemental ground DoTs
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8281 Fix Frost Blades of Katabasis DoT not scaling with Tinctures and Multistrike
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/Build.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#6873 Change controls to take a packed "rect" instead of x, y, width, height
  src/Classes/BuildListControl.lua
  src/Classes/ButtonControl.lua
  src/Classes/CalcBreakdownControl.lua
  src/Classes/CalcSectionControl.lua
  src/Classes/CalcsTab.lua
  src/Classes/CheckBoxControl.lua
  src/Classes/ConfigSetListControl.lua
  src/Classes/ConfigTab.lua
  src/Classes/Control.lua
  src/Classes/DraggerControl.lua
  src/Classes/DropDownControl.lua
  src/Classes/EditControl.lua
  src/Classes/ExtBuildListControl.lua
  src/Classes/FolderListControl.lua
  src/Classes/GemSelectControl.lua
  src/Classes/ImportTab.lua
  src/Classes/ItemDBControl.lua
  src/Classes/ItemListControl.lua
  src/Classes/ItemSetListControl.lua
  src/Classes/ItemSlotControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/LabelControl.lua
  src/Classes/ListControl.lua
  src/Classes/MinionListControl.lua
  src/Classes/MinionSearchListControl.lua
  src/Classes/NotableDBControl.lua
  src/Classes/NotesTab.lua
  src/Classes/PartyTab.lua
  src/Classes/PassiveMasteryControl.lua
  src/Classes/PassiveSpecListControl.lua
  src/Classes/PathControl.lua
  src/Classes/PopupDialog.lua
  src/Classes/PowerReportListControl.lua
  src/Classes/RectangleOutlineControl.lua
  src/Classes/ResizableEditControl.lua
  src/Classes/ScrollBarControl.lua
  src/Classes/SectionControl.lua
  src/Classes/SharedItemListControl.lua
  src/Classes/SharedItemSetListControl.lua
  src/Classes/SkillListControl.lua
  src/Classes/SkillSetListControl.lua
  src/Classes/SkillsTab.lua
  src/Classes/SliderControl.lua
  src/Classes/TextListControl.lua
  src/Classes/TimelessJewelListControl.lua
  src/Classes/TimelessJewelSocketControl.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TradeStatWeightMultiplierListControl.lua
  src/Classes/TreeTab.lua
  src/Export/Classes/DatListControl.lua
  src/Export/Classes/GGPKSourceListControl.lua
  src/Export/Classes/RowListControl.lua
  src/Export/Classes/ScriptListControl.lua
  src/Export/Classes/SpecColListControl.lua
  src/Export/Main.lua
  src/Modules/Build.lua
  src/Modules/BuildList.lua
  src/Modules/Main.lua
Labels: enhancement, technical

#8306 Fix Cooldown breakdown showing overrides for other skills (eg flicker)
  src/Classes/ModDB.lua
Labels: bug: accuracy

#8305 Allow zero enemy armour in config and fix negative enemy damage
  src/Modules/ConfigOptions.lua
Labels: user-interface

#8304 Fix Dual Strike of Ambidexterity and Cleave of Rage
  src/Modules/CalcActiveSkill.lua
Labels: bug: behaviour

#8294 Remove non-existant stat from Cadigan's Crown
  src/Data/Uniques/helmet.lua
Labels: bug: accuracy

#8290 fix Ghost Reaver and Brutal Fervour Interaction
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8287 Add Ctrl+Alt+c error popup
  src/Classes/Item.lua
Labels: enhancement

#8283 Fix 3.1 xp multiplier calc for levels 95-99
  src/Modules/Build.lua
Labels: bug: calculation

#8278 Fix Trade Query Stat Weight Crash
  src/Classes/TradeQuery.lua
Labels: crash

#8272 Shock and scorch fixes
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#8247 Fix numerous fullDPS tooltip issues
  src/Classes/CalcsTab.lua
  src/Classes/GemSelectControl.lua
  src/Classes/ItemDBControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/NotableDBControl.lua
  src/Classes/PassiveTreeView.lua
  src/Classes/SkillsTab.lua
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
  src/Classes/TreeTab.lua
  src/Data/Global.lua
  src/Modules/Build.lua
  src/Modules/Calcs.lua
Labels: bug: accuracy

#8229 Update rare templates
  src/Data/Rares.lua
  src/Export/Bases/Rares.txt
  src/Export/Scripts/bases.lua
Labels: enhancement

#8314 Fix PartyTab Crash with thresholds
  src/Modules/ModTools.lua
Labels: crash
