Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-01, with the labels that each got.

#7188 Stop adding brand skill flags to skills triggered by arcanist brand
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7126 Update active skill checks to compare by base gem where appropriate
  src/Classes/ConfigTab.lua
  src/Classes/ModStore.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/minion.txt
  src/Modules/CalcTools.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7137 Only apply dual wield penatly for on weapon triggers requiring attack sources
  src/Modules/CalcTriggers.lua
Labels: bug:behaviour

#7135 Spectre Affliction Support Enhance
  src/Classes/CalcBreakdownControl.lua
  src/Classes/MinionListControl.lua
  src/Classes/ModStore.lua
  src/Data/Minions.lua
  src/Data/Spectres.lua
  src/Export/Main.lua
  src/Export/Minions/Spectres.txt
  src/Export/Scripts/minions.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#6034 Show accuracy above hit chance when using Precise Technique
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
Labels: user-interface

#7197 Fix mod parsing for Cloistered Notable
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug

#7201 Fix interaction between Chieftain Tasalio node and increased/more fire resistance modifiers
  src/Modules/CalcDefence.lua
Labels: bug:accuracy

#7224 Fix GemProperty mods applying to incorrect gems.
  src/Classes/ConfigTab.lua
  src/Classes/ImportTab.lua
  src/Modules/CalcSetup.lua
  src/Modules/CalcTools.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7225 Fix/maji double armour
  src/Modules/CalcDefence.lua
Labels: bug:behaviour

#7223 Fix crash when skills granting buffs that rely on buffs are disabled.
  src/Modules/CalcPerform.lua
Labels: crash

#7221 Fix allocated nodes on Cluster Jewels when importing character
  src/Classes/ImportTab.lua
  src/Classes/PassiveSpec.lua
Labels: bug

#7233 Round Stun and Block Duration to server ticks
  src/Modules/CalcDefence.lua
Labels: bug:behaviour

#7203 Fixes effective trigger rate not accounting for evasion roll for on crit triggers.
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcTriggers.lua
  src/Modules/ModParser.lua
Labels: bug:calculation, bug:behaviour

#7189 Fix importing of Vaal Impurity Skills and Transfigured Vaal Summon Skeletons
  src/Classes/ImportTab.lua
  src/Data/Gems.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Export/Scripts/skills.lua
  src/Modules/Data.lua
Labels: bug:behaviour

#7217 Add support for filtering on number of sockets and links in Item Trader
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#7240 Filter mods applied by Unnatural Instinct.
  src/Modules/ModParser.lua
Labels: bug:calculation

#7238 Fix ruthless support applying to mirages that only use the skill once.
  src/Modules/CalcMirages.lua
  src/Modules/CalcOffence.lua
Labels: bug:behaviour

#7243 Fix Inspiration Charges not applying to Minion Skills
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#7211 Sort the Calculations Tab breakdown lists by value
  src/Classes/CalcBreakdownControl.lua
Labels: enhancement

#7237 Add config to set the effect of Ruthless Support
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7250 Change issue tracker link in Github issues templates to include closed issues
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: enhancement, technical

#7251 Fix Templar notables Powerful/Frenzied Faith displaying incorrect Id
  src/Export/Scripts/legionPassives.lua
Labels: bug:accuracy

#7186 Fix: Precursor's Emblems curse mod does not work
  src/Modules/CalcPerform.lua
Labels: enhancement, bug:behaviour

#7249 Fix skill effect duration from buffs not applying to Earthquake of Amplification Aftershock
  src/Modules/CalcPerform.lua
Labels: bug:behaviour

#7248 Fix poison duration from charms stacking with Noxious Strike
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7252 Fix enemy Ailment Threshold Calculations
  src/Data/Misc.lua
  src/Export/Scripts/miscdata.lua
  src/Modules/CalcOffence.lua
Labels: technical, bug:calculation

#7254 Fix Law of the Wilds using the wrong minion stats
  src/Data/Minions.lua
  src/Data/SkillStatMap.lua
  src/Export/Minions/Minions.txt
Labels: bug:calculation

#7268 Implement damage fixup as a skill mod
  src/Modules/CalcActiveSkill.lua
Labels: technical

#7255 Add extra wording to clarify 'Check for duplicate' step in Github templates
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: technical

#7253 Fix Minion stats values
  src/Data/Minions.lua
  src/Data/Misc.lua
  src/Data/Spectres.lua
  src/Export/Scripts/minions.lua
  src/Export/Scripts/miscdata.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
Labels: bug:calculation

#7273 Fix base damage from transfigured shield skills not being applied
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7270 Fix Cluster Jewel imports not allocating correctly
  src/Classes/PassiveSpec.lua
  src/Data/ClusterJewels.lua
  src/Export/Scripts/cluster.lua
  src/Export/spec.lua
Labels: bug:behaviour

#7277 Fix alt Blink/Mirror Arrow using wrong minion
  src/Data/Minions.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/minion.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/act_dex.txt
  src/Export/Skills/minion.txt
Labels: bug:behaviour

#7239 Mirage cleanup
  src/Modules/CalcMirages.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: enhancement, technical

#7261 Add support for resetting Search Weights in Item Trader
  src/Classes/TradeQuery.lua
Labels: enhancement

#7278 Fix Vaal Gem import to use new lookup table
  src/Classes/ImportTab.lua
  src/Modules/Data.lua
Labels: crash, technical

#7127 Add new Spectres
  src/Classes/CalcBreakdownControl.lua
  src/Classes/MinionListControl.lua
  src/Classes/ModStore.lua
  src/Data/Minions.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Minions/Spectres.txt
  src/Export/Scripts/minions.lua
  src/Export/Skills/spectre.txt
  src/Export/spec.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTools.lua
  src/Modules/ConfigOptions.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7200 Add support for converting all trees to latest version
  src/Classes/TreeTab.lua
Labels: enhancement

#7234 Fix display in Item Trader when large number of sockets are allocated
  src/Classes/PopupDialog.lua
  src/Classes/TradeQuery.lua
  src/Export/Main.lua
  src/Modules/Main.lua
Labels: bug

#6728 Fix added cooldown and added cast time not working correctly
  src/Data/ModCache.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcTriggers.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#7283 Fix converting Ruthless trees
  src/Classes/TreeTab.lua
Labels: bug

#6707 Fix support gem crosslink issues.
  src/Classes/DropDownControl.lua
  src/Classes/GemSelectControl.lua
  src/Classes/SkillsTab.lua
  src/Modules/CalcSetup.lua
Labels: enhancement, bug:calculation, bug:behaviour

#7296 Fix charge duration not calculating
  src/Modules/CalcPerform.lua
Labels: bug

#7302 Fix crash when hovering attribute requirements
  src/Classes/CalcBreakdownControl.lua
Labels: bug

#7303 Fix sorting for unrelated stats
  src/Classes/CalcBreakdownControl.lua
Labels: user-interface

#7304 Refactor scrollbar input events
  src/Classes/CalcBreakdownControl.lua
  src/Classes/CalcsTab.lua
  src/Classes/ConfigTab.lua
  src/Classes/DropDownControl.lua
  src/Classes/EditControl.lua
  src/Classes/GemSelectControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/ListControl.lua
  src/Classes/PopupDialog.lua
  src/Classes/ScrollBarControl.lua
  src/Classes/SkillsTab.lua
Labels: technical

#7309 Fix crash when using opening wiki for skills granted by items
  src/Classes/SkillListControl.lua
  src/Modules/ItemTools.lua
Labels: bug, crash

#7311 Fix crash when hovering over some breakdowns
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: crash

#7317 Fix crash caused by incorrect calc mode used for manaforged source calc
  src/Modules/CalcSetup.lua
  src/Modules/CalcTriggers.lua
Labels: crash

#7315 Fix bug comparing non-number types in the Calcs tab
  src/Classes/CalcBreakdownControl.lua
Labels: crash

#7313 Fix various item mod interactions with Utula's Hunger
  src/Modules/Data.lua
Labels: bug:behaviour

#7322 Fix: typo "Soultether" in changelogs
  CHANGELOG.md
  changelog.txt
Labels: documentation, technical
