Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-03, with the labels that each got.

#7377 Fix life leech and block missing from current version of Essentia Sanguis
  src/Data/Uniques/claw.lua
Labels: bug:behaviour

#7376 Fix current variant of Lioneye's Glare missing Far Shot
  src/Data/Uniques/bow.lua
Labels: bug:accuracy

#7370 Fix formless inferno not increasing minion life
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#7369 Force main hand for skills used by General's cry mirages
  src/Data/Skills/act_str.lua
Labels: bug:calculation

#7366 Taiwan realm migrated to Hotcool
  src/Classes/ImportTab.lua
Labels: bug:accuracy

#7359 Remove unnecessary usage of slotcfg for energy shield and ward calculations
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#7356 Add a config option for disabling Champion Intimidate effect.
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7355 Disable skill rotation for Cast when Stunned
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7353 Fix Dancing Dervish stats (Life, Damage and Damage reduction)
  src/Data/Minions.lua
  src/Data/Skills/other.lua
  src/Export/Minions/Minions.txt
  src/Export/Skills/other.txt
Labels: bug:calculation

#7344 Fix scrolling on ItemTrader
  src/Classes/TradeQuery.lua
Labels: technical, bug:behaviour

#7341 Fix Utula's Hunger interaction with multiple uniques
  src/Modules/Data.lua
Labels: bug:behaviour

#7338 Fix crash when opening Item Trader after selecting a different league
  src/Classes/TradeQuery.lua
Labels: bug, crash

#7336 Fix sorting of ailment breakdown sections
  src/Classes/CalcBreakdownControl.lua
Labels: bug:behaviour

#7352 Fix summon skeletons duration
  src/Data/ModCache.lua
  src/Modules/CalcActiveSkill.lua
  src/Modules/ModParser.lua
Labels: bug:calculation

#7335 Adjust Totem Labels and Duration in Calc Sections
  src/Modules/CalcSections.lua
Labels: technical

#7327 Add support for Everlasting Sacrifice
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7375 Minor improvements to DPS display for mirages
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/Calcs.lua
Labels: user-interface, bug:calculation

#7390 Fix snipe precalculation using wrong calc mode
  src/Modules/CalcTriggers.lua
Labels: crash

#7387 Fix Armour and ES breakdowns for "100% increased..." Armour and ES Mastery
  src/Modules/CalcDefence.lua
Labels: bug:calculation

#7391 Fix Snipe doing damage when in trigger mode
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7384 Implement explosive trap +-30% base tertiary radius, fix overlap chance for transfigured version
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/CalcOffence.lua
Labels: bug:calculation

#7383 FIX: Nightgrip missing "taken" keyword in description
  src/Data/Uniques/gloves.lua
Labels: bug:accuracy

#7396 [Necropolis] Initial unique support
  src/Data/ModCache.lua
  src/Data/Uniques/Special/Generated.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7401 Reduce clutter in Import character selection list
  src/Classes/ImportTab.lua
Labels: user-interface

#7404 Update existing skill gems from 3.24 patch notes
  src/Data/Minions.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/minion.lua
  src/Data/Skills/sup_int.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_int.txt
  src/Modules/CalcOffence.lua
Labels: enhancement

#7408 Update Items with 3.24 Changes
  src/Data/Bases/flask.lua
  src/Data/ModCache.lua
  src/Data/ModFlask.lua
  src/Data/ModJewel.lua
  src/Data/ModMaster.lua
  src/Data/ModVeiled.lua
  src/Data/TattooPassives.lua
  src/Data/Uniques/flask.lua
Labels: enhancement

#7418 Stop sorting unique item list when added item isn't equipped
  src/Classes/ItemListControl.lua
Labels: bug

#7426 Fix Replica Replica Hyrri's Ire not appearing in unique list
  src/Data/Uniques/body.lua
Labels: bug:accuracy

#7423 Fix Devouring Diadem missing Mana Reservation mod
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#7425 Fix Wraithlord not giving global Minion levels
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#7427 Fix Wither stacks not working with Unholy Might
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7442 Add buttons to filter Active and Support gems in Skills tab
  src/Classes/GemSelectControl.lua
Labels: enhancement

#7464 Add config option to bypass Vigilant Strike cooldown
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7470 Add Grace of the Goddess unique wand
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#7482 Update to SimpleGraphic v2.0.1
  runtime/SimpleGraphic.dll
  runtime/SimpleGraphic/SimpleGraphic.log
  runtime/lcurl.dll
  runtime/lua51.dll
  runtime/lzip.dll
Labels: user-interface

#7459 Fix nil sortCache error in SkillsTab in dev
  src/Classes/GemSelectControl.lua
Labels: technical

#7476 Adding popup to specify new user path if default one fails
  src/Modules/Main.lua
Labels: crash

#7458 Fix calc mode issues for triggers and mirages
  src/Classes/GemSelectControl.lua
  src/Data/Global.lua
  src/Data/Skills/sup_str.lua
  src/Modules/Build.lua
  src/Modules/CalcMirages.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
  src/Modules/Common.lua
Labels: crash

#7511 Essence Exports
  src/Export/spec.lua
Labels: technical

#7513 Fix Replica Hyrri's Ire granting Dex instead of Int
  src/Data/Uniques/body.lua
Labels: bug:accuracy

#7515 Drop Level Min & Max became a DropLevel list
  src/Export/spec.lua
Labels: technical

#7505 Fix settings not saving for certain users
  src/Modules/Main.lua
Labels: bug

#7506 Fix heatmap colouring when switching power stat
  src/Classes/CalcsTab.lua
Labels: technical

#7467 Added config variable to control the missing Unreserved Mana% used in Manabond's added base Lightning damage calculation.
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7455 Fix Tree export to PoE Planner
  src/Classes/PassiveSpec.lua
Labels: bug:accuracy

#7454 Added config toggle to add Arcane Cloak's mana spend to the value provided in the manaSpentRecently modifier.
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7517 Disallow delve mods on cluster jewels
  src/Classes/ItemsTab.lua
Labels: bug

#7518 Add support for Necropolis mods in Item Crafter
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/ModCache.lua
  src/Data/ModNecropolis.lua
  src/Export/Scripts/mods.lua
  src/Modules/CalcDefence.lua
  src/Modules/Data.lua
  src/Modules/ModParser.lua
Labels: enhancement
