Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-08, with the labels that each got.

#8048 Fix incorrect skillId for elder staff power charge on crit
  src/Modules/ModParser.lua
Labels: crash

#8074 Check for empty build file on load.
  src/Modules/Build.lua
Labels: enhancement, technical

#8072 Fix issue where PoB did not detect changes when selecting gems via keyboard shortcuts
  src/Classes/SkillsTab.lua
Labels: user-interface

#8062 Fix Ynda's Stand ward conversion mod not taking catalysts into consideration
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#8108 Fix The Light of Meaning adding stats to allocated sockets
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8111 Add variant for post 3.21 Combat Focus
  src/Data/Uniques/jewel.lua
Labels: bug: accuracy

#8112 Update Sap of the Seasons to add new cap
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#8109 Scale Warcry buffs by Warcry Power earlier in Calc
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcPerform.lua
  src/Modules/Data.lua
Labels: bug: calculation

#8113 Fix Rage Effect incorrectly scaling some mods
  src/Data/ModCache.lua
  src/Data/Skills/act_str.lua
  src/Data/Uniques/sword.lua
  src/Export/Skills/act_str.txt
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8102 Fix Arcane Surge effect per Summoned Totem mod not working
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8087 Fix full dps visual bug on gem dropdown
  src/Modules/Build.lua
Labels: user-interface

#8084 Fix Ynda's Stand not working correctly with Trickster's Escape Artist
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#8083 Fix Ward rounding final value incorrectly
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#8082 Fix Divine Blessing not removing reservation from skill
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8081 Fix Maata's Teaching using wrong crit chance range
  src/Data/Uniques/mace.lua
Labels: bug: accuracy

#8080 Fix incorrect names for Timeless Jewel nodes
  src/Data/TimelessJewelData/LegionPassives.lua
  src/Export/Scripts/legionPassives.lua
Labels: bug: accuracy

#8078 Add support for Tincture mods
  src/Modules/ModParser.lua
Labels: enhancement

#8077 Nicer check-empty-build popup
  src/Modules/Build.lua
Labels: enhancement, technical

#8066 Fix infinitely nested XML stored as importLink
  src/Classes/ImportTab.lua
Labels: bug

#8040 Fix Overexertion not applying to skills linked with Generals Cry
  src/Modules/CalcMirages.lua
Labels: bug: behaviour

#8121 Fix rare case with gain on suppression with no chance to mitigate damage (eg 100% suppress chance)
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#8130 Add support for some warcry power modifiers
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8044 Color mastery differences blue when comparing trees
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#8173 Fix warcry options are not shown in all configurations.
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#8171 Fix Tattoos being removed from list when using Remove All Tattoos button
  src/Classes/TreeTab.lua
Labels: bug: behaviour

#8166 Fixes Minions with Endurance Charges still gaining resists.
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8161 Explain Exporting Timeless jewels in RELEASE.md and dev help txt
  RELEASE.md
  help.txt
Labels: documentation

#8145 Improve Rage Calcs tab breakdown
  src/Data/ModCache.lua
  src/Data/Skills/act_str.lua
  src/Data/Uniques/gloves.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: user-interface

#8141 Fix broken base types on some items
  src/Data/Rares.lua
  src/Data/Uniques/jewel.lua
Labels: bug: accuracy

#8135 Minor improvements to Tinctures and Mana Burn
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8134 Enable Tincture Effects to also apply to Ranged Weapons
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8126 Add Warcry effect mod to calcs tab with breakdown
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: enhancement

#8122 Hide legacy Tattoos from dropdown by default
  src/Classes/TreeTab.lua
  src/Data/TattooPassives.lua
  src/Export/Scripts/tattooPassives.lua
Labels: enhancement

#8120 Fix EHP and Maximum Hit taken with negative Unreserved Life
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#8100 Handle account name spaces in import
  src/Classes/ImportTab.lua
Labels: technical

#6814 Enemy damaging ailments
  src/Data/ModCache.lua
  src/Data/ModMap.lua
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8116 Add support for export and importing warcry buffs to the Party Tab
  src/Classes/PartyTab.lua
  src/Modules/CalcPerform.lua
Labels: enhancement

#8129 Fix Rallying Cry damage rounding
  src/Modules/CalcPerform.lua
Labels: bug: calculation

#8092 View Gem level sources in calc sections
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
Labels: enhancement

#8175 Fix Sand Stance "less damage taken" incorrectly applying to DoT
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#8176 Fix Hateforge Rage cost calculation
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#8177 Fix crash when allocating Blood Magic with Manabond
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: crash

#8206 Fix Sublime Vision disabling Mine skills
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8205 Fix Damage while Leeching Life mod not working
  src/Modules/ModParser.lua
Labels: bug: calculation

#8196 Improve breakdown for snipe's damage mods
  src/Modules/CalcTriggers.lua
Labels: user-interface

#8195 Fix Snipe for Assailum not working
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8192 Fix limited processing flag not persisting through recursions causing crash
  src/Modules/CalcMirages.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
Labels: crash

#8275 Add support for Debuffs granted by Glorious Madness
  src/Data/Uniques/boots.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#8267 Minor code changes
  src/Modules/CalcPerform.lua
Labels: technical

#8265 Fix Eldritch Implicit Mod Replacement
  src/Classes/ItemsTab.lua
Labels: bug: behaviour

#8263 Show Curse limit on calcs tab
  src/Modules/CalcSections.lua
Labels: enhancement

#8271 Change default Boss Config from None to Pinnacle
  src/Modules/ConfigOptions.lua
Labels: enhancement

#8258 Add support for modifying affix limits
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8243 Add support for Items Implicits Cannot Be Changed
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8240 Implement settlers trigger enchant
  spec/System/TestTriggers_spec.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcTriggers.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8239 Hide recovery information if recovery is 0 on mana flasks
  src/Classes/ItemsTab.lua
Labels: user-interface

#8237 Fix Bloodscent not making rage eligble.
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8235 Validate mode before saving settings
  src/Modules/Main.lua
Labels: crash, technical

#8233 Mana cost raw not being set to 0 when using lifetap
  src/Modules/CalcOffence.lua
  src/Modules/CalcTriggers.lua
Labels: bug: calculation

#8223 Make runesmith enchants an enchant instead of a craft
  src/Classes/Item.lua
  src/Data/EnchantmentWeapon.lua
  src/Data/ModMaster.lua
  src/Export/Scripts/enchant.lua
  src/Export/Scripts/masters.lua
  src/Export/statdesc.lua
  src/Modules/Data.lua
Labels: bug: accuracy

#8222 Adds parsing for local elemental inc damage
  src/Classes/Item.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8218 Fix "# of warcries used recently" configuration option unavailable.
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#8217 Add Support for many Runecraft Enchants
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8215 Default to last added Tattoo in Tattoo popup
  src/Classes/TreeTab.lua
Labels: enhancement

#8211 Fix invalid skill ids in party tab source
  src/Classes/PartyTab.lua
Labels: crash

#8184 Added ignore mirrored items checkbox to trade query options.
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#8279 Update Affliction Spectre Buffs with 3.25 Changes
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
Labels: bug: accuracy
