Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2024-07, with the labels that each got.

#7660 Fix Curtain Call PoB description does not match with in-game.
  src/Data/Uniques/helmet.lua
Labels: bug:accuracy

#7666 Add platform dropdown option to issue templates
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: technical

#7661 Correct subsection layouting for calcs tab
  src/Classes/CalcSectionControl.lua
Labels: user-interface

#7655 Allow children of PopupDialogs to process input events first
  src/Classes/PopupDialog.lua
Labels: user-interface

#7681 Fix enemy level not updating in sync with player level when in auto mode
  src/Modules/Build.lua
Labels: bug:behaviour

#7677 New Notable Support - Incorporeal
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7676 New Notable - Mixed Munitions
  src/Modules/ModParser.lua
Labels: enhancement

#7683 Add support for inc brand aoe after 50% attached duration mastery
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7675 Disable Tree download if file is missing
  src/Classes/PassiveTree.lua
  src/Modules/Main.lua
Labels: technical

#7674 hide alternate_ascendancies as they are unobtainable but still in tree data
  src/Classes/PassiveTree.lua
Labels: technical, user-interface

#7670 Add support for Impale avoidance in calcs tab
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7669 Add support for unholy might on block staff mastery
  src/Modules/ModParser.lua
Labels: enhancement

#7668 Add support for stun cull mace mastery
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7682 Update bandit rewards and Fellshrine Reward
  src/Modules/Build.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
Labels: bug:calculation

#7685 Fix the stats of "The Dark Seer" unique sceptre
  src/Data/Uniques/mace.lua
Labels: bug:accuracy

#7679 Split Tree sprites data from tree.lua
  RELEASE.md
  fix_ascendancy_positions.py
  src/Classes/PassiveTree.lua
  src/TreeData/3_19/Assets.lua
Labels: enhancement, technical

#7689 Add support for additional strike targets mod & Ancestral Call Support
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7688 Add support for conditional Quantity/Rarity modifiers & Bisco's
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7687 Add support for flat dmg reduction to Projectile Attacks
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7686 Add support for Maim, Hinder, Impale, CB, Silence, Blind, Knockback Immunity
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7477 Adds support for the "%d more recovery if used while on low life" Life flask mod
  src/Classes/ItemsTab.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7509 Make Custom Modifiers input resizable + Add reusable component
  src/Classes/ConfigTab.lua
  src/Classes/DraggerControl.lua
  src/Classes/ResizableEditControl.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7488 Cleaner overlay buttons
  src/Classes/GemSelectControl.lua
Labels: user-interface

#7702 cannibalistic rite Life Cost
  src/Modules/ModParser.lua
Labels: enhancement

#7700 3 25 unique changes
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/sword.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7709 Chance To Ignore Enemy Physical Damage Reduction
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7672 Add support for linking sets through Loadouts
  help.txt
  src/Classes/ItemSetListControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/PassiveSpecListControl.lua
  src/Classes/SkillSetListControl.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#7713 Add parsing for new dead eye far shot notable
  src/Modules/ModParser.lua
Labels: enhancement

#7708 3 25 new uniques
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/wand.lua
Labels: enhancement

#7704 Gladiator rework
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7715 Fix The Apostate not working with Life Mastery
  src/Modules/Data.lua
Labels: bug:behaviour

#7714 Update base Ward recharge delay
  src/Modules/Data.lua
Labels: enhancement

#7718 enhance passive tree search with sticky edges
  src/Classes/PassiveTreeView.lua
Labels: enhancement

#7703 Show total tattoo count when adding tattoos
  src/Classes/TreeTab.lua
Labels: enhancement

#7500 Fix support gems supporting pseudo active parts from gems granted by the same item
  src/Modules/CalcSetup.lua
  src/Modules/CalcTools.lua
  src/Modules/CalcTriggers.lua
Labels: bug:calculation, bug:behaviour

#7630 Fix Ignite Max stack below 2 not displayed in the Ignite calc widget. #7592
  src/Modules/CalcSections.lua
Labels: user-interface

#7345 Add Abyssal Sockets to Item Trader
  src/Classes/TradeQuery.lua
  src/Classes/TradeQueryGenerator.lua
Labels: enhancement

#7346 Add support for removing all Tattoos
  src/Classes/TreeTab.lua
Labels: enhancement

#6827 Move power calcs offence, defence calc to its own func
  src/Classes/CalcsTab.lua
Labels: enhancement, bug:accuracy

#6828 Power calcs cache optimisation
  src/Classes/CalcsTab.lua
Labels: enhancement

#6829 Ordered power calc (tree show node power)
  src/Classes/CalcsTab.lua
Labels: enhancement

#7731 Fix crash caused by invalid impossible escape keystone
  src/Classes/PassiveSpec.lua
Labels: crash

#7723 Fix tree pathing
  src/TreeData/3_25/tree.lua
  src/TreeData/3_25_ruthless/tree.lua
Labels: bug:behaviour

#7736 Fix mod missing from current verison. Move mod line
  src/Data/Uniques/body.lua
Labels: bug:accuracy

#7741 Add missing strength roll to Kaom's Binding
  src/Data/Uniques/belt.lua
Labels: bug:accuracy

#7733 Fix for Determined Survivor Block Chance
  src/Modules/ModParser.lua
Labels: bug:calculation

#7750 Fix cheiftain's damage conversion
  src/Modules/ModParser.lua
Labels: bug:calculation

#7747 Fix Blood Price Unique stats
  src/Data/Uniques/helmet.lua
Labels: bug:calculation

#7738 Fix incorrect modflags for weaponcfg
  src/Modules/CalcDefence.lua
  src/Modules/ModParser.lua
Labels: bug:behaviour

#7745 Implement handling for double exerts mod from berserker ascendancy
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7746 Add support for banner modifiers and valour on tree
  src/Data/Uniques/body.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7753 fix: update wand crit chance and attack speed
  src/Data/Bases/wand.lua
Labels: enhancement

#7730 EHP lucky and unlucky rework
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7725 Update perfect agony keystone
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7724 correct The Light of Meaning crit chance
  src/Data/Uniques/Special/New.lua
Labels: bug:calculation

#7712 Implement support for new anointable nodes
  src/Classes/NotableDBControl.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7696 Retaliation skills
  src/Modules/ModParser.lua
  src/TreeData/3_25/tree.lua
  src/TreeData/3_25_ruthless/tree.lua
Labels: enhancement

#7695 Rage Rework
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7690 Add support for spark maximum hits mode
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#7623 fix(7622): store widowhail multiplier & apply to clones
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
Labels: bug:calculation

#6750 Add support for tornado shot secondary projectiles skill part
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7732 [3.25] Vaal Pact implementation
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7707 Support Warden
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
  src/Modules/CalcDefence.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7735 fixed modifiers to "[Any Damage] with melee skills" not working for DoT
  src/Modules/ModParser.lua
Labels: bug:calculation

#7742 added Ynda's Stand belt's Armour Evasion to Ward Conversion mod
  src/Modules/CalcDefence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7342 Add support for blocking allocated nodes when searching Militant Faith jewels
  src/Classes/DropDownControl.lua
  src/Classes/ImportTab.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: enhancement

#7275 QoL Enums Data file was added, Trade Data relative was added
  src/Export/Classes/Dat64File.lua
  src/Export/Classes/GGPKData.lua
  src/Export/Main.lua
  src/Export/Scripts/enums.lua
  src/Export/spec.lua
Labels: enhancement

#7269 Add a tooltip stat-diff toggle to Items tab
  help.txt
  src/Classes/ItemsTab.lua
Labels: enhancement

#7678 Fix maximum sustainable stages calculations ignoring certain buffs/mods
  spec/System/TestSkills_spec.lua
  src/Modules/CalcPerform.lua
Labels: bug:calculation

#7244 Improve handling of trigger chance.
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7662 Add supports for Multi mine/trap throws
  src/Data/SkillStatMap.lua
  src/Modules/Build.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7761 Add editorconfig configuration
  .editorconfig
Labels: technical

#7212 Add support for multiple configurations
  help.txt
  src/Classes/ConfigSetListControl.lua
  src/Classes/ConfigTab.lua
  src/Classes/ItemSetListControl.lua
  src/Classes/PassiveSpecListControl.lua
  src/Classes/SkillSetListControl.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7758 Fix incorrect calculation of effecive crit/hit chance for triggers when using skills that hit with both weapons at the same time
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7763 Add search to the Calcs tab
  src/Classes/CalcSectionControl.lua
  src/Classes/CalcsTab.lua
  src/Data/Global.lua
Labels: user-interface

#6809 Enemy dot skills
  src/Data/BossSkills.lua
  src/Export/Enemies/BossSkills.txt
  src/Export/Scripts/bossData.lua
  src/Modules/Build.lua
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7749 Tinctures
  src/Classes/ImportTab.lua
  src/Classes/Item.lua
  src/Classes/ItemDBControl.lua
  src/Classes/ItemsTab.lua
  src/Data/Bases/tincture.lua
  src/Data/ModTincture.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7721 Update gems with 3.25 balance changes
  src/Data/Gems.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/other.lua
  src/Data/Skills/sup_int.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/aura_skill_stat_descriptions.lua
  src/Data/StatDescriptions/banner_aura_skill_stat_descriptions.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/other.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7760 Fix trigger chance apping to self triggers that assume max rate
  src/Modules/CalcTriggers.lua
Labels: bug:calculation

#7773 Champion foritfy
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7777 fix crash from avoidance chance
  src/Modules/CalcDefence.lua
Labels: technical

#7779 Use pre-armour physical damage as base damage for impale damage calculation
  src/Modules/CalcOffence.lua
Labels: enhancement

#7800 Fix "damage with Bleeding" mod not working
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#7799 Fix War Banner not granting damage to Bleed
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: calculation

#7798 Fix Fist of War description not applying damage to Ailments
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/gem_stat_descriptions.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug: accuracy

#7797 Fix Blade Flurry using the wrong damage effectiveness values
  src/Data/Skills/act_dex.lua
Labels: bug: accuracy

#7791 Fix Seismic Cry including old AoE increase mod
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug: accuracy

#7789 Fix tree selection hotkey double selecting
  src/Classes/TreeTab.lua
Labels: bug, user-interface

#7802 Fix Power Siphon not benefiting from Spell Damage
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: behaviour

#7803 Fix Caustic Arrow of Poison still have Flat Damage
  src/Data/Skills/act_dex.lua
Labels: bug: accuracy

#7806 Fix pathing from Ascendant path node to class start
  src/Classes/PassiveSpec.lua
Labels: bug: behaviour

#7810 Fix Valour incorrectly granting increased Aura effect instead of more Aura Effect
  src/Data/SkillStatMap.lua
Labels: bug: calculation

#7807 Fix Perfect Agony not including on enemy effects
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#7811 Fix Divine Blessing flat cost not appearing in breakdown
  src/Modules/CalcSections.lua
Labels: bug: behaviour

#7823 Fix Blood Rage not granting Attack damage leech
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
Labels: bug: behaviour

#7819 Fix Lethal Pride granting Phys as Extra Fire instead of Rage on hit
  src/Data/TimelessJewelData/LegionPassives.lua
Labels: bug: accuracy

#7817 Fix Svalinn Lucky block mod not applying to Spell Block
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#7814 Fix Enduring Cry having incorrect duration
  src/Data/Skills/act_str.lua
Labels: bug: behaviour

#7813 Fix Seismic Cry more AoE mod scaling with Buff Effect
  src/Modules/CalcPerform.lua
Labels: bug: calculation

#7812 Fix Seething Fury not working with Perfect Agony
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#7815 Update Claw base Critical Strike Chance for 3.25
  src/Data/Bases/claw.lua
Labels: bug: calculation

#7822 Add toggle for node search vieport edge highlight
  src/Classes/PassiveTreeView.lua
  src/Modules/Main.lua
Labels: user-interface

#7825 Fix crash when trying to add gems to Penance Brand of Dissipation
  src/Modules/CalcPerform.lua
Labels: crash

#7828 Update Axe, Dagger, Sceptre, Staff and Flask Bases with 3.25 Changes
  src/Data/Bases/axe.lua
  src/Data/Bases/dagger.lua
  src/Data/Bases/flask.lua
  src/Data/Bases/mace.lua
  src/Data/Bases/staff.lua
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7842 Update Death Aura damage with 3.25 changes
  src/Data/Skills/other.lua
Labels: enhancement

#7839 Fix Herald of Ash Phys as extra Fire scaling
  src/Data/Skills/act_str.lua
Labels: bug: accuracy

#7837 Fix Seismic Cry AoE calculation
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
Labels: bug: calculation

#7831 Fix impale not using enemy damage taken
  spec/System/TestImpale_spec.lua
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#7866 Fix Rage Effect not applying to "per x Rage" mods
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#7865 Update Tattoo Keystones with 3.25 Changes
  src/Data/ModCache.lua
  src/Data/TattooPassives.lua
Labels: enhancement

#7864 Update Legion Notables with 3.25 changes
  src/Data/TimelessJewelData/LegionPassives.lua
Labels: enhancement

#7861 Fix Autoexertion and Call to Arms not disabling Warcry buffs
  src/Data/ModCache.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_str.lua
  src/Data/StatDescriptions/skill_stat_descriptions.lua
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#7851 Fix Tincture Mana Burn rate applying inversely
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
Labels: bug: calculation

#5914 Add support for changing item quality in the standard edit item interface
  src/Classes/ItemsTab.lua
Labels: enhancement

#7862 Fix crash when hovering over Tinctures in Item tab
  src/Classes/ItemsTab.lua
Labels: crash

#7824 Add support to search Character import list by Ascendancy
  src/Classes/DropDownControl.lua
  src/Classes/ImportTab.lua
Labels: user-interface

#7872 Change ArcaneSurge cast speed increase to ModFlag.Cast
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#7884 Update Fungal and Profane Ground with 3.25 changes
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#7883 Fix Cyclone of Tumult and Dual Strike of Impaling gem values
  src/Data/Skills/act_dex.lua
Labels: bug: accuracy

#7881 Fix Cruel Retort granting Attack/Cast speed to all skills
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#7880 Add automatic calculation for Rage sacrificed when using Rage Vortex
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7879 Add config options to override the number of Trap/Mines per throw
  src/Modules/CalcOffence.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#7853 Banner debuff change
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: crash, bug: calculation

#7847 Relax matching for loadout names and allow groups at any spot
  src/Modules/Build.lua
Labels: bug: behaviour

#7892 Fix Flesh and Stone less damage taken scaling from Aura effect
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#7894 Fix quality not applying to Tincture duration
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#7898 Fix impale not using damage taken *from hits*
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#7890 Fix Cleave of Rage area not scaling with Rage effect
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#7909 Fix Critical Strike Chance of some Rune Daggers
  src/Data/Bases/dagger.lua
Labels: bug: accuracy

#7914 Fix Rallying Cry Exerted damage mod not working with Autoexertion
  src/Modules/CalcPerform.lua
Labels: bug: calculation

#7915 Fix Seismic Cry AoE mod not applying sometimes
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#7916 Fix Rage Vortex AoE per sacrificed Rage mod not working
  src/Classes/ModStore.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#7918 Fix Maligoro's Virtuosity not working with Perfect Agony
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#7919 Fix Mana cost for Infernal Cry
  src/Data/Skills/act_str.lua
Labels: bug: accuracy

#7920 Fix Partytab Mine Export Crash
  src/Modules/CalcPerform.lua
Labels: crash

#7922 Fix Banner skills not applying to Minions
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: behaviour

#7924 Fix AoE from Fist of War not applying to supported skills
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
Labels: bug: behaviour

#7925 Fix Fungal Ground debuff to apply to all Resistances
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#7904 Fix cancelling tree version conversion didn't revert back to previous value in dropdown
  src/Classes/TreeTab.lua
Labels: user-interface

#7846 Explicitely check for 1 size sets for loadouts
  help.txt
  src/Classes/ConfigTab.lua
  src/Classes/ItemSetListControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/SkillsTab.lua
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: bug: behaviour

#7926 Update unique Staves with block changes
  src/Data/Bases/staff.lua
  src/Data/Uniques/staff.lua
Labels: bug: accuracy

#7389 Add latest and trending builds list to the build list module
  help.txt
  runtime/SimpleGraphic/Fonts/Liberation Sans Bold.18.tga
  runtime/SimpleGraphic/Fonts/Liberation Sans Bold.tgf
  src/Assets/ascendants/ascendant.jpeg
  src/Assets/ascendants/assassin.jpeg
  src/Assets/ascendants/berserker.jpeg
  src/Assets/ascendants/champion.jpeg
  src/Assets/ascendants/chieftain.jpeg
  src/Assets/ascendants/deadeye.jpeg
  src/Assets/ascendants/duelist.jpeg
  src/Assets/ascendants/elementalist.jpeg
  src/Assets/ascendants/gladiator.jpeg
  src/Assets/ascendants/guardian.jpeg
  src/Assets/ascendants/hierophant.jpeg
  src/Assets/ascendants/inquisitor.jpeg
  src/Assets/ascendants/juggernaut.jpeg
  src/Assets/ascendants/marauder.jpeg
  src/Assets/ascendants/necromancer.jpeg
  src/Assets/ascendants/occultist.jpeg
  src/Assets/ascendants/pathfinder.jpeg
  src/Assets/ascendants/raider.jpeg
  src/Assets/ascendants/ranger.jpeg
  src/Assets/ascendants/saboteur.jpeg
  src/Assets/ascendants/scion.jpeg
  src/Assets/ascendants/shadow.jpeg
  src/Assets/ascendants/slayer.jpeg
  src/Assets/ascendants/templar.jpeg
  src/Assets/ascendants/trickster.jpeg
  src/Assets/ascendants/warden.jpeg
  src/Assets/ascendants/witch.jpeg
  src/Classes/BuildListControl.lua
  src/Classes/ExtBuildListControl.lua
  src/Classes/ExtBuildListProvider.lua
  src/Classes/ImportTab.lua
  src/Classes/PoBArchivesProvider.lua
  src/Classes/PopupDialog.lua
  src/Export/Main.lua
  src/Modules/Build.lua
  src/Modules/BuildList.lua
  src/Modules/BuildSiteTools.lua
  src/Modules/Common.lua
  src/Modules/Main.lua
Labels: enhancement

#7930 Cleanup impale
  src/Modules/CalcOffence.lua
Labels: technical

#7934 update impale tests
  spec/System/TestImpale_spec.lua
Labels: technical

#7954 Fixed monster explosion ignite divide by 0 calculation error
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#7950 Dark seer missing global chance to blind on hit
  src/Data/Uniques/mace.lua
Labels: bug: accuracy

#7949 - Update skill gem description for Puncture
  src/Data/Skills/act_dex.lua
Labels: bug: accuracy

#7979 Fix gladiator shield block override from counting as from the shield
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#7985 Fix crash with gem selection/addition
  src/Export/statdesc.lua
  src/Modules/StatDescriber.lua
Labels: crash, technical

#7988 Add support for all new 3.25 Gems
  spec/System/TestTriggers_spec.lua
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/act_str.lua
  src/Data/Skills/sup_dex.lua
  src/Data/Skills/sup_str.lua
  src/Export/Skills/act_dex.txt
  src/Export/Skills/act_int.txt
  src/Export/Skills/act_str.txt
  src/Export/Skills/sup_dex.txt
  src/Export/Skills/sup_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement
