Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-07, with the labels that each got.

#8764 Fix Runegraft bonus for Boots / Gloves scaling skill gems
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#8763 Fix Hand of Phrecia applying auras on enemies
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8325 Fix Elemental Overload not reducing Ailment chance to 0
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8773 Fix Phantasmal Might not working when Summon Phantasm was linked to Spell Totem
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
Labels: bug: behaviour

#8771 Fix Multistrike + Awakened Spell Echo not working properly with minions
  src/Data/SkillStatMap.lua
  src/Modules/ConfigOptions.lua
Labels: bug: calculation

#8804 Fix trigger based reservation pooling
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8803 Fix Item sort option for "Current Usable" not using taking into account attribute requirement mods
  src/Classes/ItemDBControl.lua
Labels: bug: behaviour

#8800 Fix values changing depending on order of skill groups
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#8779 Fix Minion Scaling mods on Spinehail scaling with Widowhail
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: calculation

#8801 Minor cleanup of the Autoexersion skill gem implementation
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
  src/Modules/CalcTriggers.lua
Labels: technical, bug: behaviour

#8830 Fix Righteous Fire of Arcane Devotion more Cast Speed mod not working
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: bug: accuracy

#8823 Remove Channelling time config box for Focused Channelling - Existing users should update their config
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/ConfigOptions.lua
Labels: user-interface

#8819 Fix Summon Spider / Spectral Wolf count config not scaling with Dark Monarch
  src/Classes/ModStore.lua
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#8815 Fix Aura effect scaling when using Hand of Phrecia and "effect of auras on you" mods
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8814 Fix Attribute Requirement sorting
  src/Modules/CalcPerform.lua
Labels: user-interface

#8812 Fix Nametaker not instant leeching Mana and Energy Shield
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8810 Fix Plague Bearer default config not applying
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#8852 Fix autoexertion modifying active skill tables
  src/Modules/CalcTriggers.lua
Labels: crash

#8846 Fix Iron Mass giving Skeletons Triple Damage in Offhand
  src/Classes/ModStore.lua
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8841 Fix missing Minion DoT multiplier from critical hits
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#8883 Fix Mine Aura effect scaling Curses used with High-Impact Mine
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8878 Fix Devouring Diadem in unique list using suffix veiled mods
  src/Data/ModCache.lua
  src/Data/Uniques/helmet.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#8862 Fix rounding of scaled mods being incorrect in some cases
  src/Classes/ModList.lua
  src/Modules/CalcSetup.lua
Labels: bug: calculation

#8886 Update Cinderswallow and support new mods
  src/Data/ModCache.lua
  src/Data/Uniques/flask.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#8888 Fix Kaladra's Touch not copying influence from other ring
  src/Modules/CalcSetup.lua
Labels: bug: behaviour
