Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-01, with the labels that each got.

#8199 Implement a docker container for tests
  .github/workflows/builddocker.yml
  .github/workflows/test.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement, technical

#8387 improve "set up the exporter" tutorial
  CONTRIBUTING.md
Labels: documentation, technical

#8371 fix: caps/spelling/space
  src/Modules/CalcDefence.lua
  src/Modules/CalcSections.lua
  src/Modules/ConfigOptions.lua
Labels: technical

#8392 Fix crash caused by lack of envirement override propagation
  src/Modules/CalcSetup.lua
  src/Modules/Calcs.lua
Labels: crash

#8409 Fix GemProperty mod not being affected by scaling
  src/Modules/ModParser.lua
Labels: bug: calculation

#8414 Implement lua side hotkey for screenshots
  src/Launch.lua
Labels: technical

#8425 Automate creating PR for SimpleGraphic releases
  .github/workflows/update-simple-graphic.yml
Labels: technical

#8412 Fix fallout from SimpleGraphic upgrade with wider Unicode support
  Dockerfile
  src/Classes/EditControl.lua
  src/Modules/Common.lua
  src/TreeData/PSPointsFrame.png
  src/TreeData/PSStartNodeBackgroundInactive.png
  src/UpdateCheck.lua
Labels: enhancement, bug: behaviour, pob2
