Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-09, with the labels that each got.

#8979 [PATCH] chore: update cspell to run on push
  .github/workflows/spellcheck.yml
Labels: technical, pob2-merged

#8977 Fix LIST type mods being duplicated
  src/Classes/ModList.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#8959 Automatically check if the ModCache needs to be regenerated
  .github/workflows/test.yml
  src/Data/ModCache.lua
  src/Modules/Main.lua
Labels: technical

#8976 Update uniques
  src/Data/ModCache.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/axe.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/body.lua
  src/Data/Uniques/boots.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/quiver.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/staff.lua
  src/Data/Uniques/wand.lua
Labels: enhancement

#8972 Fix typos "unscaleable" to "unscalable"
  docs/modSyntax.md
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
Labels: technical
