Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-06, with the labels that each got.

#8611 Fix Tincture CDR mod and Mana Burn rate display bug
  src/Classes/Item.lua
  src/Classes/ItemsTab.lua
Labels: bug: calculation

#8599 Adjusted war cry uptime tooltip
  src/Modules/CalcOffence.lua
Labels: user-interface

#8580 Fix many unique staves with Attack block instead of Spell block implicit
  src/Data/Uniques/staff.lua
Labels: bug: accuracy

#8578 Add support for Settling Ash tree passive
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8569 Add Shaper influence to Tides of Time unique belt
  src/Data/Uniques/belt.lua
Labels: bug: accuracy

#8561 Add support for Aquamarine Flask "reduced effect of freeze on you"
  src/Modules/ModParser.lua
Labels: enhancement

#8574 Fix Dominating Blow Hit counting multiple times when used in FullDPS
  src/Modules/Calcs.lua
  src/Modules/ConfigOptions.lua
Labels: bug: accuracy

#8575 Fix Gem-lined Cap Ascendancy Notable not applying
  src/Modules/CalcTools.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#8637 Update Death Aura damage
  src/Data/Skills/other.lua
Labels: bug: calculation

#8625 Update Arcane Surge cast speed from 10% to 20%
  src/Modules/CalcPerform.lua
Labels: enhancement

#8590 Improve MoM+EB(+ES bypass) calculations
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#8618 Update Scold's Bridle self damage wording
  src/Data/ModCache.lua
  src/Data/Uniques/helmet.lua
  src/Modules/ModParser.lua
Labels: bug: accuracy

#6868 Add support for Wintertide Brand average DOT calculation
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: enhancement

#8658 Update Arcane Surge tooltip
  src/Modules/ConfigOptions.lua
Labels: bug: accuracy

#8652 Fix globalLimit being sensitive to tag order
  spec/System/TestDefence_spec.lua
  src/Classes/ModDB.lua
  src/Classes/ModStore.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8469 Resume failed update feature
  src/UpdateCheck.lua
Labels: enhancement

#8377 Removed action speed calculation and breakdown display for Explosive Arrow
  src/Data/Skills/act_dex.lua
Labels: bug: calculation

#8624 Enable Sorting of folders by date and inherit the sort order in the build save dialog
  src/Classes/FolderListControl.lua
  src/Modules/BuildList.lua
Labels: user-interface, pob2

#8666 Fix Nebulis and similar mods being treated as uncapped
  spec/System/TestItemMods_spec.lua
  src/Classes/ModStore.lua
Labels: bug: behaviour

#8671 Fix CWC not supporting triggerbots
  spec/System/TestTriggers_spec.lua
  src/Modules/CalcTriggers.lua
Labels: bug: calculation

#8673 Export Dexterity gems
  src/Data/ModCache.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_dex.lua
  src/Export/Skills/act_dex.txt
  src/Modules/ModParser.lua
Labels: enhancement

#8676 Add support for strength-based Trarthus gems
  src/Data/Gems.lua
  src/Data/SkillStatMap.lua
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: enhancement

#8679 Implement intelligence Trarthus gems and Starfall
  src/Data/Gems.lua
  src/Data/ModCache.lua
  src/Data/Skills/act_int.lua
  src/Data/Skills/other.lua
  src/Export/Skills/act_int.txt
  src/Export/Skills/other.txt
  src/Modules/CalcTriggers.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8681 Add support for Cold Dot Multiplier Per Overcapped Cold Res Mastery
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8705 Update EmmyLua VSCode debugging tutorial
  CONTRIBUTING.md
Labels: documentation, technical

#8717 Fix effective inherited cooldown not being affected by correct conditional icdr in hybrid triggers
  src/Modules/Build.lua
  src/Modules/BuildDisplayStats.lua
  src/Modules/CalcSections.lua
  src/Modules/CalcTriggers.lua
Labels: bug: behaviour

#8694 Fix Dual Strike of Ambidexterity causing crash
  src/Modules/CalcMirages.lua
  src/Modules/CalcOffence.lua
Labels: crash

#8698 Add support for various "Infamous" (Mercenary exclusive) item modifiers
  src/Data/ModCache.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8728 fix Mastery node right-click crash (runegraft)
  src/Classes/TreeTab.lua
Labels: technical

#8735 Add support for Runegraft mods
  src/Classes/Item.lua
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcSetup.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8729 Update EmmyLua VSCode debugging tutorial 2
  CONTRIBUTING.md
Labels: documentation, technical

#8738 Fix Skill Set allowing editing a nil value after saving new Skill Set
  src/Classes/SkillSetListControl.lua
Labels: crash

#8740 Fix Summon Phantasm minion level incorrectly using the active gem level
  src/Data/Skills/sup_int.lua
  src/Export/Skills/sup_int.txt
  src/Modules/CalcActiveSkill.lua
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8185 Predefine build name on character import.
  src/Classes/ImportTab.lua
  src/Modules/Build.lua
  src/Modules/Main.lua
Labels: enhancement

#8190 Fix Add 'Cast Time' to Calcs page for Warcries
  src/Modules/CalcSections.lua
Labels: enhancement

#8756 Fix The Dark Monarch not scaling "per summoned x" mods
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8754 Fix Swift Affliction less duration and damaging ailment duration not applying individually
  src/Data/SkillStatMap.lua
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug: behaviour

#8749 Fix crash when trying to edit Config/Item Set after saving a new Set
  src/Classes/ConfigSetListControl.lua
  src/Classes/ItemSetListControl.lua
Labels: crash

#8746 Fix Runegraft bonus for Boots / Gloves not working
  src/Classes/ModStore.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour
