Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-02, with the labels that each got.

#8435 update issue templates
  .github/ISSUE_TEMPLATE/accuracy_bug_report.yaml
  .github/ISSUE_TEMPLATE/application_bug_report.yaml
  .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml
  .github/ISSUE_TEMPLATE/calculation_bug_report.yaml
  .github/ISSUE_TEMPLATE/crash_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: technical

#8452 fix caps pob-poe1 edition
  src/Export/Classes/GGPKData.lua
  src/Export/Scripts/tattooPassives.lua
Labels: technical

#8419 Fixes Cinderswallow Urn mod missing in current version.
  src/Data/Uniques/flask.lua
Labels: bug

#8449 Add support for Legacy Of Phrecia Ascendancies
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8438 Update readme.md, contributing.md
  CONTRIBUTING.md
  README.md
  docker-compose.yml
Labels: documentation, technical

#8456 Add more Legacy of Phrecia Mods
  src/Data/ModCache.lua
  src/Data/Uniques/Special/New.lua
  src/Data/Uniques/belt.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/helmet.lua
  src/Data/Uniques/jewel.lua
  src/Data/Uniques/mace.lua
  src/Data/Uniques/ring.lua
  src/Data/Uniques/shield.lua
  src/Data/Uniques/sword.lua
  src/Data/Uniques/tincture.lua
  src/Modules/CalcOffence.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8430 Improve EHP accuracy
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
  src/Modules/Data.lua
Labels: bug: calculation

#8417 Fixed interaction between block replacement effect from Determined Survivor and Necromantic Aegis
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#8416 Implement ability to delete folders with contents
  src/Classes/BuildListControl.lua
Labels: enhancement, user-interface, pob2

#8393 Fixed Non-Damaging Ailment issue with Critical Mastery in Calc Screen
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8253 Fix Viper Strike of Mamba poison
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug: calculation

#8254 Revert sidebar poison to split posion dps again
  src/Modules/CalcOffence.lua
  src/Modules/CalcSections.lua
Labels: bug: accuracy

#8342 Disable "gain when hit" for builds which cannot survive unlucky hits
  src/Modules/CalcDefence.lua
Labels: bug: behaviour

#8463 Fix maximum virulence parsing for multi digit increases
  src/Modules/ModParser.lua
Labels: bug: calculation

#8466 fix-typos-comments
  src/Modules/CalcOffence.lua
Labels: technical

#8465 Fix various issues with Legacy of Phrecia ascendancies
  src/Data/Uniques/Special/New.lua
Labels: bug: accuracy

#8471 Add Wildspeaker, Blind Prophet, Aristocrat and Puppeteer jewels
  src/Data/Uniques/Special/New.lua
Labels: enhancement

#8476 Add Ancestral Commander, Behemoth, Bog Shaman, and Scavenger Ascendancy Jewels
  src/Data/ModCache.lua
  src/Data/Uniques/Special/New.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8459 Fix ES bypass regression
  spec/System/TestDefence_spec.lua
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#8483 Fix Eyes of the Greatwolf DoT Multi wording
  src/Data/Uniques/amulet.lua
Labels: bug: accuracy

#8500 Fix influences not importing correctly
  src/Classes/ImportTab.lua
Labels: bug: accuracy

#8481 Add checkbox for Sacrificial Zeal
  src/Data/ModCache.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8487 Add black background to detail text in character dropdown
  src/Classes/DropDownControl.lua
Labels: enhancement, user-interface, pob2

#8507 Fix Tawhoa's Chosen crash when no active skill is enabled
  src/Modules/CalcActiveSkill.lua
Labels: crash

#8508 Fix Forbidden jewels not finding the right ascendancy nodes
  src/Classes/CalcBreakdownControl.lua
  src/Classes/PassiveTree.lua
  src/Modules/CalcSetup.lua
Labels: bug: behaviour

#8506 Dynamically expand some dropdowns that were too narrow to read
  src/Classes/TreeTab.lua
  src/Modules/Build.lua
Labels: user-interface

#8518 Fix error when crafting a fishing rod enchant
  src/Data/EnchantmentWeapon.lua
  src/Export/Scripts/enchant.lua
Labels: bug

#8519 Add new Harbinger skills
  src/Data/ModCache.lua
  src/Data/Skills/other.lua
  src/Export/Skills/other.txt
Labels: enhancement
