Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-08, with the labels that each got.

#8889 Fix Howlcrack causing inf DPS with Generals Cry
  src/Data/Global.lua
  src/Modules/CalcMirages.lua
  src/Modules/CalcPerform.lua
  src/Modules/CalcTriggers.lua
  src/Modules/Calcs.lua
Labels: bug: behaviour

#8905 Fix crash when clicking "Add modifier" button on Tinctures
  src/Classes/ItemsTab.lua
Labels: crash

#8900 Use harmonic mean for dual wield attack speed calc instead of average
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8904 Adding Beastcrafts to Item Crafter
  src/Classes/ItemsTab.lua
  src/Data/BeastCraft.lua
  src/Export/Scripts/mods.lua
  src/Modules/Data.lua
Labels: enhancement

#8912 Fix Volatility applying to Minion Spell skills
  src/Data/Skills/sup_str.lua
  src/Export/Skills/sup_str.txt
Labels: bug: behaviour

#7650 Add support for Defiance of Destiny Gain before enemy hit
  src/Data/ModCache.lua
  src/Modules/CalcDefence.lua
  src/Modules/ConfigOptions.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8915 Fix Temporal Chains double counting towards Brand Ticks
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8916 Add support for duration of Ailments Retaliation mastery
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8918 Fix Shepherd of Souls applying twice with 2 Yaomac's Accord equipped
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8922 Tooltip text "tattoo" or "runegraft" based on node type
  src/Classes/PassiveTreeView.lua
Labels: user-interface

#8925 Add text after red mods to show that PoB does not currently handle them
  src/Classes/GemSelectControl.lua
  src/Classes/ItemsTab.lua
  src/Classes/NotableDBControl.lua
  src/Classes/PassiveTreeView.lua
  src/Classes/SkillsTab.lua
  src/Classes/Tooltip.lua
  src/Modules/ItemTools.lua
  src/Modules/Main.lua
Labels: user-interface

#8931 Fix Glacial Hammer of Shattering missing crit chance every 3rd use
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
Labels: bug: calculation

#8946 Fix Ancestral Vision not working correctly with The Arkhon's Tools
  src/Modules/CalcPerform.lua
Labels: bug: behaviour

#8950 Update mods on several uniques to use metres for radius instead of units
  fix_ascendancy_positions.py
  src/Data/Uniques/amulet.lua
  src/Data/Uniques/bow.lua
  src/Data/Uniques/flask.lua
  src/Data/Uniques/gloves.lua
  src/Data/Uniques/shield.lua
Labels: bug: accuracy

#8955 fix: spelling in changelogs
  CHANGELOG.md
  changelog.txt
Labels: documentation, technical

#8956 Fix Spell Echo not working with some Minion skills
  src/Data/SkillStatMap.lua
Labels: bug: calculation

#8954 Correct skill slot comparison for General's Cry detection
  src/Modules/CalcMirages.lua
Labels: bug: calculation
