Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-03, with the labels that each got.

#8547 Remove Royale mods from craft menu and exporter
  src/Data/ModItem.lua
  src/Export/Scripts/mods.lua
Labels: bug: accuracy

#8546 Add support for Rejuvenation Totem helm enchant
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/ModParser.lua
Labels: enhancement

#8542 Change Sacrificial Zeal to be opt in rather than opt out
  src/Modules/ConfigOptions.lua
Labels: bug: behaviour

#8536 Fix Foxshade life modifiers preventing life mastery
  src/Modules/Data.lua
Labels: bug: behaviour

#8528 Add support for Felbog Fang hindered mod
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8527 Add support for "minions recover #% life on block"
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8526 Add support for Assured Strike tree node
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8523 Add a warning when more than one Aspect skill is active
  src/Modules/Build.lua
  src/Modules/ConfigOptions.lua
Labels: enhancement

#8522 Fix Gruthkul's Pelt disabling on hit curses
  src/Modules/CalcActiveSkill.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8530 Fix issues around importing to the wrong tree
  src/Classes/ImportTab.lua
Labels: bug

#8549 Remove channeling part from Divine Ire of Disintegration
  src/Data/Skills/act_int.lua
  src/Export/Skills/act_int.txt
Labels: user-interface

#8551 Fix Gain Ward instead of Armour/Evasion mod when total is above 100
  src/Modules/CalcDefence.lua
Labels: bug: calculation

#8550 Fix Herald of Ask damage showing negative values
  src/Data/Skills/act_str.lua
  src/Export/Skills/act_str.txt
  src/Modules/CalcOffence.lua
Labels: bug: calculation

#8548 Fix Puppeteer Caustic Ground on death calculation
  src/Data/ModCache.lua
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
  src/Modules/ModParser.lua
Labels: bug: calculation

#8552 Fix Minion supports not scaling Siegebreaker ground DoT
  src/Data/Skills/minion.lua
  src/Export/Skills/minion.txt
Labels: bug: behaviour

#8555 Fix The Baron and Rotting Might not stacking correctly
  src/Data/ModCache.lua
  src/Modules/CalcPerform.lua
  src/Modules/ModParser.lua
Labels: bug: behaviour

#8557 Add support for Ewar's Mirage +1 projectile when in off hand
  src/Data/ModCache.lua
  src/Modules/ModParser.lua
Labels: enhancement

#8559 Add Karui Backburner Spectre
  src/Data/Skills/spectre.lua
  src/Data/Spectres.lua
  src/Export/Minions/Spectres.txt
  src/Export/Skills/spectre.txt
Labels: enhancement
