Repository PathOfBuildingCommunity/PathOfBuilding, pull requests merged in 2025-04, with the labels that each got.

#8594 Add resource lost information to enemy damage breakdown
  src/Modules/CalcDefence.lua
Labels: enhancement

#8596 Create workflows for porting changes
  .github/workflows/backport.yml
  .github/workflows/backport_receive.yml
Labels: technical

#8597 Fix missing datSource on new installs
  src/Export/Classes/GGPKSourceListControl.lua
  src/Export/Main.lua
Labels: pob2

#8565 feat: exporter: add clear output button
  src/Export/Main.lua
Labels: technical
